mywork/force-app/main/default/objects/ALM_Private__c/ALM_Private__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Private ALM Settings</description>
    <label>ALM Private</label>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Private__c/fields/Consumer_Key__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Key__c</fullName>
    <description>Consumer key for OAuth connected app.</description>
    <inlineHelpText>Consumer key for OAuth connected app.</inlineHelpText>
    <label>Consumer Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Private__c/fields/Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret__c</fullName>
    <description>Consumer secret for OAuth connected app</description>
    <inlineHelpText>Consumer secret for OAuth connected app</inlineHelpText>
    <label>Consumer Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Jenkins_Build__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jenkins Build</label>
    <referenceTo>Jenkins_Build__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <inlineHelpText>Link to download the build package</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Is_ALM_Instance__c.field-meta.xml
<CustomField>
    <fullName>Is_ALM_Instance__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that this is the instance in which the ALM package is installed</inlineHelpText>
    <label>Is ALM Instance</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/Jenkins_Build__c.object-meta.xml
<CustomObject>
    <label>Jenkins Build</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jenkins Build Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jenkins Builds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Jenkins_Job__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Job__c</fullName>
    <label>Jenkins Job</label>
    <referenceTo>Jenkins_Job__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <description>The url of the build package sent to jenkins</description>
    <inlineHelpText>The url of the build package sent to jenkins</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Config__c/Jenkins_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Represents a configuration for a Jenkins CI build server.</description>
    <label>Jenkins Config</label>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Represents a Jenkins CI build server endpoint.</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/User_API_Token__c.field-meta.xml
<CustomField>
    <fullName>User_API_Token__c</fullName>
    <description>Represents a Jenkins CI user API token.</description>
    <label>User API Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <description>Represents a Jenkins CI user ID.</description>
    <label>User ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/Jenkins_Job__c.object-meta.xml
<CustomObject>
    <description>Represents a job on a Jenkins CI build server.</description>
    <label>Jenkins Job</label>
    <nameField>
        <label>Jenkins Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jenkins Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Represents a relative URL path to a job on a Jenkins CI build server.</description>
    <label>Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents a Sightline release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Represents an authentication token for a job on a Jenkins CI build server.</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/TestJenkinsStartJobRequest.cls
@isTest
private class TestJenkinsStartJobRequest {

	private static Auth_User__c authUser;
	private static Build__c build;
	private static Instances__c instance;
	private static Jenkins_Build__c jenkinsBuild;
	private static Jenkins_Job__c jenkinsJob;
	private static Release__c release;
	private static Jenkins_Config__c jenkinsConfig;
	private static ALM_Private__c sightlineSettings;

	static void setup() {
		System.runAs(TestingUtils.ADMIN_USER) {
			release = new Release__c(Name='Jenkins Release');
			insert release;

			instance = new Instances__c(Name='Jenks-Instance', Is_ALM_Instance__c=true);
			insert instance;

			jenkinsJob = TestingUtils.createJenkinsJob(instance.Id, release.Id);
			jenkinsBuild = TestingUtils.createJenkinsBuild(jenkinsJob.Id);

			build = TestingUtils.buildBuild(release.Id, jenkinsBuild.Id);
			insert build;
			// Setting isForTools to true because that's OAuthService.getSightlineUser() returns the auth user of the sightline Instance, which is isForTools === true
			authUser = TestingUtils.createAuthUser(UserInfo.getUserId(), instance.Id, true);
			authUser.Refresh_Token__c = 'jenks-refresh-token-123';
			update authUser;

			sightlineSettings = TestingUtils.createOAuthSettings();
			setupJenkinsConfig();
		}
	}

	static void setupJenkinsConfig() {
		jenkinsConfig = new Jenkins_Config__c(
				Endpoint__c = 'TEST_ENDPOINT',
				User_ID__c = 'TEST_USER_ID',
				User_API_Token__c = 'TEST_USER_API_TOKEN'
		);
		insert jenkinsConfig;
	}

	static testMethod void jenkinsStartJobRequest_constructor() {
		setup();

		Test.startTest();
			JenkinsStartJobRequest jenkinsJobRequest = new JenkinsStartJobRequest(
					jenkinsBuild.Name, jenkinsBuild.Jenkins_Job__r.Token__c, jenkinsBuild.Jenkins_Job__r.Path__c,
					build.Package_Url__c);
		Test.stopTest();

		System.assertEquals(jenkinsBuild.Name, jenkinsJobRequest.jenkinsBuildName,
				'The Jenkins Build Name should match');
		System.assertEquals(build.Package_Url__c, jenkinsJobRequest.buildPackageUrl,
				'The build package url should be correct');
		System.assertEquals(jenkinsConfig.Endpoint__c + jenkinsBuild.Jenkins_Job__r.Path__c, jenkinsJobRequest.jenkinsEndpoint,
				'The jenkins config endpoint should be correct');
		System.assertEquals(jenkinsConfig.User_API_Token__c, jenkinsJobRequest.jenkinsUserApiToken,
				'The jenkins config user API token should be correct');
		System.assertEquals(jenkinsConfig.User_ID__c, jenkinsJobRequest.jenkinsUserId,
				'The jenkins config user Id should be correct');
		System.assertEquals(jenkinsBuild.Jenkins_Job__r.Token__c, jenkinsJobRequest.jenkinsJobTokenParam,
				'The jenkins auth token should be correct');

		// BaseRequest fields
		System.assert(!String.isBlank(jenkinsJobRequest.sightlineServerURL),
				'The Sightline Server Url should be populated');
		System.assert(!String.isBlank(jenkinsJobRequest.organizationId),
				'The Sightline Organization Id should be populated');
		System.assertEquals(sightlineSettings.Consumer_Key__c, jenkinsJobRequest.clientId,
				'The client Id should be correct');
		System.assertEquals(sightlineSettings.Consumer_Secret__c, jenkinsJobRequest.clientSecret,
				'The client secret should be correct');
		System.assertEquals(authUser.Refresh_Token__c, jenkinsJobRequest.sightlineRefreshToken,
				'The sightlineRefreshToken should be correct');
	}
}