mywork/force-app/main/default/objects/Feedback_API_Mapping__c/Feedback_API_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores field mapping from for
Feedback API.  Mapping is from source field name to target field name.</description>
    <label>Feedback API Mapping</label>
</CustomObject>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Comparison_Value__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Value__c</fullName>
    <description>Comparison value to match operator against</description>
    <inlineHelpText>Comparison value to match operator against (Only populate if this is a complex mapping)</inlineHelpText>
    <label>Comparison Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Is_Complex__c.field-meta.xml
<CustomField>
    <fullName>Is_Complex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate that the mapping is not a 1:1 mapping from a field in the source object to a field in the target object</description>
    <inlineHelpText>Used to indicate that the mapping is not a 1:1 mapping from a field in the source object to a field in the target object</inlineHelpText>
    <label>Is Complex?</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Only 'equals' is currently supported. If blank, the target value will always be applied</description>
    <inlineHelpText>Only 'equals' is currently supported. If blank, the target value will always be applied (Only populate if this is a complex mapping)</inlineHelpText>
    <label>Operator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>Stores the API name of the field in the target SObject. The SObject type is stored in Feedback API Settings</inlineHelpText>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <description>Value to populate target field with if comparison evaluates to true - This can be in the form of a merge field on the source object e.g. {!SourceFieldName}. Otherwise, the value will be copied as is.</description>
    <inlineHelpText>Value to populate target field with if comparison evaluates to true - This can be in the form of a merge field on the source object e.g. {!SourceFieldName}. Otherwise, the value will be copied as is. (only necessary if this is a complex mapping)</inlineHelpText>
    <label>Target Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/Feedback_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Feedback REST API</description>
    <label>Feedback API Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <inlineHelpText>ID of the Org we expect to be receiving requests from.</inlineHelpText>
    <label>Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/fields/Target_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Name__c</fullName>
    <inlineHelpText>The API name of the target object to create. In most cases this will be Backlog__c</inlineHelpText>
    <label>Target Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/FeedbackRestService.cls
@RestResource(urlMapping='/FeedbackAPI/*')
global with sharing class FeedbackRestService
{
    public static String EQUALS_OPERATOR = 'equals';
    public static String NO_SETTINGS_ERROR_MSG = 'Feedback API settings have not been configured.';
    public static String INVALID_SETTINGS_ERROR_MSG = 'Feedback API settings have not been configured Properly. Invalid target object.';
    public static String INVALID_MAPPING_ERROR_MSG = 'Feedback API mapping has not been configured Properly. Please check your mappings.';
    public static String INVALID_JSON_ERROR = 'Invalid JSON data.';
    public static String UNAUTHORIZED_MSG = 'Unauthorized request.';

    /**
    *  Creates an SObject from the feedbackData
    *  @param feedbackData     JSON string representing field data for the feedback record  i.e. '{"Story_Description__c" : "value xxx"}'
    *  @param authToken    The org Id to check for authorization
    */
    @HttpPost
    global static Response create(String feedbackData, String authToken)
    {
        Feedback_API_Settings__c settings = Feedback_API_Settings__c.getInstance();
        List<Feedback_API_Mapping__c> fieldMappings = Feedback_API_Mapping__c.getAll().values();

        if( settings == null || fieldMappings.isEmpty() )
        {
            return new Response(false, NO_SETTINGS_ERROR_MSG);
        }
        else if( !isAuthorized( settings, authToken) )
        {
            return new Response(false, UNAUTHORIZED_MSG);
        }

        SObject target;

        try
        {
            target = buildTargetObject( settings.Target_Object_Name__c, fieldMappings, feedbackData);
        }
        catch( FeedbackAPIException fe )
        {
            return new Response(false, fe.getMessage());
        }
        catch( Exception e )
        {
            return new Response(false, 'An unknown error occured: ' + e.getMessage());
        }

        try
        {
            insert target;
        }
        catch( DMLException de)
        {
            return new Response(false, de.getMessage());
        }

        String name = getName(settings, target);

        return new Response(true, '', String.valueOf( target.Id ), name);
    }

    private static Boolean isAuthorized(Feedback_API_Settings__c settings, String orgId)
    {
        return (settings.Org_Id__c == orgId);
    }

    private static String getName(Feedback_API_Settings__c settings, SObject record)
    {
        String query = 'SELECT Name FROM ' + settings.Target_Object_Name__c;
        query += ' WHERE Id = \'' + record.Id + '\'';
        List<SObject> records = Database.query( query );
        if (records.isEmpty())
        {
            return '';
        }
        else
        {
        	return String.valueOf( records[0].get('Name') );
        }
    }

    /**
    * Creates an sObject of type typeName from fieldMappings using the data from fieldJSON
    *  @param typeName      The type to create
    *  @param fieldMappings  Used to map fields from the fieldJSON to the target object
    *  @param fieldJSON      JSON Field mapping for source / target object
    *  @throws FeedbackAPIException
    */
    private static sObject buildTargetObject(String typeName, List<Feedback_API_Mapping__c> fieldMappings, String fieldJSON)
    {
        Map<String, Object> sourceData;
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(typeName);
        if (targetType == null) {
            throw new FeedbackAPIException(INVALID_SETTINGS_ERROR_MSG);
        }

        try
        {
            sourceData = (Map<String, Object>) JSON.deserializeUntyped( fieldJSON );
        }
        catch(System.JSONException je)
        {
            throw new FeedbackAPIException(INVALID_JSON_ERROR);
        }

        SObject target = targetType.newSObject();

        for( Feedback_API_Mapping__c mapping : fieldMappings )
        {
            if ( sourceData.containsKey( mapping.Source_Field__c ) )
            {
                Object value = sourceData.get( mapping.Source_Field__c );

                if (mapping.Is_Complex__c)
                {
                    if (String.isBlank(mapping.Operator__c)
                        || (mapping.Operator__c.equalsIgnoreCase( EQUALS_OPERATOR )
                             && mapping.Comparison_Value__c != null
                             && mapping.Comparison_Value__c.equalsIgnoreCase( String.valueOf( value ))))
                    {
                        Formula f = new Formula( mapping.Target_Value__c );
                        value = f.evaluateSimpleMergeFields(sourceData);
                    }
                    else
                    {
                        continue;
                    }
                }

                if (value instanceof String && Formula.isDateTime( (String)value )) {
                    value = Formula.parseJSONDateTime( (String)value );
                }
                else if (value instanceof String && Formula.isDate( (String)value )) {
                    value = Date.valueOf( (String)value );
                }

                try
                {
                    target.put( mapping.Target_Field__c, value );
                }
                catch(System.SObjectException se)
                {
                    throw new FeedbackAPIException(INVALID_MAPPING_ERROR_MSG + ':' +mapping.Target_Field__c);
                }
            }
        }

        return target;
    }

    global class Response
    {
        public Boolean success;
        /*holds any error message if an error occured*/
        public String message;
        public String createdId;
        public String createdName;

        public Response( Boolean success, String message)
        {
            this.success = success;
            this.message = message;
        }
        public Response( Boolean success, String message, String createdId, String createdName)
        {
            this( success, message);
            this.createdId = createdId;
            this.createdName = createdName;
        }
    }

    global class FeedbackAPIException extends Exception {}
}