mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Child Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestComponentSearchController.cls
@isTest
private class TestComponentSearchController {
    /**--------------------------------------- DEPRECATED CLASS ---------------------------------------
    static ComponentSearchController controller;

    private static void createTestComponents() {
        controller = new ComponentSearchController();

        Component__c c1 = new Component__c(Name='Test object', Type__c='Apex Class');
        insert c1;

        Component__c c2 = new Component__c(Name='Test Apex Trigger', Type__c='Apex Trigger');
        Component__c c3 = new Component__c(Name='Test custom field 1', Type__c='Apex Unit Test', Parent_Component__c=c1.Id);
        Component__c c4 = new Component__c(Name='Test custom field 2', Type__c='Apex Unit Test', Parent_Component__c=c1.Id);
        Component__c[] components = new Component__c[] {c2, c3, c4};
        insert components;
    }

    static testMethod void testToggleSort_Name() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'desc';

        controller.toggleSort(); // results in ascending

        System.assertEquals('Test custom field 1', controller.searchResultsWrapper.get(0).component.Name);
        System.assertEquals('Test custom field 2', controller.searchResultsWrapper.get(1).component.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(2).component.Name);
        System.assertEquals('Test Apex Trigger', controller.searchResultsWrapper.get(3).component.Name);

        controller.toggleSort(); // results in descending

        System.assertEquals('Test custom field 1', controller.searchResultsWrapper.get(3).component.Name);
        System.assertEquals('Test custom field 2', controller.searchResultsWrapper.get(2).component.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(1).component.Name);
        System.assertEquals('Test Apex Trigger', controller.searchResultsWrapper.get(0).component.Name);
    }

    static testMethod void testToggleSort_Type() {
        createTestComponents();

        controller.sortField = 'Type__c';
        controller.sortDirection = 'desc';

        controller.toggleSort(); // results in ascending

        System.assertEquals('Object', controller.searchResultsWrapper.get(0).component.Type__c);
        System.assertEquals('Object Field', controller.searchResultsWrapper.get(1).component.Type__c);
        System.assertEquals('Object Field', controller.searchResultsWrapper.get(2).component.Type__c);
        System.assertEquals('Apex Trigger', controller.searchResultsWrapper.get(3).component.Type__c);

        controller.toggleSort(); // results in descending

        System.assertEquals('Object', controller.searchResultsWrapper.get(3).component.Type__c);
        System.assertEquals('Object Field', controller.searchResultsWrapper.get(2).component.Type__c);
        System.assertEquals('Object Field', controller.searchResultsWrapper.get(1).component.Type__c);
        System.assertEquals('Apex Trigger', controller.searchResultsWrapper.get(0).component.Type__c);
    }

    static testMethod void testToggleSort_ParentComponent() {
        createTestComponents();

        controller.sortField = 'Parent_Component__r.Name';
        controller.sortDirection = 'desc';

        controller.toggleSort(); // results in ascending

        System.assertEquals(null, controller.searchResultsWrapper.get(0).component.Parent_Component__r.Name);
        System.assertEquals(null, controller.searchResultsWrapper.get(1).component.Parent_Component__r.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(2).component.Parent_Component__r.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(3).component.Parent_Component__r.Name);

        controller.toggleSort(); // results in descending

        System.assertEquals(null, controller.searchResultsWrapper.get(0).component.Parent_Component__r.Name);
        System.assertEquals(null, controller.searchResultsWrapper.get(1).component.Parent_Component__r.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(2).component.Parent_Component__r.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(3).component.Parent_Component__r.Name);
    }

    static testMethod void testDoQuery() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        System.assertEquals(4, controller.recordCount);
        System.assertEquals(4, controller.searchResultsWrapper.size());
    }

    static testMethod void testDoSearch_Name() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        System.assertEquals(4, controller.recordCount);
        System.assertEquals(4, controller.searchResultsWrapper.size());

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('name', 'tr');
        ApexPages.currentPage().getParameters().put('type', '');
        ApexPages.currentPage().getParameters().put('parentName', '');
        ApexPages.currentPage().getParameters().put('includeDeleted', 'false');

        controller.doSearch();
        System.assertEquals(1, controller.recordCount);
        System.assertEquals(1, controller.searchResultsWrapper.size());
        System.assertEquals('Test Apex Trigger', controller.searchResultsWrapper.get(0).component.Name);
    }

    static testMethod void testDoSearch_Type() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        System.assertEquals(4, controller.recordCount);
        System.assertEquals(4, controller.searchResultsWrapper.size());

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('name', '');
        ApexPages.currentPage().getParameters().put('type', 'ob');
        ApexPages.currentPage().getParameters().put('parentName', '');
        ApexPages.currentPage().getParameters().put('includeDeleted', 'false');

        controller.doSearch();
        System.assertEquals(3, controller.recordCount);
        System.assertEquals(3, controller.searchResultsWrapper.size());
        System.assertEquals('Test custom field 1', controller.searchResultsWrapper.get(0).component.Name);
        System.assertEquals('Test custom field 2', controller.searchResultsWrapper.get(1).component.Name);
        System.assertEquals('Test object', controller.searchResultsWrapper.get(2).component.Name);
    }

    static testMethod void testDoSearch_ParentComponent() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        System.assertEquals(4, controller.recordCount);
        System.assertEquals(4, controller.searchResultsWrapper.size());

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('name', '');
        ApexPages.currentPage().getParameters().put('type', '');
        ApexPages.currentPage().getParameters().put('parentName', 's');
        ApexPages.currentPage().getParameters().put('includeDeleted', 'false');

        controller.doSearch();
        System.assertEquals(2, controller.recordCount);
        System.assertEquals(2, controller.searchResultsWrapper.size());
        System.assertEquals('Test custom field 1', controller.searchResultsWrapper.get(0).component.Name);
        System.assertEquals('Test custom field 2', controller.searchResultsWrapper.get(1).component.Name);
    }

    static testMethod void testDoSearch_AllFilters() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        System.assertEquals(4, controller.recordCount);
        System.assertEquals(4, controller.searchResultsWrapper.size());

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('name', '1');
        ApexPages.currentPage().getParameters().put('type', 'f');
        ApexPages.currentPage().getParameters().put('parentName', 't');
        ApexPages.currentPage().getParameters().put('includeDeleted', 'false');

        controller.doSearch();
        System.assertEquals(1, controller.recordCount);
        System.assertEquals(1, controller.searchResultsWrapper.size());
        System.assertEquals('Test custom field 1', controller.searchResultsWrapper.get(0).component.Name);
    }

    static testMethod void testUpdateSearchResultsCheckboxes() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('selectAll', 'true');
        controller.updateSearchResultsCheckboxes();

        for (ComponentSearchWrapper w : controller.searchResultsWrapper) {
            System.assert(w.checked == true);
        }

        ApexPages.currentPage().getParameters().put('selectAll', 'false');
        controller.updateSearchResultsCheckboxes();

        for (ComponentSearchWrapper w : controller.searchResultsWrapper) {
            System.assert(w.checked == false);
        }
    }
*/
    /*
    static testMethod void testUpdateSavedComponentsCheckboxes() {
        createTestComponents();

        controller.sortField = 'Name';
        controller.sortDirection = 'asc';

        controller.doQuery();

        PageReference p = Page.AssetEntry;
        Test.setCurrentPage(p);

        ApexPages.currentPage().getParameters().put('selectAll', 'true');
        controller.updateSavedComponentsCheckboxes();

        for (ComponentSearchWrapper w : controller.existingSavedMembers) {
            System.assert(w.checked == true);
        }

        ApexPages.currentPage().getParameters().put('selectAll', 'false');
        controller.updateSavedComponentsCheckboxes();

        for (ComponentSearchWrapper w : controller.existingSavedMembers) {
            System.assert(w.checked == false);
        }
    }
   */
}