mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Instance_Count__c.field-meta.xml
<CustomField>
    <fullName>Instance_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of instances that this component exists in.</description>
    <inlineHelpText>The number of instances that this component exists in.</inlineHelpText>
    <label>Instance Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/PmPostInstallHelper__c/PmPostInstallHelper__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Helper for the post install script that will enable/disable the validation rule on Component object</description>
    <label>BW ALM PM Post Install Helper</label>
</CustomObject>

mywork/force-app/main/default/objects/PmPostInstallHelper__c/fields/Enable_Rule__c.field-meta.xml
<CustomField>
    <fullName>Enable_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Rule</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/classes/TestUpdateExistingComponents.cls
@isTest
private class TestUpdateExistingComponents {

    static testMethod void testBatch() {
        // Assert initial custom setting value
        List<PmPostInstallHelper__c> cs = [Select Enable_Rule__c from PmPostInstallHelper__c];
        System.assertEquals(0, cs.size(), 'There should be 1 custom setting record');
        
        List<Component__c> componentList = new List<Component__c>();

        // Insert 200 component records to simulate one batch execution
        for (Integer i=0; i<200; i++) {
            Component__c c = new Component__c(Name='Foo'+i);
            c.Type__c = 'Application';
            componentList.add(c);
        }
        
        insert componentList;
        
        // Update the newly created components
        for (Component__c c : componentList) {
        	c.Instance_Count__c = 1;
        }
        
        update componentList;
        
        Integer startCount = [Select count() from Component__c Where Instance_Count__c = 1];
        System.assertEquals(200, startCount, 'Expected 200 records with an instance count of 1');
        
        // execute the batch
        Test.startTest();
            UpdateExistingComponents batch = new UpdateExistingComponents();
            ID batchProcessid = Database.executeBatch(batch);
        Test.stopTest();
        
        Integer endCount = [Select count() from Component__c Where Instance_Count__c = 1];
        System.assertEquals(0, endCount, 'There should be 0 records with an instance count of 1');
        
        Integer finalCount = [Select count() from Component__c Where Instance_Count__c = 0];
        System.assertEquals(200, finalCount, 'There should be 200 records with an instance count of 1');
        
        // Assert custom setting value
        List<PmPostInstallHelper__c> setting = [Select Enable_Rule__c from PmPostInstallHelper__c];
        System.assertEquals(1, setting.size(), 'There should be 1 custom setting record');
        System.assert(setting[0].Enable_Rule__c, 'Enable Rule should be true');
    }
}