mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Field_Modified_Data__c.field-meta.xml
<CustomField>
    <fullName>Field_Modified_Data__c</fullName>
    <label>Field Modified Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/classes/FieldModifiedData.cls
/**
 * This class represents the deserialized JSON of the Field_Modified_Data__c field on the Component__c object.
 */ 
public with sharing class FieldModifiedData {
    public String environmentName { get; set; }
    public Datetime lastModifiedDate { get; private set; }
    public String lastModifiedByName { get; private set; }
    public Datetime createdDate { get; private set; }
    public String createdByName { get; private set; }
    public Boolean deleted { get; private set; }
    
    public FieldModifiedData(String environmentName, Datetime lastModifiedDate, String lastModifiedByName, Datetime createdDate, String createdByName) {
    	this.environmentName = environmentName;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedByName = lastModifiedByName;
        this.createdDate = createdDate;
        this.createdByName = createdByName;
    }

    public FieldModifiedData(String environmentName, Datetime lastModifiedDate, String lastModifiedByName, Datetime createdDate, String createdByName, Boolean deleted) {
        this.environmentName = environmentName;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedByName = lastModifiedByName;
        this.createdDate = createdDate;
        this.createdByName = createdByName;
        this.deleted = deleted;
    }
    
    public FieldModifiedData(String environmentName) {
    	this.environmentName = environmentName;
    }

    public FieldModifiedData(String environmentName, Boolean deleted) {
        this.environmentName = environmentName;
        this.deleted = deleted;
    }
}