mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Backup_URL__c.field-meta.xml
<CustomField>
    <fullName>Backup_URL__c</fullName>
    <inlineHelpText>Link to download a backup version of the components from the target</inlineHelpText>
    <label>Backup URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Manual_Upload__c.field-meta.xml
<CustomField>
    <fullName>Manual_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the build was created by manually uploading a build package</description>
    <label>Manual Upload</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <inlineHelpText>Link to download the build package</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Source_Repository__c.field-meta.xml
<CustomField>
    <fullName>Source_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Builds (Target)</relationshipLabel>
    <relationshipName>Builds1</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <description>Represents an overall deployment of metadata components.</description>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest build for this deployment</description>
    <inlineHelpText>The latest build for this deployment</inlineHelpText>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Deployment_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Attempt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Attempt</label>
    <referenceTo>Deployment_Attempt__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments_Source</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Deployments (Target)</relationshipLabel>
    <relationshipName>Deployments_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Assemble_Request_Error__c.field-meta.xml
<CustomField>
    <fullName>Assemble_Request_Error__c</fullName>
    <label>Assemble Request Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Is_Quick_Deploy__c.field-meta.xml
<CustomField>
    <fullName>Is_Quick_Deploy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Quick Deploy</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Is_Validation__c.field-meta.xml
<CustomField>
    <fullName>Is_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Validation</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Errors__c</fullName>
    <label>Number Components Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Total__c</fullName>
    <label>Number Components Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Test_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Test_Errors__c</fullName>
    <label>Number Test Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Tests_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Tests_Total__c</fullName>
    <label>Number Tests Total</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/SF_Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Deployment_Id__c</fullName>
    <label>SF Deployment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Target_Instance__c.field-meta.xml
<CustomField>
    <fullName>Target_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Test_Level__c.field-meta.xml
<CustomField>
    <fullName>Test_Level__c</fullName>
    <label>Test Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NoTestRun</fullName>
            </value>
            <value>
                <fullName>RunSpecifiedTests</fullName>
            </value>
            <value>
                <fullName>RunLocalTests</fullName>
            </value>
            <value>
                <fullName>RunAllTestsInOrg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Total_Code_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Total_Code_Coverage__c</fullName>
    <label>Total Code Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Total_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines__c</fullName>
    <label>Total Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/DeploymentModel.cls
public with sharing class DeploymentModel {

    public static final String DEFAULT_TEST_LEVEL = 'Default';
    public static final String FAILED_BUILD_STATUS = 'Failed';
    public static final Integer QUICK_DEPLOY_MAX_AGE = 240;

    public Attempt deploymentAttempt;
    public Deployment__c record;

    public Boolean isValidation;
    public Boolean isDeploy;
    public Boolean isSuccess;
    public Boolean isInProgress;
    public Boolean isManualUpload;
    public Boolean isQuickDeployEligible;
    public String sourceInstanceName;
    public String targetInstanceName;
    public String lastModifiedDate;
    public Integer totalBuildErrors;
    public String buildStatus;
    public Integer codeCoverage;
    public String buildPackageUrl;
    public String backupPackageUrl;
    @TestVisible
    private Integer codeCoverageErrorCount;

    public DeploymentModel(Deployment__c deployment, Deployment_Attempt__c deploymentAttempt) {
        this(deployment, deploymentAttempt, 0);
    }

    public DeploymentModel(Deployment__c deployment, Deployment_Attempt__c deploymentAttempt, Integer codeCoverageErrorCount) {
        this.record = deployment;
        Datetime deploymentEndDate;
        this.codeCoverageErrorCount = codeCoverageErrorCount;
        if (deploymentAttempt == null) {
            this.isValidation = false;
            this.isDeploy = false;
            this.isSuccess = false;
            this.isInProgress = false;
        } else {
            this.deploymentAttempt = new Attempt(deploymentAttempt, codeCoverageErrorCount);
            this.isValidation = deploymentAttempt.Is_Validation__c;
            this.isDeploy = !deploymentAttempt.Is_Validation__c;
            this.isSuccess = deploymentAttempt.Status__c == DeploymentServices.STATUS_SUCCESS ? true : false;
            this.isInProgress = (this.deploymentAttempt.inProgress || this.deploymentAttempt.isPending || this.deploymentAttempt.isNotStarted);
            this.codeCoverage = (deploymentAttempt.Total_Code_Coverage__c == null) ? null : deploymentAttempt.Total_Code_Coverage__c.intValue();
            deploymentEndDate = deploymentAttempt.End_Date__c;
        }

        buildPackageUrl = deployment.Build__r.Package_URL__c;
        backupPackageUrl = deployment.Build__r.Backup_URL__c;
        lastModifiedDate = deployment.LastModifiedDate.format();
        this.isManualUpload = (deployment.Build__c == null) ? false : deployment.Build__r.Manual_Upload__c;

        setSourceInstanceName();
        this.targetInstanceName = (deployment.Target__c == null ? '' : deployment.Target__r.Name);
        this.buildStatus = deployment.Build__r.Status__c;
        setIsQuickDeployEligible(deploymentEndDate);
    }

    public DeploymentModel(Deployment__c deployment, Deployment_Attempt__c deploymentAttempt, Integer codeCoverageErrorCount, Integer numErrors) {
        this(deployment, deploymentAttempt, codeCoverageErrorCount);
        this.totalBuildErrors = (numErrors == null ? 0 : numErrors);
        this.isSuccess = getIsSuccess();
    }

    private void setSourceInstanceName() {
        if (record.Source__c != null) {
            this.sourceInstanceName = record.Source__r.Name;
        } else if (record.Build__r.Source_Repository__c != null) {
            this.sourceInstanceName = record.Build__r.Source_Repository__r.Name;
        } else {
            this.sourceInstanceName = '';
        }
    }

    private void setIsQuickDeployEligible(Datetime endDate) {
        if (isSuccess && isValidation
             && codeCoverage != null && codeCoverage >= 75
             && !deploymentAttempt.hasComponentErrors
             && !deploymentAttempt.hasTestErrors
             && deploymentAttempt.hasRanTests
             && endDate >= Datetime.now().addHours(-QUICK_DEPLOY_MAX_AGE)
             && codeCoverageErrorCount == 0 
             ) {
            isQuickDeployEligible = true;
        } else {
            isQuickDeployEligible = false;
        }
    }

    private Boolean getIsSuccess() {
        if (this.totalBuildErrors > 0 || FAILED_BUILD_STATUS.equalsIgnoreCase(this.buildStatus)) {
            return false;
        } else if(this.deploymentAttempt != null &&
                (this.deploymentAttempt.hasComponentErrors ||
                this.deploymentAttempt.hasTestErrors ||
                this.deploymentAttempt.hasCodeCoverageErrors))
        {
            return false;
        }

        return true;
    }

    public class Attempt {
        public final String NOT_APPLICABLE = 'N/A';
        public final String NOT_RAN = 'NOT RAN';
        public final String RESULT_PASS = 'pass';
        public final String RESULT_FAIL = 'fail';
        public final String RESULT_CANCELED = 'canceled';

        public Deployment_Attempt__c record {get; set;}
        public String deploymentType {get; set;}
        public String endTime {get; set;}
        public String sfDeploymentId {get; set;}
        public String startTime {get; set;}
        public String status {get; set;}
        public String targetInstance {get; set;}
        public String lastModifiedDate {get; set;}
        public Boolean isPending {get; set;}
        public Boolean inProgress {get; set;}
        public Boolean isNotStarted {get; private set;}
        public Boolean isQuickDeploy {get; private set;}
        public Boolean hasComponentErrors {get; set;}
        public Boolean hasTestErrors {get; set;}
        public Boolean hasRanTests {get; set;}
        public Boolean hasCodeCoverageErrors {get; set;}

        public String deploymentStatus {
            get {
                if(record.Status__c == 'Succeeded') {
                    return 'Successful';
                } else if(record.Status__c == 'Pending') {
                    return 'Pending';
                } else if(record.Status__c == 'Failed') {
                    return 'Failed';
                } else if(record.Status__c == 'InProgress') {
                    return 'In Progress';
                } else if(record.Status__c == 'Canceled') {
                    return 'Canceled';
                } else {
                    return 'Unknown';
                }
            }
        }
        public String codeCoverage {get; set;}
        public String apexTestsTotal { get; set; }
        public Decimal numberComponentsErrors { get; set; }
        public Decimal numberTestsErrors { get; set; }
        public Decimal totalLines { get; set; }
        public Decimal numberComponentsTotal { get; set; }
        public String componentResult {get; set;}
        public String apexResult {get; set;}
        public String assembleRequestError { get; set; }

        public Attempt(Deployment_Attempt__c deployment) {
            this(deployment, 0);
        }

        public Attempt(Deployment_Attempt__c deployment, Integer codeCoverageErrorCount) {
            this.record = deployment;
            if (record.Start_Date__c != null) {
                this.startTime = record.Start_Date__c.format();
            }
            if (record.End_Date__c != null) {
                this.endTime = record.End_Date__c.format();
            }
            if (record.Status__c != null) {
                status = record.Status__c.replaceAll(' ','').toLowerCase();
            }

            if (record.Status__c == DeploymentServices.STATUS_FAILED ||
                  record.Status__c == DeploymentServices.STATUS_SUCCESS ||
                    record.Status__c == DeploymentServices.STATUS_CANCELED) {
                hasCodeCoverageErrors = (codeCoverageErrorCount > 0);
            } else {
                hasCodeCoverageErrors = false;
            }
            setQuickDeployResults();

            lastModifiedDate = record.LastModifiedDate.format();
            sfDeploymentId = record.SF_Deployment_Id__c;
            targetInstance = record.Target_Instance__r.Name;
            deploymentType = (deployment.Is_Validation__c) ? 'validation' : 'deployment';
            isPending = (String.isBlank(record.Status__c) || record.Status__c == DeploymentServices.STATUS_PENDING);
            inProgress = (isPending || record.Status__c == DeploymentServices.STATUS_IN_PROGRESS || record.Status__c == 'In Progress');
            isNotStarted = (record.Status__c == DeploymentServices.STATUS_NOT_STARTED);
            numberComponentsTotal = record.Number_Components_Total__c != null ? record.Number_Components_Total__c : 0;
            numberTestsErrors = record.Number_Test_Errors__c != null ? record.Number_Test_Errors__c : 0;
            hasTestErrors = (numberTestsErrors > 0);
            numberComponentsErrors = record.Number_Components_Errors__c != null ? record.Number_Components_Errors__c : 0;
            hasComponentErrors = (numberComponentsErrors > 0) || (record.Status__c == DeploymentServices.STATUS_FAILED && !hasTestErrors && !hasCodeCoverageErrors);
            totalLines = record.Total_Lines__c != null ? record.Total_Lines__c : 0;

            hasRanTests = totalLines > 0;

            if (hasRanTests) {
                codeCoverage = record.Total_Code_Coverage__c + '';
            } else {
                codeCoverage = NOT_APPLICABLE;
            }
            apexTestsTotal = record.Number_Tests_Total__c == null ? '0' : record.Number_Tests_Total__c + '';

            if (status == RESULT_CANCELED) {
                if (Integer.valueOf(apexTestsTotal) == 0) {
                    componentResult = RESULT_CANCELED;

                    // Set apex result to in-progress to display the gray vertial bar image
                    apexResult = 'in-progress';
                } else {
                    componentResult = (hasComponentErrors) ? RESULT_FAIL : RESULT_PASS;
                    apexResult = RESULT_CANCELED;
                }
            } else {
                componentResult = (hasComponentErrors) ? RESULT_FAIL : RESULT_PASS;
                apexResult = (hasTestErrors) ? RESULT_FAIL : RESULT_PASS;
            }

            assembleRequestError = deployment.Assemble_Request_Error__c;
            if (!String.isBlank(assembleRequestError)) {
                componentResult = NOT_APPLICABLE;
                apexTestsTotal = NOT_APPLICABLE;
                codeCoverage = NOT_APPLICABLE;
            }
        }

        private void setQuickDeployResults() {
            isQuickDeploy = record.Is_Quick_Deploy__c;
            if (isQuickDeploy) {
                 Deployment_Attempt__c quickDeployAttempt =
                     DeploymentServices.getQuickDeployValidationAttempt(record.Deployment__c);

                 if (quickDeployAttempt != null) {
                     record.Number_Tests_Total__c = quickDeployAttempt.Number_Tests_Total__c;
                     record.Total_Lines__c = quickDeployAttempt.Total_Lines__c;
                     record.Total_Code_Coverage__c = quickDeployAttempt.Total_Code_Coverage__c;
                     record.Test_Level__c = quickDeployAttempt.Test_Level__c;
                 }
            }
        }
    }

}