mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Assemble_Request_Error__c.field-meta.xml
<CustomField>
    <fullName>Assemble_Request_Error__c</fullName>
    <label>Assemble Request Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/BuildModel.cls
public class BuildModel {

    public Build__c record;
    public String buildStatus;
    public String webAssemblerFailureMessage;
    public String buildStage;
    public Integer componentsRetrieved;
    public Integer componentsTotal;

    public BuildModel(Build__c build){
        this.record = build;
        if (build != null){
            this.buildStatus = build.Status__c;
            if (!build.Deployment_Attempts__r.isEmpty()){
                this.webAssemblerFailureMessage = build.Deployment_Attempts__r[0].Assemble_Request_Error__c;
            }
        }
    }

    public BuildModel (Build__c build, AssemblerServices.BuildStatus buildStatus) {
        this(build);
        if (build != null && buildStatus != null) {
            this.buildStatus = buildStatus.status;
            if (String.isNotBlank(buildStatus.failureReason)) {
                webAssemblerFailureMessage = buildStatus.failureReason;
            }
            this.buildStage = buildStatus.buildStage;
            this.componentsRetrieved = buildStatus.componentsRetrieved;
            this.componentsTotal = buildStatus.componentsTotal;
        }
    }

    /**
    * Saves the Build__c and related Deployent_Attempt__c if there are unsaved changes
    * @throws DMLExeption
    */
    public void save() {

        System.savepoint sp = Database.setSavepoint();

        if (record.Status__c != buildStatus) {
            record.Status__c = buildStatus;
            update record;
        }

        if (!record.Deployment_Attempts__r.isEmpty()) {
            Deployment_Attempt__c attempt = record.Deployment_Attempts__r[0];

            if (attempt.Assemble_Request_Error__c != webAssemblerFailureMessage) {
                attempt.Assemble_Request_Error__c = webAssemblerFailureMessage;

                try {
                    update attempt;
                } catch (DMLException de) {
                    Database.rollback(sp);
                    throw de;
                }
            }
        }
    }
}