mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <description>Represents an overall deployment of metadata components.</description>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest build for this deployment</description>
    <inlineHelpText>The latest build for this deployment</inlineHelpText>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Completed_Build__c.field-meta.xml
<CustomField>
    <fullName>Completed_Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Completed Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>Deployments (Completed Build)</relationshipLabel>
    <relationshipName>Deployments1</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/TestBuildTrigger.cls
@isTest
private class TestBuildTrigger {

    static testMethod void updateDeploymentWithCompletedBuild() {
        Release__c release = new Release__c(Name='Test release');
        insert release;

        Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_IN_PROGRESS);

        Deployment__c deployment = new Deployment__c(Name='Background Build');
        deployment.Build__c = build.Id;
        insert deployment;

        Test.startTest();

            build.Status__c = BuildServices.STATUS_SUCCESS;
            update build;

        Test.stopTest();

        Deployment__c updatedDeployment = [SELECT Id, Completed_Build__c FROM Deployment__c];

        System.assertEquals(build.Id, updatedDeployment.Completed_Build__c, 'The deployment should be updated with the completed build');
    }
}