mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <label>Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Last_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Time__c</fullName>
    <label>Last Run Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Last_Successful_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Run__c</fullName>
    <label>Last Successful Run</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Report_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Developer_Name__c</fullName>
    <label>Report Developer Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Target_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Api_Name__c</fullName>
    <description>Holds the api name of the target object into which snapshots will be stored</description>
    <label>Target Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>Snapshot</fullName>
            </value>
            <value>
                <fullName>Repo_Sync</fullName>
                <label>Repo Sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/Snapshot_Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Snapshot Field Mapping</label>
    <nameField>
        <displayFormat>SNAPMAP-{0000}</displayFormat>
        <label>Snapshot Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ALM_Job__c.Tool__c</field>
            <operation>equals</operation>
            <value>Snapshot</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>Snapshot Field Mappings</relationshipLabel>
    <relationshipName>Snapshot_Field_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/Report_Column__c.field-meta.xml
<CustomField>
    <fullName>Report_Column__c</fullName>
    <description>The api name of the field in the source report.</description>
    <label>Report Column</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/Target_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Api_Name__c</fullName>
    <description>The target field or fields in which the matching source field data should be stored, when using multiple targets, please separate via commas.</description>
    <label>Target Field Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/SnapshotReportExecution.cls
public with sharing class SnapshotReportExecution implements Reports.NotificationAction{

    public void execute(Reports.NotificationActionContext context) {
        Reports.ReportResults results = context.getReportInstance().getReportResults();

        //Find the alm job based on the report Id, this will allow us to determine
        //the mapping into the target object.
        //if there is no mapping, then we will not proceed.
        List<ALM_Job__c> snapshots = [
            SELECT
                Id, Target_Object_Api_Name__c, Errors__c,
                (SELECT Id, ALM_Job__c, Report_Column__c, Target_Field_Api_Name__c FROM Snapshot_Field_Mappings__r)
            FROM ALM_Job__c
            WHERE Tool__c = :ALMJobServices.getToolName(ALMJobServices.ToolType.SNAPSHOT)
            AND Report_Developer_Name__c = :results.getReportMetadata().getDeveloperName()
            LIMIT 1
        ];

        if (snapshots.isEmpty()
        || snapshots[0].Snapshot_Field_Mappings__r == null
        || snapshots[0].Snapshot_Field_Mappings__r.isEmpty()) {
            return;
        }

        ALM_Job__c snapshot = snapshots[0];
        String errors = '';

        try{
            List<Map<String, String>> reportFlattenedData = SnapshotServices.organizeReportResults(results);

            List<SObject> targetObjectsToInsert = SnapshotServices.mapReportResultsIntoTargetObject(reportFlattenedData, snapshot);

            errors = SnapshotServices.insertRecords(targetObjectsToInsert);
        }catch(Exception ex){
            errors = 'Error occurred at : ' + SnapshotServices.nowTime.format()
                                            + SnapshotServices.ERROR_LINE_SEPARATOR
                                            + ex.getMessage();
        }

        if (String.IsNotBlank(errors)) {
            snapshot.Errors__c = errors.abbreviate(ALM_Job__c.Errors__c.getDescribe().getLength());
        } else{
            snapshot.Last_Successful_Run__c = SnapshotServices.nowTime;
            snapshot.Errors__c = '';
        }
        snapshot.Last_Run_Time__c = SnapshotServices.nowTime;

        try {
            update snapshot;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}