mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Report_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Developer_Name__c</fullName>
    <label>Report Developer Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Target_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Api_Name__c</fullName>
    <description>Holds the api name of the target object into which snapshots will be stored</description>
    <label>Target Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>Snapshot</fullName>
            </value>
            <value>
                <fullName>Repo_Sync</fullName>
                <label>Repo Sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Burndown_Snapshot__c/Burndown_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Holds historical information of backlog items in a sprint to be used in a burndown report and chart.</description>
    <label>Burndown Snapshot</label>
    <nameField>
        <displayFormat>BNSS-{0000}</displayFormat>
        <label>BNSS-Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Burndown Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Burndown_Snapshot__c/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Burndown_Snapshot__c/fields/Item_Key__c.field-meta.xml
<CustomField>
    <fullName>Item_Key__c</fullName>
    <label>Item Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/Snapshot_Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Snapshot Field Mapping</label>
    <nameField>
        <displayFormat>SNAPMAP-{0000}</displayFormat>
        <label>Snapshot Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ALM_Job__c.Tool__c</field>
            <operation>equals</operation>
            <value>Snapshot</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>Snapshot Field Mappings</relationshipLabel>
    <relationshipName>Snapshot_Field_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/Report_Column__c.field-meta.xml
<CustomField>
    <fullName>Report_Column__c</fullName>
    <description>The api name of the field in the source report.</description>
    <label>Report Column</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Snapshot_Field_Mapping__c/fields/Target_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Api_Name__c</fullName>
    <description>The target field or fields in which the matching source field data should be stored, when using multiple targets, please separate via commas.</description>
    <label>Target Field Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/SnapshotInstallServices.cls
public with sharing class SnapshotInstallServices {
    @TestVisible
    public static String SNAPSHOT_REPORT_DEVELOPER_NAME = 'Sprint_Snapshot';
    @TestVisible
    public static String SNAPSHOT_TARGET_OBJECT_NAME = SObjectServices.getFullyQualifiedName('Burndown_Snapshot__c');

    @TestVisible
    private static Map<String, String> COLUMN_NAME_TO_FIELD_NAME = new Map<String,String>{
        'Backlog Item: Key' => SObjectServices.getFullyQualifiedName('Item_Key__c'),
        'Backlog Item: Status' => SObjectServices.getFullyQualifiedName('Status__c'),
        'Backlog Item: Dev Effort' => SObjectServices.getFullyQualifiedName('Effort__c')
    };

    @TestVisible
    private static list<String> errors = new List<String>();

    public static void createAlmJobSnapshotAndMappings() {
        ALM_Job__c snapshotJob = new ALM_Job__c(Tool__c = ALMJobServices.getToolName(ALMJobServices.ToolType.SNAPSHOT),
                                                Report_Developer_Name__c = SNAPSHOT_REPORT_DEVELOPER_NAME,
                                                Target_Object_Api_Name__c = SNAPSHOT_TARGET_OBJECT_NAME);

        try {
            insert snapshotJob;
        } catch (DMLException dex) {
            errors.add(dex.getMessage());
        }
        if (errors.isEmpty()) {
            List<Snapshot_Field_Mapping__c> mappingsToInsert = new List<Snapshot_Field_Mapping__c>();

            for (String column : COLUMN_NAME_TO_FIELD_NAME.keySet()) {
                String field = COLUMN_NAME_TO_FIELD_NAME.get(column);

                Snapshot_Field_Mapping__c mapping = new Snapshot_Field_Mapping__c(ALM_Job__c = snapshotJob.Id,
                                                                          Report_Column__c = column,
                                                                          Target_Field_Api_Name__c = field);
                mappingsToInsert.add(mapping);
            }

            try {
                insert mappingsToInsert;
            } catch (DMLException dex) {
                errors.add(dex.getMessage());
            }
        }
        if (!errors.isEmpty()) {
            String body = String.join(errors, '\n');

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] mailTo = new String[] {'productdev@bluewolfgroup.com'};
            mail.setToAddresses(mailTo);
            mail.setSubject('Errors occurred during the snapshot post install process');
            mail.setPlainTextBody(body);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        }
    }
}