mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Deploy_Manually__c.field-meta.xml
<CustomField>
    <fullName>Deploy_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set to true if this component should be deployed manually</inlineHelpText>
    <label>Deploy Manually</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Source_Sandbox__c</fullName>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Sandbox</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Field_Modified_Data__c.field-meta.xml
<CustomField>
    <fullName>Field_Modified_Data__c</fullName>
    <label>Field Modified Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Child Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/UnsupportedMetadataTypes__c/UnsupportedMetadataTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A list of metadata types that is not supported by the Metadata API.  These types muse be deployed manually.

http://www.salesforce.com/us/developer/docs/api_meta/Content/meta_unsupported_types.htm</description>
    <label>Unsupported Metadata Types</label>
</CustomObject>

mywork/force-app/main/default/classes/ComponentSearchWrapper.cls
global virtual with sharing class ComponentSearchWrapper implements Comparable{
    @AuraEnabled
    public Boolean checked {get; set;}
    @AuraEnabled
    public Backlog_Component__c backlogComponent {get; set;}
    @AuraEnabled
    public Component__c component {get; set;}
    @AuraEnabled
    public String environment {get; set;}
    @AuraEnabled
    public String notes {get; set;}
    @AuraEnabled
    public Boolean isUnsupportedType {get; set;}
    @AuraEnabled
    public Datetime lastModifiedDate {get; set;}
    @AuraEnabled
    public String lastModifiedBy {get; set;}
    @AuraEnabled
    public Boolean existsOnCurrentBacklog {get; set;}
    @AuraEnabled
    public Boolean isDeleted {get; set;}

    @AuraEnabled
    public String componentType {get; set;}
    @AuraEnabled
    public Id parentComponentId {get; set;}
    @AuraEnabled
    public String parentComponentName {get; set;}
    @AuraEnabled
    public Boolean deployManually {get; set;}
    
    @AuraEnabled
    public String componentReferences {get; set;}

    // Holds the key calculated for uniqueness (used in front end)

    public String key;
    @AuraEnabled
    public String componentName {get; set;}

    public static Set<String> unsupportedTypesList {
        get {
            if (unsupportedTypesList == null) {
                unsupportedTypesList = new Set<String>();

                List<UnsupportedMetadataTypes__c> customSetting = UnsupportedMetadataTypes__c.getAll().values();
                for (UnsupportedMetadataTypes__c record : customSetting) {
                    unsupportedTypesList.add(record.Name__c);
                }
            }

            return unsupportedTypesList;
        }
    }

    public static Boolean sortDescending
    {
        get
        {
            if(sortDescending == null)
                sortDescending = true;
            return sortDescending;
        }
        set;
    }

    public ComponentSearchWrapper(){}

    public ComponentSearchWrapper(Component__c comp,
                                     String parentName,
                                     String instance,
                                     DateTime lastModifiedDate,
                                     String lastModifiedBy) {
        this.component = comp;
        this.componentName = comp.Name;
        this.componentType = comp.Type__c;
        this.parentComponentName = parentName;
        this.environment = instance;
        this.key = getKey();
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
    }

    public ComponentSearchWrapper(Component__c component,
                                  String environment,
                                  String notes,
                                  Datetime lastModifiedDate,
                                  String lastModifiedBy,
                                  Boolean isDeleted) {

        this(component, lastModifiedDate, lastModifiedBy);
        this.environment = environment;
        this.notes = notes;
        this.key = getKey();
        this.isDeleted = isDeleted != null ? isDeleted : false;
    }

    public ComponentSearchWrapper(Component__c component, FieldModifiedData fmd) {
        // Empty string is for notes. When creating from FieldModifiedData, notes will be empty.
        this(component, fmd.environmentName, '',  fmd.lastModifiedDate, fmd.lastModifiedByName, fmd.deleted);
    }

    public ComponentSearchWrapper(Component__c component,
                             Backlog_Component__c backlogComponent,
                             Datetime lastModifiedDate,
                             String lastModifiedBy,
                             Boolean isDeleted) {

        this(component, lastModifiedDate, lastModifiedBy);
        this.backlogComponent = backlogComponent;
        this.environment = backlogComponent.Source_Sandbox__c;
        this.notes = backlogComponent.Notes__c;
        this.deployManually = backlogComponent.Deploy_Manually__c;
        this.backlogComponent.Component__r = null;
        this.isDeleted = isDeleted != null ? isDeleted : false;
    }

    public ComponentSearchWrapper(Component__c component,
                             Backlog_Component__c backlogComponent,
                             Datetime lastModifiedDate,
                             String lastModifiedBy,
                             Boolean isDeleted,
                             String componentReferences) {

        this(component, backlogComponent, lastModifiedDate, lastModifiedBy, isDeleted);
        this.componentReferences = componentReferences;
    }
    
    @TestVisible
    private ComponentSearchWrapper(Component__c component,
                             Datetime lastModifiedDate,
                             String lastModifiedBy) {

        Component__c comp = component.clone(true, true, true, true);
        comp.Field_Modified_Data__c = null;
        this.component = comp;
        this.isUnsupportedType = unsupportedTypesList.contains(comp.Type__c);
        this.deployManually = this.isUnsupportedType;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.existsOnCurrentBacklog = false;
        this.checked = false;
        this.componentName = ComponentServices.getComponentName(comp);

        this.componentType = comp.Type__c;
        this.parentComponentName = ComponentServices.getComponentName(component.Parent_Component__r);
        this.parentComponentId = component.Parent_Component__r.Id;
    }

    @AuraEnabled
    public String getKey() {
        String environment = (environment == null) ? '' : environment;
        return environment + '|' + String.valueOf( component.Id );
    }

    public static ComponentSearchWrapper addWrapper(List<ComponentSearchWrapper> wrapperList,
                                  Component__c component,
                                  String environment,
                                  String notes,
                                  Datetime lastModifiedDate,
                                  String lastModifiedBy,
                                  Boolean isDeleted) {

        ComponentSearchWrapper wrapper = new ComponentSearchWrapper(component, environment, notes, lastModifiedDate, lastModifiedBy, isDeleted);
        wrapperList.add(wrapper);
        return wrapper;
    }

    public static ComponentSearchWrapper addWrapper(List<ComponentSearchWrapper> wrapperList,
                                  Backlog_Component__c backlogComponent,
                                  Component__c component,
                                  String environment,
                                  Datetime lastModifiedDate,
                                  String lastModifiedBy,
                                  Boolean isDeleted) {

        backlogComponent.Source_Sandbox__c = environment;
        // parse ref data 
        String referencesJSONString = getReferencesStringJSON(component);
        
        String componentReferences = '';
        if (String.isNotBlank(referencesJSONString)) {
            List<ComponentReference> cr = (List<ComponentReference>) JSON.deserialize(referencesJSONString, List<ComponentReference>.class);
            Set<String> ids = new Set<String>();
            for (ComponentReference compRef : cr) {
                if (compRef.instance.equalsIgnoreCase(environment)) {
                    componentReferences = compRef.references;
                    break;
                }
            }
        }
        
        ComponentSearchWrapper wrapper = new ComponentSearchWrapper(component, backlogComponent, 
            lastModifiedDate, lastModifiedBy, isDeleted, componentReferences);
        wrapperList.add(wrapper);
        return wrapper;
    }

    /**
     * Custom sorter to sort by Last Modified Date in descending order
     */
    global Integer compareTo(Object compareTo) {
        ComponentSearchWrapper compareToWrapper = (ComponentSearchWrapper) compareTo;
        if (lastModifiedDate == compareToWrapper.lastModifiedDate) {
            return 0;
        }
        else if (lastModifiedDate == null
            || (lastModifiedDate < compareToWrapper.lastModifiedDate)) {
            return (sortDescending) ? 1 : -1;
        }
        else {
            return (sortDescending) ? -1 : 1;
        }
    }

    public override String toString() {
        return '[' +environment + ':' + ComponentServices.getComponentName(component) + ':' + component.Type__c + ':' +  component.Parent_Component__c + ']';
    }
    
    @TestVisible
    private static String getReferencesStringJSON(Component__c c) {
        String json = '';
        
        Integer maxNumberOfFields = 5;
        
        for (Integer i=1; i<=maxNumberOfFields; i++) {
            String fieldValue = (String) c.get('Reference_Data_' + i + '__c');
            if (String.isNotBlank(fieldValue)) {
                json += fieldValue;
            }
        }
        
        return json;
    }
    
    public class ComponentReference {
        public String instance;
        public String references;
    
        public ComponentReference() {}
    
        public ComponentReference(String instance, String references) {
            this.instance = instance;
            this.references = references;
        }
    }

}