mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/Build_Component__c.object-meta.xml
<CustomObject>
    <label>Build Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Build Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build_Component__c/fields/Backlog_Component__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Component</label>
    <referenceTo>Backlog_Component__c</referenceTo>
    <relationshipLabel>Build Componnets</relationshipLabel>
    <relationshipName>Build_Componnets</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Build Components</relationshipLabel>
    <relationshipName>Build_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/ProfilePermissions.cls
public with sharing class ProfilePermissions {

    public static final Integer MAX_TEXT_AREA_DATA_LENGTH = 131072;
    public static final Integer DATA_FIELD_COUNT = 2;

    public String name;
    public List<Section> sections;
    public List<String> instances;

    public ProfilePermissions() {
        this.sections = new List<Section>();
        this.instances = new List<String>();
    }

    public ProfilePermissions(Map<String, Set<String>> sectionToPermissions) {
        this.sections = new List<Section>();

        for (String sectionName : sectionToPermissions.keySet()) {
            Section section = new Section();
            section.apiName = sectionName;
            section.permissions =  new List<String>( sectionToPermissions.get(sectionName) );
            sections.add(section);
        }
    }

    public class Section {
        public String apiName;
        public List<String> permissions;
    }

    /**
    * Replaces the object selections in the FLS Section with the documented fields for that object
    * @param objectToDocumentedFields   Map of object name => Set of documented fields on that object
    */
    public void expandFLS(Map<String, Set<String>> objectToDocumentedFields) {
        for (Section section : sections) {
            if (section.apiName == ProfileServices.FIELD_API_NAME) {
                Set<String> fieldPermissions = new Set<String>();
                for (String objectName : section.permissions) {
                    if (objectToDocumentedFields.containsKey(objectName)) {
                        fieldPermissions.addAll( objectToDocumentedFields.get(objectName) );
                    }
                }
                section.permissions = new List<String>(fieldPermissions);
                break;
            }
        }
    }

    public static ProfilePermissions mergePermissions(List<ProfilePermissions> permissions) {
        ProfilePermissions mergedPermissions = new ProfilePermissions();

        Set<String> allInstances = new Set<String>();
        Map<String, Section> sectionMap = new Map<String, Section>();

        for (ProfilePermissions permission : permissions) {
            allInstances.addAll(permission.instances);
            mergedPermissions.name = permission.name;

            for(Section section : permission.sections) {
                if (sectionMap.containsKey(section.apiName)) {
                    Section mergedSection = sectionMap.get(section.apiName);
                    Set<String> sectionPermissions = new Set<String>(mergedSection.permissions);
                    for (String sectionPermission : section.permissions) {
                        if (sectionPermission != null && !sectionPermissions.contains(sectionPermission)) {
                            mergedSection.permissions.add(sectionPermission);
                        }
                    }
                } else {
                    Set<String> sectionPermissions = new Set<String>(section.permissions);
                    sectionPermissions.remove(null);
                    section.permissions = new List<String>(sectionPermissions);
                    sectionMap.put(section.apiName, section);
                }
            }
        }

        mergedPermissions.instances = new List<String>(allInstances);
        mergedPermissions.sections = sectionMap.values();

        return mergedPermissions;
    }
    
    public void selectPermissions(Map<String, Set<String>> sectionToPermissions) {
        Map<String, Section> sectionMap = getSectionMap();
        
        for (String sectionName : sectionToPermissions.keySet()){
            if (sectionMap.containsKey(sectionName)){
                Section sectionRecord = sectionMap.get(sectionName);
                Set<String> sectionPermissions = new Set<String>(sectionRecord.permissions);
                sectionPermissions.addAll(sectionToPermissions.get(sectionRecord.apiName));
                sectionRecord.permissions = new List<String>(sectionPermissions);
            } else {
                Section sectionRecord = new Section();
                sectionRecord.apiName = sectionName;
                sectionRecord.permissions = new List<String>(sectionToPermissions.get(sectionName));
                this.sections.add(sectionRecord);
            }
        }
    }

    public void removePermissions(Map<String, Set<String>> sectionToPermissions) {
        Map<String, Section> sectionMap = getSectionMap();

        for (String sectionName : sectionToPermissions.keySet()) {
            if (sectionMap.containsKey(sectionName)) {
                Section sectionRecord = sectionMap.get(sectionName);
                Set<String> sectionPermissions = new Set<String>(sectionRecord.permissions);
                sectionPermissions.removeAll(sectionToPermissions.get(sectionRecord.apiName));
                sectionRecord.permissions = new List<String>(sectionPermissions);
            }
        }
    }

    public Map<String, Section> getSectionMap() {
        Map<String, Section> sectionMap = new Map<String, Section>();

        for (Section section : this.sections) {
            sectionMap.put(section.apiName, section);
        }

        return sectionMap;
    }

    /**
    * Gets the profile json stored on a record
    * @param   record   Either a Backlog_Component__c or Build_Component__c
    * @return  String   The serialized ProfilePermissions
    */
    public static String getProfilePermissionsString(SObject record) {
        String permissionsString = '';
        for (Integer i = 1; i <= DATA_FIELD_COUNT; i++) {
            String fieldName = SObjectServices.getFullyQualifiedName('Profile_Data_' + i + '__c');
            String value = (String)record.get(fieldName);
            if (value != null) {
                permissionsString += value;
            }
        }

        return permissionsString;
    }

    /**
    * Populates the profile json fields on the passed in record with Profile_Data_i__c fields
    */
    public static void setProfilePermissionsData(SObject record, String permissionData) {
        //clear all profile data
        for (Integer i = 1; i <= DATA_FIELD_COUNT; i++) {
            String fieldName = SObjectServices.getFullyQualifiedName('Profile_Data_' + i + '__c');
            record.put(fieldName, '');
        }

        List<String> permissionDataChunks
            = String.isEmpty(permissionData) ? new List<String>() : State.splitByLength(permissionData, MAX_TEXT_AREA_DATA_LENGTH);

        if (permissionDataChunks.size() > DATA_FIELD_COUNT) {
            throw new ALMException('Profile data could not be stored. Data value to long: ' + String.valueOf(permissionData.length()) );
        }

        for (Integer i = 0; i < permissionDataChunks.size(); i++) {
            String fieldName = SObjectServices.getFullyQualifiedName('Profile_Data_' + (i + 1) + '__c');
            record.put(fieldName, permissionDataChunks[i]);
        }
    }

    public static ProfilePermissions valueOf(Backlog_Component__c backlogComponent) {
        String permissionsJSON = getProfilePermissionsString(backlogComponent);
        ProfilePermissions profile = valueOf(permissionsJSON);
        if (backlogComponent.Source_Instance__r != null) {
            profile.instances = new List<String> { backlogComponent.Source_Instance__r.Name };
        }

        if (String.isBlank(profile.name) && backlogComponent.Component__r != null) {
            profile.name = ComponentServices.getComponentName(backlogComponent.Component__r);
        }

        return profile;
    }

    public static ProfilePermissions valueOf(Build_Component__c buildComponent) {
        String permissionsJSON = getProfilePermissionsString(buildComponent);
        ProfilePermissions profile = valueOf(permissionsJSON);
        if (String.isBlank(profile.name)) {
            profile.name = buildComponent.Component_Name__c;
        }

        return profile;
    }

    public static ProfilePermissions valueOf(String permissionsJSON) {
        if (String.isBlank(permissionsJSON)) {
            return new ProfilePermissions();
        }

        try {
            return (ProfilePermissions)JSON.deserialize(permissionsJSON, ProfilePermissions.class);
        } catch(JSONException je) {
            throw new ALMException(je.getMessage());
        }
    }
}