mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/AssemblerOrgSourceRequest.cls
public virtual with sharing class AssemblerOrgSourceRequest extends AssemblerRequest {
    public String sourceRefreshToken;
    public String sourceEndpoint;

    public AssemblerOrgSourceRequest(Build__c build, Auth_User__c sourceOAuth, Auth_User__c targetOAuth,
        Boolean skipTargetBackup) {

        super(build, targetOAuth, skipTargetBackup);

        if (sourceOAuth != null) {
            this.sourceRefreshToken = sourceOAuth.Refresh_Token__c;
            this.sourceEndpoint = sourceOAuth.Instance_URL__c + SOAP_ENDPOINT;
        }
    }
}