mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/Scratch_Org__c.object-meta.xml
<CustomObject>
    <label>Scratch Org</label>
    <pluralLabel>Scratch Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <label>Scratch Org Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org_Info__c/Scratch_Org_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Scratch Org Info</label>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org_Info__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <description>Access Token.</description>
    <inlineHelpText>Access Token</inlineHelpText>
    <label>Access Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Info__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description></description>
    <label>Instance URL</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Info__c/fields/SFDX_Auth_URL__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Auth_URL__c</fullName>
    <description></description>
    <inlineHelpText>SFDX AuthURL for the scratch org</inlineHelpText>
    <label>SFDX AuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/ScratchOrgServices.cls
public with sharing class ScratchOrgServices {

    public static final String FRONT_DOOR_URL = '/secur/frontdoor.jsp?sid=';

    public static String getLoginUrl(String scratchOrgId) {
        String url = null;
        Scratch_Org_Info__c soInfo = Scratch_Org_Info__c.getValues(scratchOrgId);
        //TODO: write test and move to another method
        List<Scratch_Org__c> scratchOrgs = [SELECT Id FROM Scratch_Org__c 
            WHERE Id = :scratchOrgId
             AND CreatedById = :UserInfo.getUserId()];

        if(soInfo != null && !scratchOrgs.isEmpty()) {
            url = soInfo.Instance_URL__c + FRONT_DOOR_URL + getFreshAccessToken(soInfo);
        }
        return url;

    }
        public static String getFreshAccessToken(Scratch_Org_Info__c scratchOrgInfo) {
        String accessToken = scratchOrgInfo.Access_Token__c;

        OAuthServices.AppSettings appSettings = new OAuthServices.AppSettings(
            OAuthServices.getAppSettings().callBackURL,
            getClientIdFromAuthUrl(scratchOrgInfo),
            getConsumerSecretFromAuthUrl(scratchOrgInfo));

        //TODO the following should really be the scratchOrgInfo.Instance_URL__c, but we would then have to be able to add that to the remote site settings
        String customLoginUrl = 'https://test.salesforce.com';

        OauthRequest oauthReq = new OAuthRequest(appSettings, customLoginUrl);

        Auth_User__c authUser = new Auth_User__c(
                    Access_Token__c = accessToken, Refresh_Token__c = getRefreshTokenFromAuthUrl(scratchOrgInfo)
        );
        List<Auth_User__c> authUsers = new List<Auth_User__c>{authUser};
        authUsers = oauthReq.reauthorize(authUsers, false);
        String freshAccessToken = authUsers[0].Access_Token__c;
        scratchOrgInfo.Access_Token__c = freshAccessToken;
        update scratchOrgInfo;
        return freshAccessToken;
    }

    //auth url is in the format force://CLIENT_ID:CONSUMER_SECRET:REFRESH_TOKEN@flow-nosoftware-5934-dev-ed.cs10.my.salesforce.com

    public static String getRefreshTokenFromAuthUrl(Scratch_Org_Info__c scratchOrgInfo) {
        String authUrl = scratchOrgInfo.SFDX_Auth_URL__c;
        List<String> parsed = authUrl.split(':');
        return parsed.size() == 4 ? parsed[3].substring(0, parsed[3].indexOf('@')) : '';

    }

    public static String getClientIdFromAuthUrl(Scratch_Org_Info__c scratchOrgInfo) {
        String authUrl = scratchOrgInfo.SFDX_Auth_URL__c;
        List<String> parsed = authUrl.split(':');
        Integer START_INDEX_OF_CLIENT_ID = 2;
        return (parsed.size() == 4 && parsed[1].length() >START_INDEX_OF_CLIENT_ID )?
            parsed[1].substring(START_INDEX_OF_CLIENT_ID): '';
    }

    public static String getConsumerSecretFromAuthUrl(Scratch_Org_Info__c scratchOrgInfo) {
        String authUrl = scratchOrgInfo.SFDX_Auth_URL__c;
        List<String> parsed = authUrl.split(':');
        return parsed.size() == 4 ? parsed[2].substring(0, parsed[2].length()): '';
    }
}