mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <inlineHelpText>Link to download the build package</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Ignore_Deployment_Warnings__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Deployment_Warnings__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Deployment Warnings</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Is_Quick_Deploy__c.field-meta.xml
<CustomField>
    <fullName>Is_Quick_Deploy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Quick Deploy</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Is_Validation__c.field-meta.xml
<CustomField>
    <fullName>Is_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Validation</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Deployed__c</fullName>
    <label>Number Components Deployed</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Errors__c</fullName>
    <label>Number Components Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Total__c</fullName>
    <label>Number Components Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Test_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Test_Errors__c</fullName>
    <label>Number Test Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Tests_Completed__c.field-meta.xml
<CustomField>
    <fullName>Number_Tests_Completed__c</fullName>
    <label>Number Tests Completed</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Tests_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Tests_Total__c</fullName>
    <label>Number Tests Total</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/SF_Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Deployment_Id__c</fullName>
    <label>SF Deployment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Specified_Tests__c.field-meta.xml
<CustomField>
    <fullName>Specified_Tests__c</fullName>
    <label>Specified Tests</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/State_Detail__c.field-meta.xml
<CustomField>
    <fullName>State_Detail__c</fullName>
    <label>State Detail</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Target_Instance__c.field-meta.xml
<CustomField>
    <fullName>Target_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Test_Level__c.field-meta.xml
<CustomField>
    <fullName>Test_Level__c</fullName>
    <label>Test Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NoTestRun</fullName>
            </value>
            <value>
                <fullName>RunSpecifiedTests</fullName>
            </value>
            <value>
                <fullName>RunLocalTests</fullName>
            </value>
            <value>
                <fullName>RunAllTestsInOrg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/DeploymentRequest.cls
public with sharing class DeploymentRequest {

    private static final String DEPLOYMENT_ENDPOINT = ALMRestServices.WEB_SERVICE_URL + '/deployments';
    private static final String ERROR_CODE_404 = '404';

    private Build__c build;
    private String targetInstanceId;
    public String buildId;
    public String almServerURL;
    public Map<String, String> deploymentOptions {get; set;}
    public Map<String, String> targetInstance {get; set;}
    public String packageURL;
    public String sightlineRefreshToken;
    public String clientId;
    public String clientSecret;
    public String validationId;
    public Deployment_Attempt__c deployment {get; set;}

    public DeploymentRequest(Build__c build, Deployment_Attempt__c attempt) {
        this.build = build;
        this.buildId = build.Id;
        this.almServerURL = URL.getSalesforceBaseUrl().toExternalForm();
        this.packageURL = (String.isNotBlank(build.Package_URL__c) && build.Package_URL__c.startsWith('/')) ? this.almServerURL + build.Package_URL__c : build.Package_URL__c;

        Auth_User__c sightlineAuthUser = OAuthServices.getSightlineAuthUser();
        try {
            this.sightlineRefreshToken = sightlineAuthUser.Refresh_Token__c;
        } catch(Exception e) {
            throw new ALMException(System.Label.Sightline_Instance_Not_Authorized);
        }

        OAuthServices.AppSettings settings = OAuthServices.getAppSettings();
        this.clientId = settings.consumerKey;
        this.clientSecret = settings.consumerSecret;

        this.deploymentOptions = new Map<String, String>{
            'isQuickDeploy' => String.valueOf(attempt.Is_Quick_Deploy__c),
            'isValidation' => String.valueOf(attempt.Is_Validation__c),
            'ignoreDeploymentWarnings' => String.valueOf(attempt.Ignore_Deployment_Warnings__c),
            'singlePackage' => 'true',
            'specifiedTests' => attempt.Specified_Tests__c,
            'testLevel' => attempt.Test_Level__c
        };
        this.deployment = attempt;

        if (attempt.Is_Quick_Deploy__c) {
            this.validationId = attempt.SF_Deployment_Id__c;
        }

        setTargetInstanceAuthInfo(attempt.Target_Instance__c, attempt.CreatedById);
    }

    /**
    * @param instanceId     the target instance id
    * @param userId         the user to retrieve the auth info for
    * @throws ALMException
    */
    public void setTargetInstanceAuthInfo(String instanceId, String userId) {
        targetInstanceId = instanceId;
        Instances__c instance = InstanceServices.getInstance(instanceId);

        if (instance == null) {
            throw new ALMException('Unable to find instance with Id: ' + instanceId);
        } else {
            Auth_User__c auth = OAuthServices.getAuthUser(instanceId, false, userId);
            if (auth == null) {
                throw new ALMException(System.Label.Generic_Error + '\nNo Auth User found for instance ['+ instanceId + '] and user [' + userId + ']');
            } else {
                this.targetInstance = new Map<String, String>{
                    'serverURL' => auth.Instance_URL__c,
                    'refreshToken' => auth.Refresh_Token__c
                };
            }
        }
    }

    /**
    * Make deployment request callout
    * @throws ALMException
    */
    public DeploymentCreateResponse send() {
        String endpoint = DEPLOYMENT_ENDPOINT + '/new';
        String body = JSON.serialize(this);

        String response;
        DeploymentCreateResponse deployResult;

        response = ALMRestServices.makePostRequest(endpoint, body);

        try {
            deployResult =
             (DeploymentCreateResponse) JSON.deserialize(response, DeploymentCreateResponse.class);
        }
        catch(JSONException je) {
            System.debug(je);
            throw new ALMException(je.getMessage());
        }

        return deployResult;
    }

    /**
    * @throws ALMException
    */
    public void sendCancelRequest() {
        String endpoint = DEPLOYMENT_ENDPOINT + '/cancel/' + deployment.UUID__c;
        String body = JSON.serialize(new CancelDeploymentRequest(almServerURL));

        // No need to handle response since we are just concerned with HTTP status
        ALMRestServices.makePostRequest(endpoint, body);
    }

    /**
    * Make deployment status callout and update SFDC record with result
    * @param jobUUID    The uuid of the deployment job
    * @return Deployment_Attempt__c  Deployment record with updated values - **note these values are not persisted.
    * @throws ALMException
    */
    public static Deployment_Attempt__c getJobStatus(String jobUUID) {
        String endpoint = DEPLOYMENT_ENDPOINT + '/' + jobUUID;

        String response;
        DeploymentStatusResponse parsedResponse;

        try {
            response = ALMRestServices.makeGetRequest(endpoint);
        } catch (AssemblerException e) {
          System.debug(e.getMessage());
          if (e.getMessage().contains(ERROR_CODE_404)) {
                throw new ALMException('Unable to get status for JOB UUID: ' + jobUUID);
            } else {
                throw new ALMException(e.getMessage());
            }
        }

        try {
            parsedResponse =
             (DeploymentStatusResponse) JSON.deserialize(response, DeploymentStatusResponse.class);
        }
        catch(JSONException je) {
            System.debug(je);
            throw new ALMException(je.getMessage());
        }

        return parsedResponse.getSObject();
    }

    private class CancelDeploymentRequest {
        public String sightlineRefreshToken;
        public String almServerURL;

        public CancelDeploymentRequest() {}

        public CancelDeploymentRequest(String url) {
            almServerURL = url;

            Auth_User__c sightlineAuthUser = OAuthServices.getSightlineAuthUser();
            try {
                this.sightlineRefreshToken = sightlineAuthUser.Refresh_Token__c;
            } catch(Exception e) {
                throw new ALMException(System.Label.Sightline_Instance_Not_Authorized);
            }
        }
    }

    public class DeploymentCreateResponse {
        public String result;
        public String jobId;
    }

    public class DeploymentStatusResponse {
        public String asyncRequestId;
        public String jobId;
        public String status;
        public String startTime;
        public String endTime;
        public Integer numberComponentsDeployed;
        public Integer numberComponentsTotal;
        public Integer numberComponentErrors;
        public Integer numberTestErrors;
        public Integer numberTestsCompleted;
        public Integer numberTestsTotal;
        public String stateDetail;

        public Deployment_Attempt__c getSObject() {
            Deployment_Attempt__c record = new Deployment_Attempt__c();

            record.SF_Deployment_Id__c = asyncRequestId;
            record.Status__c = status;
            record.State_Detail__c = stateDetail;
            record.UUID__c = jobId;
            record.Number_Components_Deployed__c = numberComponentsDeployed;
            record.Number_Components_Errors__c = numberComponentErrors;
            record.Number_Components_Total__c = numberComponentsTotal;
            record.Number_Test_Errors__c = numberTestErrors;
            record.Number_Tests_Completed__c = numberTestsCompleted;
            record.Number_Tests_Total__c = numberTestsTotal;

            return record;
        }
    }
}