mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Commit__c/VC_Commit__c.object-meta.xml
<CustomObject>
    <label>VC Commit</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>VC Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VC Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Backlog_Components__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Components__c</fullName>
    <label>Backlog Components</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Backlog_Item__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Commit History</relationshipLabel>
    <relationshipName>VC_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Commit_Message__c.field-meta.xml
<CustomField>
    <fullName>Commit_Message__c</fullName>
    <label>Commit Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/VC_Repository__c.field-meta.xml
<CustomField>
    <fullName>VC_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>VC Commits</relationshipLabel>
    <relationshipName>VC_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Repository_URL__c</fullName>
    <description>The SSH URL of the version control system repository.</description>
    <inlineHelpText>The SSH URL of the version control system repository. This URL may explicitly specify the "ssh://" protocol or, as in the case of some VC services (e.g. GitHub), the URL may have its own unique syntax.</inlineHelpText>
    <label>Repository URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/fields/SFDC_Metadata_Path__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Metadata_Path__c</fullName>
    <defaultValue>"src"</defaultValue>
    <description>The folder location where the Salesforce metadata files will be committed to and pulled from</description>
    <inlineHelpText>Please provide the folder location where the Salesforce metadata files will be committed to and pulled from.</inlineHelpText>
    <label>Repository Salesforce Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Source_Format__c.field-meta.xml
<CustomField>
    <fullName>Source_Format__c</fullName>
    <inlineHelpText>This setting controls how the metadata is stored in your repository. If you&#39;re building with Salesforce DX scratch orgs, then select &quot;Salesforce DX.&quot; If you&#39;re building in any other standard Salesforce org, select &quot;Metadata API&quot; format.&quot;</inlineHelpText>
    <label>Source Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metadata API</fullName>
            </value>
            <value>
                <fullName>Salesforce DX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/VCCommitRequest.cls
public with sharing class VCCommitRequest extends BaseRequest {

    public String vcCommitId;
    public String commitOwner;
    public String commitMessage;

    public VersionControlSource versionControlSource;

    public String sourceRefreshToken;
    public String sourceEndpoint;

    public List<List<String>> components;
    public List<ProfilePermissions> profiles;
    public List<List<String>> destructiveChanges;

    public VCCommitRequest(VC_Commit__c vcCommit, Auth_User__c sourceAuthUser) {
        super();
        this.vcCommitId    = vcCommit.Id;

        List<VC_Repository__c> repos = [
            SELECT Repository_URL__c, SFDC_Metadata_Path__c, Source_Format__c
                FROM VC_Repository__c
                WHERE Id = :vcCommit.VC_Repository__c ];
        VC_Repository__c repo;
        if (repos.size() > 0) {
            repo = repos[0];
        } else {
            throw new ALMException(System.Label.VC_Repository_Retrieval_Error);
        }

        if (String.isBlank(repo.Repository_URL__c)) {
            throw new ALMException(VCServices.NO_REPOSITORY_URL_ERROR);
        }

        this.commitMessage = vcCommit.Commit_Message__c;
        this.commitOwner = vcCommit.CreatedBy.Username;

        this.sourceRefreshToken = sourceAuthUser.Refresh_Token__c;
        this.sourceEndpoint     = sourceAuthUser.Instance_URL__c + SOAP_ENDPOINT;

        if (String.isEmpty(sightlineRefreshToken)) {
            throw new ALMException(System.Label.Sightline_Instance_Not_Authorized);
        } 

        this.components = new List<List<String>>();
        this.destructiveChanges = new List<List<String>>();
        this.profiles = new List<ProfilePermissions>();

        this.versionControlSource = new VersionControlSource(repo, vcCommit.Branch_Name__c);

        if (String.isBlank(versionControlSource.publicKey) 
            || String.isBlank(versionControlSource.privateKey) 
            || String.isBlank(versionControlSource.passphrase)) {
            throw new ALMException(System.Label.SSH_User_Key_Retrieval_Error);
        }

        loadBacklogComponents(vcCommit.Backlog_Item__c, vcCommit.Backlog_Components__c);
    }

    private void loadBacklogComponents(String backlogId, String rawBacklogComponentIds) {
        components.add( new List<String>{ AssemblerRequest.COMPONENT_HEADER_NAME, AssemblerRequest.COMPONENT_HEADER_TYPE, AssemblerRequest.COMPONENT_HEADER_PARENT,'Profile', 'Profile Permission' });
        destructiveChanges.add( new List<String>{ AssemblerRequest.COMPONENT_HEADER_NAME, AssemblerRequest.COMPONENT_HEADER_TYPE, AssemblerRequest.COMPONENT_HEADER_PARENT });
        List<AssemblerManifestRecord> allBacklogComponents = AssemblerServices.getManifest(null, new List<String>(), new List<String>(), new List<String>(), new List<String> {backlogId});
        Set<String> backlogComponentIds = new Set<String>(rawBacklogComponentIds.split(','));

        for (AssemblerManifestRecord bc : allBacklogComponents ) {
            String backlogComponentId = bc.getBuildComponent().Backlog_Component__c;
            if (backlogComponentIds.contains(backlogComponentId)) {
                if (bc.isDeletion) {
                    destructiveChanges.add(new List<String> { bc.getName(), bc.getType(), bc.getParent() });
                } else {
                    components.add( new List<String> { bc.getName(), bc.getType(), bc.getParent(), '', '0' });
                }
            }
        }
    }

}