mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Auth Users</relationshipLabel>
    <relationshipName>Auth_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Auth_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/TestOAuthRedirectController.cls
@isTest
private class TestOAuthRedirectController {

    static testMethod void handleOAuthRedirect_success() {
        Test.setMock(HttpCalloutMock.class, new MockOAuthAPI(MockOAuthAPI.SUCCESS_ACCESS_TOKEN_REQUEST));
        TestingUtils.createOAuthSettings();
        Id currentUserId = UserInfo.getUserId();

        Instances__c instance = new Instances__c(Name='dev');
        insert instance;

        OAuthRedirectController oauthRedirector = new OAuthRedirectController();
        Map<String,String> state = new Map<String, String>{
            OAuthController.INSTANCE_STATE_PARAM => instance.Id,
            OAuthController.CSRF_STATE_PARAM => OAuthServices.generateCSRFToken()
        };

        OAuthServices.putOAuthRequestStatusInCache(instance.Id, currentUserId, true);

        Test.startTest();
            PageReference ref = Page.OAuthRedirectHandler;
            ref.getParameters().put('code', 'somecode');
            ref.getParameters().put('state', JSON.serialize(state));
            Test.setCurrentPage(ref);

            oauthRedirector.handleRedirect();
        Test.stopTest();

        List<Auth_User__c> auths = [SELECT Id, Instance__c, User__c FROM Auth_User__c];

        System.assertEquals(1, auths.size(), 'when the access token request succeeds, an auth records should be created');
        System.assertEquals(instance.Id, auths[0].Instance__c, 'The instance Id should be set on the auth record');
        System.assertEquals(UserInfo.getUserId(), auths[0].User__c, 'The instance Id should be set on the auth record');
        System.assertEquals(false, OAuthServices.OAuthRequestIsInProgress(instance.Id, currentUserId), 'The cache for this instance should be set to completed');

    }
}