mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/TestAssemblerOrgSourceRequest.cls
@isTest
private class TestAssemblerOrgSourceRequest {


    static testMethod void populatesSourceOAuthInfo() {
        Release__c release = new Release__c(Name='Summer 14');
        insert release;

        Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);
        Instances__c instance = TestingUtils.createInstance('dev');

        TestingUtils.createOAuthSettings();
        TestingUtils.setupSightlineAuth();

        Auth_User__c sourceAuthUser = TestingUtils.createAuthUser(UserInfo.getUserId(), instance.Id);
        Auth_User__c targetAuthUser = TestingUtils.createAuthUser(UserInfo.getUserId(), instance.Id);

        sourceAuthUser.Refresh_Token__c = 'Test Source Refresh Token';
        sourceAuthUser.Instance_URL__c = 'Test Source Instance URL';
        targetAuthUser.Refresh_Token__c = 'Test Target Refresh Token';
        targetAuthUser.Instance_URL__c = 'Test Target Instance URL';

        Test.startTest();

            AssemblerOrgSourceRequest testRequest = new AssemblerOrgSourceRequest(build, sourceAuthUser, targetAuthUser, false);

        Test.stopTest();

        System.assertEquals(build.Id, testRequest.buildId, 'The build ID should match.');
        System.assertEquals(sourceAuthUser.Refresh_Token__c, testRequest.sourceRefreshToken, 'The source refresh token should match.');
        System.assertEquals(sourceAuthUser.Instance_URL__c + AssemblerRequest.SOAP_ENDPOINT, testRequest.sourceEndpoint, 'The source endpoint should match.');
    }
}