mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Assemble_Request_Error__c.field-meta.xml
<CustomField>
    <fullName>Assemble_Request_Error__c</fullName>
    <label>Assemble Request Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Deployed__c</fullName>
    <label>Number Components Deployed</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Total__c</fullName>
    <label>Number Components Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Target_Instance__c.field-meta.xml
<CustomField>
    <fullName>Target_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/TestDeploymentServices.cls
@isTest
private class TestDeploymentServices {

    private static Release__c release;
    private static Instances__c instance;

    private static void setup() {
        release = new Release__c(Name='Test release');
        insert release;

        instance = new Instances__c(Name = 'dev');
        insert instance;
    }

    static testMethod void updateOngoingDeployments() {
        Test.setMock(HttpCalloutMock.class, new MockWebAssemblerAPI(MockWebAssemblerAPI.GET_DEPLOYMENT_ACTION));

        setup();

        Build__c build = new Build__c(Release__c = release.Id);
        insert build;

        Deployment_Attempt__c deployment = new Deployment_Attempt__c(Build__c = build.Id);
        deployment.UUID__c = MockWebAssemblerAPI.JOB_ID;
        deployment.Status__c = 'Pending';
        insert deployment;

        Test.startTest();

            List<Deployment_Attempt__c> deployments = DeploymentServices.updateOngoingDeployments(build.Id);

        Test.stopTest();

        System.assertEquals(1, deployments.size(), 'The pending deployment should be treated as ongoing');

        Deployment_Attempt__c returnedDeployment = deployments[0];

        System.assertEquals(deployment.Id, returnedDeployment.Id, 'The created pending deployment should be returned');
        System.assertEquals(MockWebAssemblerAPI.JOB_ID, returnedDeployment.UUID__c, 'The UUID should remain unchanged');
        System.assertEquals(MockWebAssemblerAPI.DEPLOY_RESULT_SUCCESS_STATUS, returnedDeployment.Status__c, 'The status should be updated from the deployment status response');
        System.assertEquals(MockWebAssemblerAPI.COMPONENT_COUNT, returnedDeployment.Number_Components_Total__c, 'The Number_Components_Total__c should be set from the deployment status response');
        System.assertEquals(MockWebAssemblerAPI.COMPONENT_COUNT, returnedDeployment.Number_Components_Deployed__c, 'The Number_Components_Deployed__c should be set from deployment status response');

        Deployment_Attempt__c updatedDeployment = [SELECT Id, UUID__c, Status__c, Number_Components_Total__c, Number_Components_Deployed__c FROM Deployment_Attempt__c WHERE Id = :deployment.Id];

        System.assertEquals(MockWebAssemblerAPI.JOB_ID, updatedDeployment.UUID__c, 'The UUID should remain unchanged');
        System.assertEquals(MockWebAssemblerAPI.DEPLOY_RESULT_SUCCESS_STATUS, updatedDeployment.Status__c, 'The status should be updated from the deployment status response');
        System.assertEquals(MockWebAssemblerAPI.COMPONENT_COUNT, updatedDeployment.Number_Components_Total__c, 'The Number_Components_Total__c should be updated from the deployment status response');
        System.assertEquals(MockWebAssemblerAPI.COMPONENT_COUNT, updatedDeployment.Number_Components_Deployed__c, 'The Number_Components_Deployed__c should be updated from deployment status response');
    }

    static testMethod void startAttempts() {
        Test.setMock(HttpCalloutMock.class, new MockWebAssemblerAPI(MockWebAssemblerAPI.DEPLOYMENTS_ACTION));
        TestingUtils.createOAuthSettings();
        TestingUtils.setupSightlineAuth();

        setup();

        Auth_User__c authUser = TestingUtils.createAuthUser(UserInfo.getUserId(), instance.Id);

        Build__c build =  TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

        Deployment_Attempt__c attempt = new Deployment_Attempt__c(Build__c = build.Id, Status__c = DeploymentServices.STATUS_NOT_STARTED);
        attempt.Target_Instance__c = instance.Id;
        insert attempt;

        Test.startTest();

            DeploymentServices.startAttempts(new Set<Id>{attempt.Id});

        Test.stopTest();

        Deployment_Attempt__c updatedAttempt = [SELECT Id, UUID__c, Status__c FROM Deployment_Attempt__c WHERE Id = :attempt.Id];
        System.assertEquals(MockWebAssemblerAPI.JOB_ID, updatedAttempt.UUID__c, 'The deploy job should be kicked off and the attempt record updated with the job Id');
        System.assertEquals(MockWebAssemblerAPI.STATUS_RESULT, updatedAttempt.Status__c, 'The deploy job should be kicked off and the attempt record updated with the job Id');
    }

    static testMethod void startAttempts_failureCreatesAlmErrors() {
        Test.setMock(HttpCalloutMock.class, new MockWebAssemblerAPI(MockWebAssemblerAPI.ASSEMBLE_FAILURE_ACTION));

        setup();

        Build__c build =  TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

        Deployment_Attempt__c attempt = new Deployment_Attempt__c(Build__c = build.Id, Status__c = DeploymentServices.STATUS_NOT_STARTED);
        attempt.Target_Instance__c = instance.Id;
        insert attempt;

        Test.startTest();

            DeploymentServices.startAttempts(new Set<Id>{attempt.Id});

        Test.stopTest();

        Deployment_Attempt__c updatedAttempt = [SELECT Id, UUID__c, Status__c, Assemble_Request_Error__c FROM Deployment_Attempt__c WHERE Id = :attempt.Id];
        System.assertEquals(null, updatedAttempt.UUID__c, 'Failures when kicking off the deployment should result in a blank UUID');
        System.assertEquals(DeploymentServices.STATUS_FAILED, updatedAttempt.Status__c, 'The deployment attempt should be marked as a failure');
        System.assertNotEquals(null, updatedAttempt.Assemble_Request_Error__c, 'The deployment attempt should hold an assemble request error.');
    }

}