mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Source_Repository__c.field-meta.xml
<CustomField>
    <fullName>Source_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Repository_URL__c</fullName>
    <description>The SSH URL of the version control system repository.</description>
    <inlineHelpText>The SSH URL of the version control system repository. This URL may explicitly specify the "ssh://" protocol or, as in the case of some VC services (e.g. GitHub), the URL may have its own unique syntax.</inlineHelpText>
    <label>Repository URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/fields/SFDC_Metadata_Path__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Metadata_Path__c</fullName>
    <defaultValue>"src"</defaultValue>
    <description>The folder location where the Salesforce metadata files will be committed to and pulled from</description>
    <inlineHelpText>Please provide the folder location where the Salesforce metadata files will be committed to and pulled from.</inlineHelpText>
    <label>Repository Salesforce Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/TestAssemblerGitSourceRequest.cls
@isTest
private class TestAssemblerGitSourceRequest {

    static testMethod void populatesSourceOAuthInfo() {
        final String TEST_PUBLIC_KEY = 'Test Public Key';
        final String TEST_PRIVATE_KEY = 'Test Private Key';
        final String TEST_PASSPHRASE = 'Test Passphrase';

        Release__c release = new Release__c(Name='Summer 14');
        insert release;

        Instances__c instance = TestingUtils.createInstance('dev');

        TestingUtils.createOAuthSettings();
        TestingUtils.setupSightlineAuth();

        Auth_User__c targetAuthUser = TestingUtils.createAuthUser(UserInfo.getUserId(), instance.Id);
        targetAuthUser.Instance_URL__c = 'Test Target Instance URL';

        Id userId = UserInfo.getUserId();
        SSHServices.storePublicKey(userId, TEST_PUBLIC_KEY);
        SSHServices.storePrivateKey(userId, TEST_PRIVATE_KEY);
        SSHServices.storePassphrase(userId, TEST_PASSPHRASE);

        VC_Repository__c repo = TestingUtils.createVcRepository('git-repo', 'http://www.git.com', 'GitHub', 'GitTest');
        repo.SFDC_Metadata_Path__c = 'some/src/path/';

        Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_NOT_STARTED);
        build.Source_Repository_Location__c = 'master';
        build.Source_Repository__c = repo.Id;

        Test.startTest();
            AssemblerGitSourceRequest assemblerRequest = new AssemblerGitSourceRequest(build, targetAuthUser, repo, false);
        Test.stopTest();

        VersionControlSource vcSource = assemblerRequest.versionControlSource;

        System.assertNotEquals(null, vcSource, 'The version control source info should be populated');
        System.assertEquals(TEST_PUBLIC_KEY, vcSource.publicKey, 'The public key should be set on the version control source ');
        System.assertEquals(TEST_PRIVATE_KEY, vcSource.privateKey, 'The private key should be set on the version control source ');
        System.assertEquals(TEST_PASSPHRASE, vcSource.passphrase, 'The passphrase key should be set on the version control source ');
        System.assertEquals(repo.Id, vcSource.repoId, 'The repo id should be set on the version control source ');
        System.assertEquals(repo.Repository_URL__c, vcSource.repoUrl, 'The repo url should be set on the version control source ');
        System.assertEquals(repo.SFDC_Metadata_Path__c, vcSource.sfdcMetadataPath, 'The metadata path should be set on the version control source ');
        System.assertEquals(build.Source_Repository_Location__c, vcSource.repoLocation, 'The repo location should be set on the version control source ');
    }
}