mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Auth_User__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <description>The endpoint for the instance to authenticate against</description>
    <label>Instance URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mywork/force-app/main/default/classes/BaseRequest.cls
public virtual with sharing class BaseRequest {

    public static final String SOAP_ENDPOINT = '/services/Soap/u/42.0';

    public String sightlineServerURL;
    public String sightlineEndpoint;
    public String clientId;
    public String clientSecret;
    public String organizationId;
    public String sightlineRefreshToken;

    public BaseRequest() {
        Auth_User__c sightlineAuthUser = OAuthServices.getSightlineAuthUser();
        if (sightlineAuthUser != null) {
            this.sightlineRefreshToken = sightlineAuthUser.Refresh_Token__c;
        	this.sightlineServerURL = sightlineAuthUser.Instance_URL__c;
        	this.sightlineEndpoint =  sightlineServerURL + SOAP_ENDPOINT;
        }

        OAuthServices.AppSettings settings = OAuthServices.getAppSettings();
        this.clientId = settings.consumerKey;
        this.clientSecret = settings.consumerSecret;
        this.organizationId = UserInfo.getOrganizationId();

    }
}