mywork/force-app/main/default/objects/Upload_Result__c/Upload_Result__c.object-meta.xml
<CustomObject>
    <label>Upload Result</label>
    <nameField>
        <displayFormat>UR-{00000}</displayFormat>
        <label>Upload Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Upload Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Upload_Result__c/fields/Num_of_Errors__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Errors__c</fullName>
    <description>Number of records that failed to insert</description>
    <label>Num of Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Upload_Result__c/fields/Num_of_Records_Created__c.field-meta.xml
<CustomField>
    <fullName>Num_of_Records_Created__c</fullName>
    <description>Number of successful records created</description>
    <label>Num of Records Created</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/classes/BacklogItemUploadResult.cls
public with sharing class BacklogItemUploadResult {
    // TODO: Determine whether record is required
    @AuraEnabled
    public Upload_Result__c record;
    @AuraEnabled
    public Id successCsvId;
    @AuraEnabled
    public Id failureCsvId;
    @AuraEnabled
    public Decimal numOfErrors;
    @AuraEnabled
    public Decimal numOfRecordsCreated;

    public BacklogItemUploadResult(){
    }

    public BacklogItemUploadResult(Upload_Result__c uploadResult, Id successCsvId, Id failureCSVId){
        this.record = uploadResult;
        this.numOfErrors = uploadResult.Num_of_Errors__c;
        this.numOfRecordsCreated = uploadResult.Num_of_Records_Created__c;
        this.successCsvId = successCsvId;
        this.failureCSVId = failureCSVId;
    }
}