mywork/force-app/main/default/objects/ALM_Application_Result__c/ALM_Application_Result__c.object-meta.xml
<CustomObject>
    <label>ALM Application Result</label>
    <nameField>
        <displayFormat>AAR-{00000}</displayFormat>
        <label>ALM Application Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Application Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(NOT(ISNULL(Run_Time__c)), (Run_Time__c -  Start_Time__c), (NOW() - Start_Time__c)) * 60 * 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (mins)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Success with Warnings</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Run_Time__c.field-meta.xml
<CustomField>
    <fullName>Run_Time__c</fullName>
    <inlineHelpText>The time the job finished running</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>The time the job started running</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/classes/ALMApplicationResultModel.cls
public with sharing class ALMApplicationResultModel {
    @AuraEnabled
    public String id {get; set;}
    @AuraEnabled
    public String startTime {get; set;}
    @AuraEnabled
    public String endTime {get; set;}
    @AuraEnabled
    public String duration {get; set;}
    @AuraEnabled
    public String errorCode {get; set;}
    @AuraEnabled
    public String instanceId {get; set;}
    @AuraEnabled
    public String result {get; set;}
    @AuraEnabled
    public ALM_Application_Result__c record {get; set;}
    @AuraEnabled
    public Boolean isSuccess {get; set;}
    @AuraEnabled
    public Boolean isWarnings {get; set;}
    @AuraEnabled
    public Boolean isFailure {get; set;}
    @AuraEnabled
    public Boolean isInProgress {get; set;}

    public ALMApplicationResultModel(ALM_Application_Result__c record) {
        this.id = record.Id;
        this.startTime = (record.Start_Time__c == null) ? null : record.Start_Time__c.format();
        this.endTime = (record.Run_Time__c == null) ? null : record.Run_Time__c.format();
        this.duration = String.valueOf(record.Duration__c);
        this.errorCode = record.Error_Code__c;
        this.instanceId = record.Instance__c;
        this.result = record.Result__c;
        this.record = record;
        this.isSuccess = ScanServices.SUCCESS_STATUS.equalsIgnoreCase(this.result) ? true : false;
        this.isWarnings = ScanServices.SUCCESS_WITH_WARNINGS_STATUS.equalsIgnoreCase(this.result) ? true : false;
        this.isFailure = ScanServices.FAILURE_STATUS.equalsIgnoreCase(this.result) ? true : false;
        this.isInProgress = !this.isSuccess && !this.isWarnings && !this.isFailure;
    }
}