mywork/force-app/main/default/objects/ALM_Application_Result__c/ALM_Application_Result__c.object-meta.xml
<CustomObject>
    <label>ALM Application Result</label>
    <nameField>
        <displayFormat>AAR-{00000}</displayFormat>
        <label>ALM Application Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Application Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Mail_To__c.field-meta.xml
<CustomField>
    <fullName>Mail_To__c</fullName>
    <label>Mail To</label>
    <type>Email</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Success with Warnings</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Mail_To__c.field-meta.xml
<CustomField>
    <fullName>Mail_To__c</fullName>
    <label>Mail To</label>
    <type>Email</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestALMJobTrigger.cls
@isTest
private class TestALMJobTrigger {

    @isTest
    static void updateMailToOnNonCompletedResults() {
        String SUCCESS = 'Success';
        String RUNNING = 'Running';
        String QUEUED = 'Queued';
        
        ALM_Job__c job = new ALM_Job__c(Status__c=QUEUED);
        insert job;
        
        ALM_Application_Result__c completedResult = new ALM_Application_Result__c(ALM_Job__c=job.Id, Result__c=SUCCESS);
        ALM_Application_Result__c runningResult = new ALM_Application_Result__c(ALM_Job__c=job.Id, Result__c=RUNNING);
        ALM_Application_Result__c queuedResult = new ALM_Application_Result__c(ALM_Job__c=job.Id, Result__c=QUEUED);
        
        insert new List<ALM_Application_Result__c> {completedResult, runningResult, queuedResult};
        
        String NEW_EMAIL = 'foo@bar.com';
        
        Test.startTest();
            job.Mail_To__c = NEW_EMAIL;
            update job;
        Test.stopTest();
        
        List<ALM_Application_Result__c> results = [SELECT Result__c, Mail_To__c 
                                                   FROM ALM_Application_Result__c 
                                                   WHERE ALM_Job__c=:job.Id];
        
        for (ALM_Application_Result__c result : results) {
            String expectedEmail = NEW_EMAIL;
            if (result.Result__c == SUCCESS) {
                expectedEmail = null;
            }
            System.assertEquals(expectedEmail, result.Mail_To__c, 
                'The email address on the ALM Job record should be copied to the ALM Application Result ' + 
                'record when the result record is Running or Queued');
        }
    }
}