mywork/force-app/main/default/objects/ALM_Application_Result__c/ALM_Application_Result__c.object-meta.xml
<CustomObject>
    <label>ALM Application Result</label>
    <nameField>
        <displayFormat>AAR-{00000}</displayFormat>
        <label>ALM Application Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Application Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Success with Warnings</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Run_Time__c.field-meta.xml
<CustomField>
    <fullName>Run_Time__c</fullName>
    <inlineHelpText>The time the job finished running</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Components__c.field-meta.xml
<CustomField>
    <fullName>Components__c</fullName>
    <label>Components</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <inlineHelpText>Store the interval in hours for how often the job should run.</inlineHelpText>
    <label>Interval</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End_Time__c</fullName>
    <inlineHelpText>The time that jobs should finish executing for the day (date value will be ignored). Jobs will not be queued to start after this time.</inlineHelpText>
    <label>Scheduled End Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_On_Friday__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_On_Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the job should run on Fridays.</inlineHelpText>
    <label>Scheduled On Friday</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_On_Monday__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_On_Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the job should run on Mondays.</inlineHelpText>
    <label>Scheduled On Monday</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_On_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_On_Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the job should run on Thursdays.</inlineHelpText>
    <label>Scheduled On Thursday</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_On_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_On_Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the job should run on Tuesdays.</inlineHelpText>
    <label>Scheduled On Tuesday</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_On_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_On_Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the job should run on Wednesdays.</inlineHelpText>
    <label>Scheduled On Wednesday</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Scheduled_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Start_Time__c</fullName>
    <inlineHelpText>The time that jobs should begin executing for the day (date value will be ignored).</inlineHelpText>
    <label>Scheduled Start Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Jobs</relationshipLabel>
    <relationshipName>ALM_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Target_Instance__c.field-meta.xml
<CustomField>
    <fullName>Target_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Jobs (Target Instance)</relationshipLabel>
    <relationshipName>ALM_Jobs1</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>Snapshot</fullName>
            </value>
            <value>
                <fullName>Repo_Sync</fullName>
                <label>Repo Sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Custom_Domain__c.field-meta.xml
<CustomField>
    <fullName>Custom_Domain__c</fullName>
    <description>Used for instances with "My" domains such as "companyname.my.salesforce.com"</description>
    <inlineHelpText>Used for instances with "My" domains such as "companyname.my.salesforce.com"</inlineHelpText>
    <label>Custom Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/fields/Rename_Lock_Expiration_Time__c.field-meta.xml
<CustomField>
    <fullName>Rename_Lock_Expiration_Time__c</fullName>
    <inlineHelpText>The timestamp of the expiration of the renaming lock.</inlineHelpText>
    <label>Rename Lock Expiration Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/InstanceModel.cls
public with sharing class InstanceModel implements Comparable {
    public static final Integer DEFAULT_SCAN_INTERVAL = 4;
    public static final Integer DEFAULT_BUTR_INTERVAL = 4;
    public static final DateTime DEFAULT_SCAN_START_TIME = DateTime.newInstance(Date.today(), Time.newInstance(9,0,0,0));
    public static final DateTime DEFAULT_SCAN_END_TIME = DEFAULT_SCAN_START_TIME.addHours(8);
    public static final DateTime DEFAULT_BUTR_START_TIME = DateTime.newInstance(Date.today(), Time.newInstance(1,0,0,0));
    public static final DateTime DEFAULT_BUTR_END_TIME = DEFAULT_BUTR_START_TIME.addHours(3);
    public static final String DEFAULT_COMPONENTS = '*';
    public static final Integer RENAME_LOCK_TIMEOUT_HOURS = 4;

    public Boolean isScanDeactivationPending {get; set;}
    public Boolean isButrDeactivationPending {get; set;}
    public Boolean isInstanceRenamePending {get; set;}
    public Boolean isInstanceRenameLocked {get; set;}
    public String id {get; set;}
    public String name {get; set;}
    public String customDomain {get; set;}
    public String instanceType {get; set;}
    public List<String> instanceTypes {get; set;}
    public List<ALMApplicationResultModel> scanResults {get; set;}
    public List<ALMApplicationResultModel> butrResults {get; set;}
    public ScanResult lastScanResult {get; set;}

    public ALM_Job__c scanJob {get; set;}
    public ALM_Job__c butrJob {get; set;}

    public Instances__c record {get; set;}

    public Long scanStartTime {
        get {
            return ALMJobServices.getJobTime(scanJob, ALM_Job__c.Scheduled_Start_Time__c);
        }
        set {
            setJobTime(scanJob, ALM_Job__c.Scheduled_Start_Time__c, value);
        }

    }

    public Long scanEndTime {
        get {
            return ALMJobServices.getJobTime(scanJob, ALM_Job__c.Scheduled_End_Time__c);
        }
        set {
            setJobTime(scanJob, ALM_Job__c.Scheduled_End_Time__c, value);
        }
    }

    public Long butrStartTime {
        get {
            return ALMJobServices.getJobTime(butrJob, ALM_Job__c.Scheduled_Start_Time__c);
        }
        set {
            setJobTime(butrJob, ALM_Job__c.Scheduled_Start_Time__c, value);
        }
    }
    public Long butrEndTime {
        get {
            return ALMJobServices.getJobTime(butrJob, ALM_Job__c.Scheduled_End_Time__c);
        }
        set {
            setJobTime(butrJob, ALM_Job__c.Scheduled_End_Time__c, value);
        }
    }

    // Set epoch-formatted time.
    private void setJobTime(ALM_Job__c job, Schema.SObjectField timeField, Long timeValue) {
        if (job != null && timeField != null && timeValue != null) {
            job.put(timeField, DateTime.newInstance(timeValue));
        }
    }

    public Boolean hasActiveScanJob {
        get {
            return scanJob != null && scanJob.Id != null;
        }

        private set;
    }

    public Boolean hasActiveButrJob {
        get {
            return butrJob != null && butrJob.Id != null;
        }

        private set;
    }

    public Boolean instanceCreated {
        get {
            return record != null && record.Id != null;
        }
    }

    public InstanceModel(Instances__c instance) {
        this.record = instance;
        this.id = instance.Id;
        this.name = instance.Name;
        this.customDomain = instance.Custom_Domain__c;
        this.instanceType = instance.Type__c;
        this.instanceTypes = InstanceServices.getInstanceTypes();
        this.scanResults = new List<ALMApplicationResultModel>();
        this.butrResults = new List<ALMApplicationResultModel>();
        this.isScanDeactivationPending = false;
        this.isButrDeactivationPending = false;
        this.isInstanceRenamePending = false;
        this.isInstanceRenameLocked = false;
    }

    public InstanceModel(Instances__c instance, ALM_Job__c scanJob) {
        this(instance);
        this.scanJob = scanJob;
    }

    public void initNewScanJob() {
        scanJob = initNewJob();
        scanJob.Tool__c = ALMJobServices.getToolName(ALMJobServices.ToolType.SCAN);
        scanJob.Components__c = DEFAULT_COMPONENTS;
        setScanJobTargetInstance();
        scanJob.Interval__c = DEFAULT_SCAN_INTERVAL;
        scanJob.Scheduled_Start_Time__c = DEFAULT_SCAN_START_TIME;
        scanJob.Scheduled_End_Time__c = DEFAULT_SCAN_END_TIME;
        this.isScanDeactivationPending = false;
    }

    public void initNewButrJob() {
        butrJob = initNewJob();
        butrJob.Tool__c = ALMJobServices.getToolName(ALMJobServices.ToolType.AUTOMATED_TESTING);
        butrJob.Interval__c = DEFAULT_BUTR_INTERVAL;
        butrJob.Scheduled_Start_Time__c = DEFAULT_BUTR_START_TIME;
        butrJob.Scheduled_End_Time__c = DEFAULT_BUTR_END_TIME;
        this.isButrDeactivationPending = false;
    }

    private ALM_Job__c initNewJob() {
        ALM_Job__c job = new ALM_Job__c();

        job.Source_Instance__c = id;
        job.Status__c = SCANServices.TOOL_STATUS_SCHEDULED;
        job.Scheduled_On_Monday__c = true;
        job.Scheduled_On_Tuesday__c = true;
        job.Scheduled_On_Wednesday__c = true;
        job.Scheduled_On_Thursday__c = true;
        job.Scheduled_On_Friday__c = true;

        return job;
    }

    public void setScanJobTargetInstance() {
        if (scanJob == null) {
            return;
        }
        Instances__c target = InstanceServices.almInstance;
        scanJob.Target_Instance__c = (target == null) ? null : target.Id;
    }

    public Integer compareTo(Object otherObject) {
        return this.name.compareTo(((InstanceModel)otherObject).name);
    }

    public Boolean checkIsRenameLocked() {
        Instances__c instance = InstanceServices.getInstance(this.id);

        if (instance == null || instance.Rename_Lock_Expiration_Time__c == null) {
            return false;
        }

        // The rename lock should expire after a specified timeout period to prevent a record from being perpetually locked in the event that a task fails to unlock it properly.
        Integer lockTimeElapsedMilliseconds = (Integer)(DateTime.now().getTime() - instance.Rename_Lock_Expiration_Time__c);
        this.isInstanceRenameLocked = lockTimeElapsedMilliseconds < 0;
        
        return this.isInstanceRenameLocked;
    }

    /**
    * @throws DMLException, QueryException
    */
    public void setRenameLock() {
        mutateRenameLock(true);
    }

    /**
    * @throws DMLException, QueryException
    */
    public void clearRenameLock() {
        mutateRenameLock(false);
    }

    /**
    * @throws DMLException, QueryException
    * @param locked - The new state of the rename lock.
    */
    private void mutateRenameLock(Boolean locked) {
        List<Instances__c> instances;
        instances = [SELECT Rename_Lock_Expiration_Time__c FROM Instances__c WHERE Id = :this.id FOR UPDATE];
        if (instances.isEmpty()) {
            return;
        }
        Instances__c instance = instances[0];

        instance.Rename_Lock_Expiration_Time__c = locked ? DateTime.now().addHours(RENAME_LOCK_TIMEOUT_HOURS).getTime() : null;
        update instance;

        this.isInstanceRenameLocked = locked;
    }

    /**
    * Represents a SCAN tool result.
    */
    public class ScanResult {
        public String instanceId {get; set;}
        public String lastRunTime {get; set;}
        public String result {get; set;}
        public ALM_Application_Result__c record {get; set;}
        public Boolean hasScanRan {get; set;}
        public Boolean isSuccess {get; set;}
        public Boolean isWarnings {get; set;}
        public Boolean isFailure {get; set;}

        public ScanResult(ALM_Application_Result__c applicationResult) {
            this.instanceId = applicationResult.Instance__c;
            this.lastRunTime = (applicationResult.Run_Time__c == null) ? '' : applicationResult.Run_Time__c.format();
            this.result = applicationResult.Result__c;
            this.record = applicationResult;
            this.hasScanRan = true;
            this.isSuccess = ScanServices.SUCCESS_STATUS.equalsIgnoreCase(this.result) ? true : false;
            this.isWarnings = ScanServices.SUCCESS_WITH_WARNINGS_STATUS.equalsIgnoreCase(this.result) ? true : false;
            this.isFailure = ScanServices.FAILURE_STATUS.equalsIgnoreCase(this.result) ? true : false;

        }

        public ScanResult(String instanceId) {
            this.instanceId = instanceId;
            this.lastRunTime = 'N/A';
            this.result = '-';
            this.hasScanRan = false;
            this.isSuccess = false;
            this.isWarnings = false;
            this.isFailure = false;
        }
    }
}