mywork/force-app/main/default/objects/ALM_Application_Result__c/ALM_Application_Result__c.object-meta.xml
<CustomObject>
    <label>ALM Application Result</label>
    <nameField>
        <displayFormat>AAR-{00000}</displayFormat>
        <label>ALM Application Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Application Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Success with Warnings</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Async_Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Apex_Job_Id__c</fullName>
    <externalId>true</externalId>
    <label>Async ApexJob Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Jobs</relationshipLabel>
    <relationshipName>ALM_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SCAN</fullName>
            </value>
            <value>
                <fullName>Automated Testing</fullName>
            </value>
            <value>
                <fullName>Snapshot</fullName>
            </value>
            <value>
                <fullName>Repo_Sync</fullName>
                <label>Repo Sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Code_Coverage__c/Code_Coverage__c.object-meta.xml
<CustomObject>
    <label>Code Coverage</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Code Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Code_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Code_Coverage__c</fullName>
    <formula>IF(Total_Lines__c  != 0 ,   Lines_Covered__c  /   Total_Lines__c , NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total code coverage of all Apex classes and triggers.  75% is needed to pass.</inlineHelpText>
    <label>Apex Code Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Unit_Test_Summary__c.field-meta.xml
<CustomField>
    <fullName>Unit_Test_Summary__c</fullName>
    <inlineHelpText>The summary record that this test result is a part of.</inlineHelpText>
    <label>Unit Test Summary</label>
    <referenceTo>Unit_Test_Summary__c</referenceTo>
    <relationshipName>Apex_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/ExecuteTestMonitorDelay__c/ExecuteTestMonitorDelay__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ExecuteTestMonitorDelay</label>
</CustomObject>

mywork/force-app/main/default/objects/ExecuteTestMonitorDelay__c/fields/DelayInMinutes__c.field-meta.xml
<CustomField>
    <fullName>DelayInMinutes__c</fullName>
    <label>DelayInMinutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/Unit_Test_Failure__c.object-meta.xml
<CustomObject>
    <description>Represents failed unit test methods from a test run</description>
    <label>Unit Test Failure</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Failed Unit Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Test Failures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/fields/Unit_Test_Summary__c.field-meta.xml
<CustomField>
    <fullName>Unit_Test_Summary__c</fullName>
    <description>The summary record that this test error result is a part of.</description>
    <label>Unit Test Summary</label>
    <referenceTo>Unit_Test_Summary__c</referenceTo>
    <relationshipLabel>Unit Test Failures</relationshipLabel>
    <relationshipName>Unit_Test_Failures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/Unit_Test_Summary__c.object-meta.xml
<CustomObject>
    <description>Summary of unit test results</description>
    <label>Unit Test Summary</label>
    <nameField>
        <displayFormat>UTS-{00000}</displayFormat>
        <label>Unit Test Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Test Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance where the unit tests were run</description>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Unit Test Summaries</relationshipLabel>
    <relationshipName>Unit_Test_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <formula>IF(System_Error__c, "Fail",
IF(AND(Failed_Apex_Tests__c = 0, Apex_Code_Coverage__c = 0, Apex_Total_LOC__c = 0), "Pass",
IF(AND(Failed_Apex_Tests__c = 0, Apex_Code_Coverage__c >= 0.75), "Pass", "Fail" )
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The overall test result.  Total Coverage must be 75% or higher and there are no failed test results.</inlineHelpText>
    <label>Result</label>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/ExecuteTestMonitorBatch.cls
public with sharing class ExecuteTestMonitorBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful, Schedulable {

    @TestVisible private String query;
    public static final String RUNNING_STATUS = SCANServices.TOOL_STATUS_RUNNING;
    public static Integer SCOPE_SIZE = 1;
    @TestVisible private ExecuteTestMonitorDelay__c delayInMinutes {
        get {
            if (delayInMinutes == null) {
                delayInMinutes = ExecuteTestMonitorDelay__c.getOrgDefaults();
                if (delayInMinutes.DelayInMinutes__c == null) {
                    delayInMinutes.DelayInMinutes__c = 0;
                }
            }
            return delayInMinutes;
        }
        set;
    }
    @TestVisible private static final Integer POLL_INTERVAL_INCREMENT = 1;
    @TestVisible private static final Integer BACKOFF_THRESHOLD_IN_MINUTES = 15;
    public static final String BATCH_JOB_TITLE = 'Execute Test Monitor Batch Job';
    @TestVisible private static final String BUTR_TOOL_NAME = ALMJobServices.getToolName(ALMJobServices.ToolType.AUTOMATED_TESTING);
    @TestVisible private List<ALM_Job__c> modifiedJobs;

    /**
     * @description Initializes query for alm job records
     */
    public ExecuteTestMonitorBatch() {
        this.query = 'SELECT Id, Async_Apex_Job_Id__c, Tool__c, Source_Instance__c, Status__c FROM ALM_Job__c WHERE Status__c = :RUNNING_STATUS AND Tool__c = :BUTR_TOOL_NAME';
        modifiedJobs = new List<ALM_Job__c>();
    }

    /**
     * @description Initializes the batch querying process
     * @param Database.BatchableContext bc
     * @return Database.QueryLocator
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    /**
     * @description Executes the process of records (alm jobs) that should be monitored for completion
     * @param Database.BatchableContext bc
     * @param SObject[] scope
     */
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        // Maps job IDs to jobs.
        Map<Id, ALM_Job__c> currentScopeMap = new Map<Id, ALM_Job__c>((List<ALM_Job__c>)scope);

        // Retrieve completed job unit test summaries mapped by job ID.
        Map<Id, Unit_Test_Summary__c> jobIdToUnitTestSummary = ExecuteTestMonitorBatchServices.checkForCompletedJobs(currentScopeMap.values());

        // Update the lists of completed jobs.
        List<ALM_Job__c> completedJobs = new List<ALM_Job__c>();
        for (Id jobId : jobIdToUnitTestSummary.keySet()) {
            completedJobs.add(currentScopeMap.get(jobId));
        }
        modifiedJobs.addAll(completedJobs);

        // Retrieves code coverage results and test failure results, mapped by job ID.
        Map<Id, CodeCoverageAggregate> jobIdToCoverageMap = ExecuteTestMonitorBatchServices.getCodeCoverageForJobs(completedJobs);
        Map<Id, CodeTestRunResult> jobIdToTestResultMap = ExecuteTestMonitorBatchServices.getCodeTestResultsForJobs(completedJobs);

        // Updates unit test summary objects with the correct instance lookup and inserts them.
        for (Id jobId : jobIdToUnitTestSummary.keySet()) {
            Unit_Test_Summary__c unitTestSummary = jobIdToUnitTestSummary.get(jobId);
            unitTestSummary.Instance__c = currentScopeMap.get(jobId).Source_Instance__c;
        }
        insert jobIdToUnitTestSummary.values();

        // Retrieves existing application results for the relevant jobs and maps them by job ID.
        Map<Id, ALM_Application_Result__c> jobIdToApplicationResult = 
            ALMApplicationResultServices.getLatestInProgressApplicationResultForJobs(Pluck.ids(completedJobs));

        // Creates code coverage result objects and associates them with their test summary.
        List<Code_Coverage__c> codeCoverageResultsToInsert = new List<Code_Coverage__c>();
        for (Id jobId : jobIdToCoverageMap.keySet()) {
            ALM_Application_Result__c applicationResult = jobIdToApplicationResult.get(jobId);

            if (applicationResult != null && applicationResult.Result__c == SCANServices.FAILURE_STATUS) {
                continue;
            }
            
            CodeCoverageAggregate coverage = jobIdToCoverageMap.get(jobId);
            ALM_Job__c job = currentScopeMap.get(jobId);
            Unit_Test_Summary__c unitTestSummary = jobIdToUnitTestSummary.get(jobId);

            List<Code_Coverage__c> newCodeCoverageResults = 
                ExecuteTestMonitorBatchServices.createCoverageObjectsForJob(coverage, job, applicationResult, unitTestSummary);

            if (newCodeCoverageResults != null) {
                codeCoverageResultsToInsert.addAll(newCodeCoverageResults);
            }
        }

        // Creates unit test failure objects and associates them with their test summary.
        List<Unit_Test_Failure__c> unitTestFailureResultsToInsert = new List<Unit_Test_Failure__c>();
        for (Id jobId : jobIdToTestResultMap.keySet()) {
            ALM_Application_Result__c applicationResult = jobIdToApplicationResult.get(jobId);

            if (applicationResult != null && applicationResult.Result__c == SCANServices.FAILURE_STATUS) {
                continue;
            }
            
            CodeTestRunResult testResult = jobIdToTestResultMap.get(jobId);
            ALM_Job__c job = currentScopeMap.get(jobId);
            Unit_Test_Summary__c unitTestSummary = jobIdToUnitTestSummary.get(jobId);

            List<Unit_Test_Failure__c> newUnitTestFailureResults = 
                ExecuteTestMonitorBatchServices.createUnitTestFailureObjectsForJob(testResult, job, applicationResult, unitTestSummary);

            if (newUnitTestFailureResults != null) {
                unitTestFailureResultsToInsert.addAll(newUnitTestFailureResults);   
            }
        }

        // Set the last successful run time on all successful jobs.
        DateTime now = DateTime.now();
        for (Id jobId : currentScopeMap.keySet()) {
            ALM_Application_Result__c applicationResult = jobIdToApplicationResult.get(jobId);

            if (applicationResult != null && applicationResult.Result__c == SCANServices.SUCCESS_STATUS) {
                ALMJobServices.markJobAsSuccess(currentScopeMap.get(jobId));
            }
        }

        // Inserts and updates relevant objects and sets completed jobs back to "Scheduled" status.
        try {
            insert codeCoverageResultsToInsert;
            insert unitTestFailureResultsToInsert;
            update jobIdToUnitTestSummary.values();
            update jobIdToApplicationResult.values();

            ExecuteTestMonitorBatchServices.updateJobsToScheduled(completedJobs);
        } catch (DMLException e) {
            ALMLogServices.error(e, ALMLogServices.Application.AUTOMATED_TESTING);
        }
    }

    /**
     * @description Aborts the scheduled job and executes the batch job.
     * @param SchedulableContext sc
     */
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new ExecuteTestMonitorBatch(), SCOPE_SIZE);

        System.abortJob(sc.getTriggerId());
    }

    /**
     * @description Determines whether to run again, if there are more alm job records that need to be processed.
     * @param Database.BatchableContext bc
     */
    public void finish(Database.BatchableContext bc) {
        List<ALM_Job__c> jobsRemaining = Database.query(this.query + ' LIMIT 1');

        if (!modifiedJobs.isEmpty()) {
            delayInMinutes.DelayInMinutes__c = POLL_INTERVAL_INCREMENT;
        }

        if (!jobsRemaining.isEmpty() && !ExecuteTestMonitorBatchServices.isMonitorBatchScheduledOrRunning()) {
            if (modifiedJobs.isEmpty() && delayInMinutes.DelayInMinutes__c < BACKOFF_THRESHOLD_IN_MINUTES) {
                delayInMinutes.DelayInMinutes__c += POLL_INTERVAL_INCREMENT;
            }
            System.scheduleBatch(new ExecuteTestMonitorBatch(), BATCH_JOB_TITLE, (Integer) delayInMinutes.DelayInMinutes__c, SCOPE_SIZE);
        }
        try{
            upsert delayInMinutes;
        }
        catch (DMLException e) {
            ALMLogServices.error(e, ALMLogServices.Application.AUTOMATED_TESTING);
        }
    }
}