mywork/force-app/main/default/objects/ALM_Application_Result__c/ALM_Application_Result__c.object-meta.xml
<CustomObject>
    <label>ALM Application Result</label>
    <nameField>
        <displayFormat>AAR-{00000}</displayFormat>
        <label>ALM Application Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Application Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Application_Result__c/fields/ALM_Job__c.field-meta.xml
<CustomField>
    <fullName>ALM_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ALM Job</label>
    <referenceTo>ALM_Job__c</referenceTo>
    <relationshipLabel>ALM Application Results</relationshipLabel>
    <relationshipName>ALM_Application_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/ALM_Job__c.object-meta.xml
<CustomObject>
    <label>ALM Job</label>
    <nameField>
        <displayFormat>AJ-{00000}</displayFormat>
        <label>ALM Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Async_Apex_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Apex_Job_Id__c</fullName>
    <externalId>true</externalId>
    <label>Async ApexJob Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>ALM Jobs</relationshipLabel>
    <relationshipName>ALM_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Auth_User__c/Auth_User__c.object-meta.xml
<CustomObject>
    <description>The link between a User and an OAuth session.</description>
    <label>Auth User</label>
    <nameField>
        <displayFormat>AU-{0000}</displayFormat>
        <label>Auth User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auth Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Code_Coverage__c/Code_Coverage__c.object-meta.xml
<CustomObject>
    <label>Code Coverage</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Code Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Code_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Code_Coverage__c</fullName>
    <formula>IF(Total_Lines__c  != 0 ,   Lines_Covered__c  /   Total_Lines__c , NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total code coverage of all Apex classes and triggers.  75% is needed to pass.</inlineHelpText>
    <label>Apex Code Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Lines_Covered__c.field-meta.xml
<CustomField>
    <fullName>Lines_Covered__c</fullName>
    <inlineHelpText>The number of apex code lines that have been executed after running unit tests.</inlineHelpText>
    <label>Lines Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Total_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines__c</fullName>
    <inlineHelpText>The total number of lines in this Apex trigger or class.</inlineHelpText>
    <label>Total Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Code_Coverage__c/fields/Unit_Test_Summary__c.field-meta.xml
<CustomField>
    <fullName>Unit_Test_Summary__c</fullName>
    <inlineHelpText>The summary record that this test result is a part of.</inlineHelpText>
    <label>Unit Test Summary</label>
    <referenceTo>Unit_Test_Summary__c</referenceTo>
    <relationshipName>Apex_Coverage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/Unit_Test_Failure__c.object-meta.xml
<CustomObject>
    <description>Represents failed unit test methods from a test run</description>
    <label>Unit Test Failure</label>
    <nameField>
        <displayFormat>UT-{00000}</displayFormat>
        <label>Failed Unit Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Test Failures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>The class that this method is a member of</description>
    <inlineHelpText>The class that this method is a member of</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message from the test failure</description>
    <inlineHelpText>The error message from the test failure</inlineHelpText>
    <label>Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The name of the test method that failed</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Failure__c/fields/Unit_Test_Summary__c.field-meta.xml
<CustomField>
    <fullName>Unit_Test_Summary__c</fullName>
    <description>The summary record that this test error result is a part of.</description>
    <label>Unit Test Summary</label>
    <referenceTo>Unit_Test_Summary__c</referenceTo>
    <relationshipLabel>Unit Test Failures</relationshipLabel>
    <relationshipName>Unit_Test_Failures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/Unit_Test_Summary__c.object-meta.xml
<CustomObject>
    <description>Summary of unit test results</description>
    <label>Unit Test Summary</label>
    <nameField>
        <displayFormat>UTS-{00000}</displayFormat>
        <label>Unit Test Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Test Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/Apex_Lines_Covered__c.field-meta.xml
<CustomField>
    <fullName>Apex_Lines_Covered__c</fullName>
    <inlineHelpText>The total number of Apex lines covered</inlineHelpText>
    <label>Apex Lines Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/Apex_Total_LOC__c.field-meta.xml
<CustomField>
    <fullName>Apex_Total_LOC__c</fullName>
    <inlineHelpText>The total number of lines of apex code</inlineHelpText>
    <label>Apex Total Lines of Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/Error_Details__c.field-meta.xml
<CustomField>
    <fullName>Error_Details__c</fullName>
    <inlineHelpText>Log field for detailed error messages from testing.</inlineHelpText>
    <label>Error Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Unit_Test_Summary__c/fields/System_Error__c.field-meta.xml
<CustomField>
    <fullName>System_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>System Error</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/classes/ExecuteTestMonitorBatchServices.cls
public with sharing class ExecuteTestMonitorBatchServices {
    public static final String SCHEDULED_STATUS = 'Scheduled';
    @TestVisible private final static String RUNNING_BATCH = 'Processing';
    @TestVisible private final static String QUEUED_BATCH = 'Queued';
    @TestVisible private final static String PREPARING_BATCH = 'Preparing';
    public final static List<String> STARTING_CATEGORY = new List<String>{QUEUED_BATCH, PREPARING_BATCH};

    public static final String ERROR_RETRIEVAL_AUTH_AND_ASYNC = 'Auth user and Async ApexJob ID cannot be found.';
    public static final String ERROR_RETRIEVAL_AUTH = 'Auth user cannot be found.';
    public static final String ERROR_RETRIEVAL_ASYNC = 'Async ApexJob ID cannot be found.';
    public static final String ERROR_RETRIEVAL_COVERAGE = 'Could not retrieve code coverage results.';
    public static final String ERROR_RETRIEVAL_FAILURES = 'Could not retrieve unit test failure results.';

    public static final String SUMMARY_FAILURES_TRUNCATED = '...[Too long, truncated]';

    @TestVisible private static String ASYNC_TOOLING_BASEQUERY = 'Select UserId, TestTime, SystemModstamp, Status,'
            + 'StartTime, Source, MethodsFailed, MethodsEnqueued,'
            + 'MethodsCompleted, LastModifiedDate, LastModifiedById, '
            + 'JobName, IsDeleted, IsAllTests, Id, EndTime, CreatedDate, '
            + 'CreatedById, ClassesEnqueued, ClassesCompleted, AsyncApexJobId From ApexTestRunResult';

    public static boolean isMonitorBatchScheduledOrRunning() {
        Boolean found = false;

        //First we check to see if the job is scheduled
        String cronQuery =    'SELECT Id'
                + ' FROM CronTrigger WHERE NextFireTime <> null'
                + ' AND CronJobDetail.Name = \''+ExecuteTestMonitorBatch.BATCH_JOB_TITLE+'\''
                + ' LIMIT 1';
        List<CronTrigger> cjobs = Database.query(cronQuery);

        if (!cjobs.isEmpty()) {
            found = true;
        }
        else
        {
            //Then we check to see if it is running or queued
            String query =  'SELECT Id'
                    + ' FROM AsyncApexJob'
                    + ' WHERE (JobType = \'BatchApex\')'
                    + ' AND ApexClass.Name = \'ExecuteTestMonitorBatch\''
                    + ' AND (Status in ' + BluewolfDevUtils.flattenListForQuery(STARTING_CATEGORY)
                    + ' OR Status in '+ BluewolfDevUtils.flattenListForQuery(new List<String>{ RUNNING_BATCH }) + ')'
                    + ' LIMIT 1';

            List<AsyncApexJob> inProgressJobs = Database.query(query);

            if (!inProgressJobs.isEmpty()) {
                found = true;
            }
        }

        return found;
    }

    /**
    * Retrieves unit test summaries for any completed jobs in the given job collection.
    * @param jobs - A collection of jobs to check on.
    * @return A map of "job ID => unit test summary".
    */
    public static Map<Id, Unit_Test_Summary__c> checkForCompletedJobs(List<ALM_Job__c> jobs) {
        Map<Id, Unit_Test_Summary__c> jobIdToUnitTestSummary = new Map<Id, Unit_Test_Summary__c>();

        Map<Id, Set<String>> instanceIdToAsyncJobIds = mapInstanceIdToAsyncJobIds(jobs);
        Map<Id, Auth_User__c> instanceIdToAuthUser = OAuthServices.getAuthUsersForTools(BluewolfDevUtils.convertIdsToStrings(instanceIdToAsyncJobIds.keySet()));

        Map<String, Unit_Test_Summary__c> asyncJobIdToUnitTestSummary = new Map<String, Unit_Test_Summary__c>();
        for (Id instanceId : instanceIdToAsyncJobIds.keySet()) {
            CodeTestRunSummary completedJobsSummary = new CodeTestRunSummary();
            completedJobsSummary.records = new List<CodeTestRunSummary.Records>();

            Auth_User__c authUser = instanceIdToAuthUser.get(instanceId);
            Set<String> asyncJobIds = instanceIdToAsyncJobIds.get(instanceId);

            // If the auth user or async IDs are unavailable, create error results.
            if (authUser == null || asyncJobIds == null) {
                String errorMessage = '';
                if (authUser == null && asyncJobIds == null) {
                    errorMessage = ERROR_RETRIEVAL_AUTH_AND_ASYNC;
                } else if (authUser == null) {
                    errorMessage = ERROR_RETRIEVAL_AUTH;
                } else if (asyncJobIds == null) {
                    errorMessage = ERROR_RETRIEVAL_ASYNC;
                }

                Set<ALM_Job__c> errorJobs = new Set<ALM_Job__c>();
                for (ALM_Job__c job : jobs) {
                    if (job.Source_Instance__c == instanceId) {
                        errorJobs.add(job);
                    }
                }

                completedJobsSummary.error = new ALMException(errorMessage);
                for (ALM_Job__c errorJob : errorJobs) {
                    CodeTestRunSummary.Records errorRecord = new CodeTestRunSummary.Records();
                    errorRecord.asyncApexJobId = errorJob.Async_Apex_Job_Id__c;
                    completedJobsSummary.records.add(errorRecord);
                }
            } else {
                // Try to retrieve summaries for completed jobs, or create error results if this fails.
                try {
                    completedJobsSummary = ToolingServices.getCompletedTestRunSummaries(authUser, asyncJobIds);
                } catch (Exception e) {
                    completedJobsSummary.error = e;
                    for (String asyncJobId : asyncJobIds) {
                        CodeTestRunSummary.Records errorRecord = new CodeTestRunSummary.Records();
                        errorRecord.asyncApexJobId = asyncJobId;
                        completedJobsSummary.records.add(errorRecord);
                    }
                }
            }

            if (completedJobsSummary != null) {
                asyncJobIdToUnitTestSummary.putAll(completedJobsSummary.deconstructIntoSobjectRecords());
            }
        }

        for (ALM_Job__c job : jobs) {
            Unit_Test_Summary__c unitTestSummary = asyncJobIdToUnitTestSummary.get(job.Async_Apex_Job_Id__c);
            if (unitTestSummary != null) {
                jobIdToUnitTestSummary.put(job.Id, unitTestSummary);
            }
        }

        return jobIdToUnitTestSummary;
    }

    /**
    * Retrieves code coverage for all jobs in the given job collection.
    * @param jobs - A collection of jobs to retrieve code coverage for.
    * @return A map of "job ID => code coverage results".
    */
    public static Map<Id, CodeCoverageAggregate> getCodeCoverageForJobs(List<ALM_Job__c> completedJobs) {
        Map<Id, CodeCoverageAggregate> jobIdToAggregatesMapToReturn = new Map<Id, CodeCoverageAggregate>();
        Map<String, List<ALM_Job__c>> jobsGroupedByInstanceId = GroupBy.Strings(ALM_Job__c.Source_Instance__c, completedJobs);
        Map<Id,Auth_User__c> instanceIdToAuthUser = OAuthServices.getAuthUsersForTools(jobsGroupedByInstanceId.keySet());

        for (Id instanceId : instanceIdToAuthUser.keySet()) {
            Auth_User__c authUser = instanceIdToAuthUser.get(instanceId);

            // Try to retrieve code coverage results for jobs, or create error results if this fails.
            try {
                CodeCoverageAggregate coverage = ToolingServices.getCodeCoverage(authUser);
                for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                    jobIdToAggregatesMapToReturn.put(job.Id, coverage);
                }
            } catch (Exception e) {
                for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                    CodeCoverageAggregate errorRecord = new CodeCoverageAggregate();
                    errorRecord.error = e;
                    jobIdToAggregatesMapToReturn.put(job.Id, errorRecord);
                }
            }
        }

        return jobIdToAggregatesMapToReturn;
    }

    /**
    * Retrieves test results for all jobs in the given job collection.
    * @param jobs - A collection of jobs to retrieve test results for.
    * @return A map of "job ID => code test run results".
    */
    public static Map<Id, CodeTestRunResult> getCodeTestResultsForJobs(List<ALM_Job__c> completedJobs) {
        Map<Id, CodeTestRunResult> jobIdToTestResultsToReturn = new Map<Id, CodeTestRunResult>();

        Map<String, List<ALM_Job__c>> jobsGroupedByInstanceId = GroupBy.Strings(ALM_Job__c.Source_Instance__c, completedJobs);
        Map<Id,Auth_User__c> instanceIdToAuthUser = OAuthServices.getAuthUsersForTools(jobsGroupedByInstanceId.keySet());

        for (Id instanceId : instanceIdToAuthUser.keySet()) {
            Auth_User__c authUser = instanceIdToAuthUser.get(instanceId);
            Set<String> asyncJobIds = new Set<String>();
            for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                asyncJobIds.add(job.Async_Apex_Job_Id__c);
            }

            // Try to retrieve test run results for jobs, or create error results if this fails.
            try {
                CodeTestRunResult codeTestResult = ToolingServices.getTestResults(authUser, asyncJobIds);
                for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                    jobIdToTestResultsToReturn.put(job.Id, codeTestResult);
                }
            } catch (Exception e) {
                for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                    CodeTestRunResult errorRecord = new CodeTestRunResult();
                    errorRecord.error = e;
                    jobIdToTestResultsToReturn.put(job.Id, errorRecord);
                }
            }
        }

        return jobIdToTestResultsToReturn;
    }

    /**
    * Creates code coverage objects from the given coverage result.
    * @param coverage - A code coverage result.
    * @param job - The test run job. May be modified as a side effect.
    * @param applicationResult - The application result related to the coverage's test run. May be modified as a side effect.
    * @param unitTestSummary - The unit test summary related to the coverage's test run. May be modified as a side effect.
    * @return A collection of code coverage objects.
    */
    public static List<Code_Coverage__c> createCoverageObjectsForJob(CodeCoverageAggregate coverage, ALM_Job__c job, ALM_Application_Result__c applicationResult, Unit_Test_Summary__c unitTestSummary) {
        if (coverage == null || job == null || applicationResult == null || unitTestSummary == null) {
            return null;
        }

        List<Code_Coverage__c> codeCoverageResults = coverage.deconstructIntoSobjectRecords();

        if (coverage.error != null) {
            ALMJobServices.markJobAsFailure(job, ERROR_RETRIEVAL_COVERAGE);
            ALMApplicationResultServices.markResultAsFailure(applicationResult, ERROR_RETRIEVAL_COVERAGE);
            ALMApplicationResultServices.appendWarning(applicationResult, coverage.error.getMessage());

            unitTestSummary.System_Error__c = true;
        } else {
            ALMApplicationResultServices.markResultAsSuccess(applicationResult);

            for (Code_Coverage__c codeCoverageResult : codeCoverageResults) {
                codeCoverageResult.Unit_Test_Summary__c = unitTestSummary.Id;

                unitTestSummary.Apex_Lines_Covered__c =
                    unitTestSummary.Apex_Lines_Covered__c != null ?
                    unitTestSummary.Apex_Lines_Covered__c + codeCoverageResult.Lines_Covered__c :
                    codeCoverageResult.Lines_Covered__c;
                unitTestSummary.Apex_Total_LOC__c =
                    unitTestSummary.Apex_Total_LOC__c != null ?
                    unitTestSummary.Apex_Total_LOC__c + codeCoverageResult.Total_Lines__c :
                    codeCoverageResult.Total_Lines__c;
            }
        }

        return codeCoverageResults;
    }

    /**
    * Creates unit test failure objects from the given code test run result.
    * @param testResult - A code test run result.
    * @param job - The test run job. May be modified as a side effect.
    * @param applicationResult - The application result related to the test result's test run. May be modified as a side effect.
    * @param unitTestSummary - The unit test summary related to the test result's test run. May be modified as a side effect.
    * @return A collection of unit test failure objects.
    */
    public static List<Unit_Test_Failure__c> createUnitTestFailureObjectsForJob(CodeTestRunResult testResult, ALM_Job__c job, ALM_Application_Result__c applicationResult, Unit_Test_Summary__c unitTestSummary) {
        if (testResult == null || job == null || applicationResult == null || unitTestSummary == null) {
            return null;
        }

        List<Unit_Test_Failure__c> unitTestFailureResults = testResult.deconstructIntoSobjectRecords();

        if (testResult.error != null) {
            ALMJobServices.markJobAsFailure(job, ERROR_RETRIEVAL_FAILURES);
            ALMApplicationResultServices.markResultAsFailure(applicationResult, ERROR_RETRIEVAL_FAILURES);
            ALMApplicationResultServices.appendWarning(applicationResult, testResult.error.getMessage());

            unitTestSummary.System_Error__c = true;
        } else {
            ALMApplicationResultServices.markResultAsSuccess(applicationResult);

            for (Unit_Test_Failure__c unitTestFailureResult : unitTestFailureResults) {
                unitTestFailureResult.Unit_Test_Summary__c = unitTestSummary.Id;
            }

            accumulateTestFailuresOntoSummary(unitTestSummary, unitTestFailureResults);
        }

        return unitTestFailureResults;
    }

    public static void updateJobsToScheduled(List<ALM_Job__c> completedJobs) {
        for (ALM_Job__c job : completedJobs) {
            job.Status__c = SCHEDULED_STATUS;
        }
        try {
            update completedJobs;
        }
        catch (DMLException dex) {
            throw dex;
        }

    }

    private static void accumulateTestFailuresOntoSummary(Unit_Test_Summary__c unitTestSummary, List<Unit_Test_Failure__c> unitTestFailures) {
        String unitTestFailureString = 
            unitTestSummary.Error_Details__c != null ? 
            unitTestSummary.Error_Details__c : 
            '';

        for (Unit_Test_Failure__c unitTestFailure : unitTestFailures) {
            unitTestFailureString += 
                unitTestFailure.Class_Name__c + '.' + 
                unitTestFailure.Method_Name__c + ': ' + 
                unitTestFailure.Message__c + 
                '\n\n';
        }

        if (!String.isBlank(unitTestFailureString)) {
            Integer maxLength = Unit_Test_Summary__c.Error_Details__c.getDescribe().getLength();

            if (unitTestFailureString.length() > maxLength) {
                unitTestSummary.Error_Details__c = 
                    unitTestFailureString.abbreviate(maxLength - SUMMARY_FAILURES_TRUNCATED.length()) + 
                    SUMMARY_FAILURES_TRUNCATED;
            } else {
                unitTestSummary.Error_Details__c = unitTestFailureString;
            }
        }
    }

    private static Map<Id, Set<String>> mapInstanceIdToAsyncJobIds(List<ALM_Job__c> jobs) {
        Map<Id, List<ALM_Job__c>> jobsGroupedByInstanceId = GroupBy.Ids(ALM_Job__c.Source_Instance__c, jobs);

        Map<Id, Set<String>> instanceIdToAsyncJobIds = new Map<Id, Set<String>>();
        for (Id instanceId : jobsGroupedByInstanceId.keySet()) {
            Set<String> asyncJobIds = new Set<String>();

            for (ALM_Job__c job : jobsGroupedByInstanceId.get(instanceId)) {
                if (job.Async_Apex_Job_Id__c != null) {
                    asyncJobIds.add(job.Async_Apex_Job_Id__c);
                }
            }

            if (!asyncJobIds.isEmpty()) {
                instanceIdToAsyncJobIds.put(instanceId, asyncJobIds);
            }
        }

        return instanceIdToAsyncJobIds;
    }
}