mywork/force-app/main/default/objects/CI_Instance__c/CI_Instance__c.object-meta.xml
<CustomObject>
    <label>CI Instance</label>
    <nameField>
        <label>CI Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CI Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/CI_Instance__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>CI Instances</relationshipLabel>
    <relationshipName>CI_Instances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/Jenkins_Build__c.object-meta.xml
<CustomObject>
    <label>Jenkins Build</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jenkins Build Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jenkins Builds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/CI_Instance__c.field-meta.xml
<CustomField>
    <fullName>CI_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CI Instance</label>
    <referenceTo>CI_Instance__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Jenkins_Job__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Job__c</fullName>
    <label>Jenkins Job</label>
    <referenceTo>Jenkins_Job__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <description>The url of the build package sent to jenkins</description>
    <inlineHelpText>The url of the build package sent to jenkins</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
                <default>true</default>
                <label>NEW</label>
            </value>
            <value>
                <fullName>IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>Creating SF Build Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Status_Details__c.field-meta.xml
<CustomField>
    <fullName>Status_Details__c</fullName>
    <label>Status Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/Jenkins_Job__c.object-meta.xml
<CustomObject>
    <description>Represents a job on a Jenkins CI build server.</description>
    <label>Jenkins Job</label>
    <nameField>
        <label>Jenkins Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jenkins Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/CI_Instance__c.field-meta.xml
<CustomField>
    <fullName>CI_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The target instance for this Job</inlineHelpText>
    <label>CI Instance</label>
    <referenceTo>CI_Instance__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Represents a relative URL path to a job on a Jenkins CI build server.</description>
    <label>Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents a Sightline release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Source_Repository__c.field-meta.xml
<CustomField>
    <fullName>Source_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds2</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/JenkinsJobExt.cls
public with sharing class JenkinsJobExt {

    /**
    * Initializes a Jenkins job run.
    * @param sc: The Jenkins_Job__c standard controller.
    */
    public JenkinsJobExt(ApexPages.StandardController sc) {
        PermissionServices.checkPagePermissions(new JenkinsJobPermissions());
    }

    @AuraEnabled
    public static String createJenkinsBuild(String jenkinsJobId, String previousSuccessfulBuildId) {
        try {
            return JenkinsServices.setupBuildRecords(jenkinsJobId, previousSuccessfulBuildId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static PageMessage startJob(String buildId) {
        try {
            List<Jenkins_Build__c> jenkinsBuilds = [SELECT Jenkins_Job__r.Release__c, Jenkins_Job__r.Path__c,
                                                        Jenkins_Job__r.CI_Instance__c, Jenkins_Job__r.Id,
                                                        Jenkins_Job__r.Source_Repository__c, Jenkins_Job__r.Name,
                                                        Name, Status_Details__c, Package_URL__c
                                                    FROM Jenkins_Build__c WHERE Id = :buildId];

            if (jenkinsBuilds.isEmpty()) {
                return new PageMessage(ApexPages.Severity.ERROR,
                                System.Label.Failure_Starting_Jenkins_Job + ' Unable to find build record.');
            }

	        Jenkins_Build__c jBuild = jenkinsBuilds[0];
            PageMessage response;
            if (String.isNotBlank(jBuild.Package_URL__C)) {
                JenkinsServices.deployBuildPackage(jBuild.Id);
                response = makeJobStartedMessage(jBuild.Jenkins_Job__r.Name, jBuild.Name);
            } else if (jBuild.Jenkins_Job__r.Source_Repository__c != null) {
                jBuild = JenkinsServices.startAssemblerJob(jBuild.Id);
                response = (jBuild.Status__c == JenkinsServices.JENKINS_SF_BUILD_IN_PROGRESS_STATUS) ?
                                makeJobStartedMessage(jBuild.Jenkins_Job__r.Name, jBuild.Name) :
                                new PageMessage(ApexPages.Severity.ERROR, System.Label.Failure_Starting_Jenkins_Job
                                                                         + ' ' + jBuild.Status_Details__c);
            } else {
                response = new PageMessage(ApexPages.Severity.ERROR, System.Label.Jenkins_Build_Error_No_Repo_Or_Reused_Build);
            }
            return response;

        } catch (Exception e) {
            JenkinsServices.updateJenkinsBuildStatus(new Jenkins_Build__c(Id=buildId),
                                                     JenkinsServices.JENKINS_BUILD_FAILURE_STATUS);
            return new PageMessage(ApexPages.Severity.ERROR,
                            System.Label.Failure_Starting_Jenkins_Job + '  ' + e.getMessage());
        }
    }

    private static PageMessage makeJobStartedMessage(String jobName, String jenkinsBuildName) {
        String message = 'Jenkins job \'' + jobName + '\' has started build ' + jenkinsBuildName + '.';
        return new PageMessage(ApexPages.Severity.INFO, message);
    }

    /**
    * Grabs all the successful Jenkins builds from the given Release.
    * @param releaseId: Id of the Release__c record
    * @return List<JenkinsBuild>: A list of JenkinsBuild objects.
    */
    @AuraEnabled
    public static List<JenkinsBuild> getExistingSuccessfulBuildsForRelease(String releaseId) {
        List<Jenkins_Build__c> successfulJenkinsBuilds =
            [SELECT Id, Name, CI_Instance__r.Name, Jenkins_Job__c, Jenkins_Job__r.Name, Jenkins_Job__r.Release__c,
                    Package_URL__c
             FROM Jenkins_Build__c
             WHERE Status__c=:'SUCCESS' AND Jenkins_Job__r.Release__c=:releaseId AND Package_URL__c != null
             ORDER BY CreatedDate DESC];

        List<JenkinsBuild> successfulBuilds = new List<JenkinsBuild>();
        for (Jenkins_Build__c build : successfulJenkinsBuilds) {
            successfulBuilds.add(new JenkinsBuild(build));
        }

        return successfulBuilds;
    }

    @AuraEnabled
    public static List<BuildRuleCriterion> getBuildRuleCriteria(String jenkinsJobId) {
        Jenkins_Job__c existingJob = JenkinsServices.getExistingJob(jenkinsJobId);

        Map<String, Schema.SObjectField> fieldMap = CI_Instance__c.SObjectType.getDescribe().fields.getMap();

        Map<String, Boolean> criteriaEvaluation = JenkinsServices.getBuildRuleCriteriaEvaluations(existingJob);
        List<BuildRuleCriterion> criteria = new List<BuildRuleCriterion>();
        List<String> sortedCriteriaValues = new List<String>(criteriaEvaluation.keySet());
        sortedCriteriaValues.sort();
        for (String fieldName : sortedCriteriaValues) {
            if (fieldMap.containsKey(fieldName)) {
                String label = fieldMap.get(fieldName).getDescribe().getLabel();
                criteria.add( new BuildRuleCriterion(label + ' (' + fieldName + ')', criteriaEvaluation.get(fieldName)) );
            }

        }

        return criteria;
    }

    public class BuildRuleCriterion {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public Boolean value;

        public BuildRuleCriterion(String label, Boolean value) {
            this.label = label;
            this.value = value;
        }
    }

    public class JenkinsBuild {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String ciInstanceName;
        @AuraEnabled
        public String jobName;
        public String releaseId;

        public JenkinsBuild(Jenkins_Build__c jenkinsBuild) {
            id = jenkinsBuild.Id;
            name = jenkinsBuild.Name;
            ciInstanceName = jenkinsBuild.CI_Instance__r.Name;
            jobName = jenkinsBuild.Jenkins_Job__r.Name;
            releaseId = jenkinsBuild.Jenkins_Job__r.Release__c;
        }
    }
}