mywork/force-app/main/default/objects/SSH_Keypair__c/SSH_Keypair__c.object-meta.xml
<CustomObject>
    <fullName>SSH_Keypair__c</fullName>
    <label>SSH Keypair</label>
    <nameField>
        <label>SSH Keypair Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SSH Keypairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/SSH_Keypair__c/fields/Passphrase__c.field-meta.xml
<CustomField>
    <fullName>Passphrase__c</fullName>
    <description>A passphrase used to encrypt/decrypt SSH keys.</description>
    <inlineHelpText>A passphrase used to encrypt/decrypt SSH keys.</inlineHelpText>
    <label>Passphrase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/SSH_Keypair__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <description>An encrypted SSH private key.</description>
    <inlineHelpText>An encrypted SSH private key.</inlineHelpText>
    <label>Private Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/SSH_Keypair__c/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <description>An encrypted SSH public key.</description>
    <inlineHelpText>An encrypted SSH public key.</inlineHelpText>
    <label>Public Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/classes/SSHPermissions.cls
public with sharing class SSHPermissions implements ApplicationPermissions {
    public static final Map<String, Schema.DescribeSObjectResult> OBJECTS_TO_DESCRIBE = new Map<String, Schema.DescribeSObjectResult> {
        SObjectServices.getFullyQualifiedName('SSH_Keypair__c') => SSH_Keypair__c.sObjectType.getDescribe()
    };

    public static final List<String> SSH_KEYPAIR_FIELDS = new List<String>{
        SObjectServices.getFullyQualifiedName('Passphrase__c'),
        SObjectServices.getFullyQualifiedName('Private_Key__c'),
        SObjectServices.getFullyQualifiedName('Public_Key__c')
    };

    public static Map<String, List<String>> OBJECT_TO_FIELDS = new Map<String, List<String>>{
        SObjectServices.getFullyQualifiedName('SSH_Keypair__c') => SSH_KEYPAIR_FIELDS
    };

    public PermissionServices.PermissionLevel hasPermission() {
        PermissionServices.PermissionLevel permissionsLevel = PermissionServices.PermissionLevel.NONE;

        if (hasObjectPermissions() && hasRecordTypePermissions() && hasFLSPermissions()) {
            permissionsLevel = PermissionServices.PermissionLevel.FULL;
        }

        return permissionsLevel;
    }

    public Boolean hasFLSPermissions() {
        return PermissionServices.hasFLSFullPermissions(OBJECTS_TO_DESCRIBE, OBJECT_TO_FIELDS);
    }

    public Boolean hasObjectPermissions(){
        return PermissionServices.hasObjectFullPermissions(OBJECTS_TO_DESCRIBE);
    }

    public Boolean hasRecordTypePermissions(){
        return true;
    }
}