mywork/force-app/main/default/objects/Backlog_Auto_Prioritization__c/Backlog_Auto_Prioritization__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Backlog Auto-Prioritization</label>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Auto_Prioritization__c/fields/Backlog_ID__c.field-meta.xml
<CustomField>
    <fullName>Backlog_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Backlog ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Auto_Prioritization__c/fields/Prioritization_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Prioritization_Behavior__c</fullName>
    <label>Prioritization Behavior</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/BacklogAutoPrioritizationModel.cls
public with sharing class BacklogAutoPrioritizationModel {
    public enum PrioritizationBehavior {
        OFF,
        TOP,
        BOTTOM
    }

    public Id backlogId;
    public PrioritizationBehavior behavior {
        get;
        set {
            this.behavior = value != null ? value : getDefaultPrioritizationBehavior();
        }
    }
    public void setBehavior(String behavior) {
        this.behavior = convertPrioritizationBehaviorStringToEnum(behavior);
    }

    public BacklogAutoPrioritizationModel() {
        this.backlogId = BacklogItemServices.UNIVERSAL_BACKLOG_ID;
        this.behavior = null;
    }

    public BacklogAutoPrioritizationModel(Id backlogId) {
        this.backlogId = backlogId;
        this.behavior = null;
    }

    public BacklogAutoPrioritizationModel(PrioritizationBehavior behavior) {
        this.backlogId = BacklogItemServices.UNIVERSAL_BACKLOG_ID;
        this.behavior = behavior;
    }

    public BacklogAutoPrioritizationModel(Id backlogId, PrioritizationBehavior behavior) {
        this.backlogId = backlogId;
        this.behavior = behavior;
    }

    public BacklogAutoPrioritizationModel(Id backlogId, String behavior) {
        this.backlogId = backlogId;
        this.behavior = convertPrioritizationBehaviorStringToEnum(behavior);
    }

    public BacklogAutoPrioritizationModel(Backlog_Auto_Prioritization__c backlogAutoPrioritizationConfiguration) {
        this(backlogAutoPrioritizationConfiguration.Backlog_ID__c, backlogAutoPrioritizationConfiguration.Prioritization_Behavior__c);
    }

    public Backlog_Auto_Prioritization__c getRecord() {
        return new Backlog_Auto_Prioritization__c(
            Name = (this.backlogId == BacklogItemServices.UNIVERSAL_BACKLOG_ID ? 'Universal' : 'Custom_' + this.backlogId),
            Backlog_ID__c = this.backlogId,
            Prioritization_Behavior__c = this.behavior.name()
        );
    }

    public static PrioritizationBehavior convertPrioritizationBehaviorStringToEnum(String behavior) {
        for (PrioritizationBehavior prioritizationBehavior : PrioritizationBehavior.values()) {
            if (prioritizationBehavior.name().equalsIgnoreCase(behavior)) {
                return prioritizationBehavior;
            }
        }

        return null;
    }

    public static PrioritizationBehavior getDefaultPrioritizationBehavior() {
        return PrioritizationBehavior.values()[0];
    }
}