mywork/force-app/main/default/objects/ALM_Error__c/ALM_Error__c.object-meta.xml
<CustomObject>
    <label>ALM Error</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>ALM Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Deployment_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Attempt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Attempt</label>
    <referenceTo>Deployment_Attempt__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/classes/SlingshotPermissions.cls
public with sharing class SlingshotPermissions implements ApplicationPermissions {

    public static final Map<String, Schema.DescribeSObjectResult> OBJECTS_TO_DESCRIBE = new Map<String, Schema.DescribeSObjectResult> {
        SObjectServices.getFullyQualifiedName('ALM_Error__c') => ALM_Error__c.sObjectType.getDescribe(),
        'Attachment' => Attachment.sObjectType.getDescribe(),
        SObjectServices.getFullyQualifiedName('Build__c') => Build__c.sObjectType.getDescribe(),
        SObjectServices.getFullyQualifiedName('Deployment_Attempt__c') => Deployment_Attempt__c.sObjectType.getDescribe()
    };

    public static Map<String, List<String>> OBJECT_TO_FIELDS = new Map<String, List<String>>{
        SObjectServices.getFullyQualifiedName('ALM_Error__c') => PermissionServices.ALM_ERROR_FIELDS,
        'Attachment' => PermissionServices.ATTACHMENT_FIELDS,
        SObjectServices.getFullyQualifiedName('Build__c') => PermissionServices.BUILD_FIELDS,
        SObjectServices.getFullyQualifiedName('Deployment_Attempt__c') => PermissionServices.DEPLOYMENT_ATTEMPT_FIELDS
    };



    public PermissionServices.PermissionLevel hasPermission() {
        PermissionServices.PermissionLevel permissionsLevel = PermissionServices.PermissionLevel.NONE;

        if (hasObjectPermissions() && hasRecordTypePermissions() && hasFLSPermissions()) {
            permissionsLevel = PermissionServices.PermissionLevel.FULL;
        }

        return permissionsLevel;
    }

    public Boolean hasFLSPermissions() {
        return PermissionServices.hasFLSFullPermissions(OBJECTS_TO_DESCRIBE, OBJECT_TO_FIELDS);
    }

    public Boolean hasObjectPermissions(){
        return PermissionServices.hasObjectFullPermissions(OBJECTS_TO_DESCRIBE);
    }

    public Boolean hasRecordTypePermissions(){
        return PermissionServices.hasRecordTypePermissions();
    }
}