mywork/force-app/main/default/objects/ALM_Error__c/ALM_Error__c.object-meta.xml
<CustomObject>
    <label>ALM Error</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>ALM Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Changed__c.field-meta.xml
<CustomField>
    <fullName>Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Changed</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Deployment_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Attempt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Attempt</label>
    <referenceTo>Deployment_Attempt__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>10</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Missing Related Component</fullName>
            </value>
            <value>
                <fullName>Component Not Found</fullName>
            </value>
            <value>
                <fullName>Component Name Changed</fullName>
            </value>
            <value>
                <fullName>Unsupported Component Type</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Error_Location__c.field-meta.xml
<CustomField>
    <fullName>Error_Location__c</fullName>
    <label>Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <label>Parent Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assembler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <inlineHelpText>Link to download the build package</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Deployed__c</fullName>
    <label>Number Components Deployed</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Errors__c</fullName>
    <label>Number Components Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Components_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Components_Total__c</fullName>
    <label>Number Components Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Test_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Test_Errors__c</fullName>
    <label>Number Test Errors</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Tests_Completed__c.field-meta.xml
<CustomField>
    <fullName>Number_Tests_Completed__c</fullName>
    <label>Number Tests Completed</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Number_Tests_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_Tests_Total__c</fullName>
    <label>Number Tests Total</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/State_Detail__c.field-meta.xml
<CustomField>
    <fullName>State_Detail__c</fullName>
    <label>State Detail</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Total_Code_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Total_Code_Coverage__c</fullName>
    <label>Total Code Coverage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Total_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines__c</fullName>
    <label>Total Lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Total_Lines_Not_Covered__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines_Not_Covered__c</fullName>
    <label>Total Lines Not Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/classes/PermissionServices.cls
public with sharing class PermissionServices {
    public enum PermissionLevel {
        NONE,
        READ_ONLY,
        FULL
    }

    public static final List<String> ALM_ERROR_FIELDS = new List<String>{
         SObjectServices.getFullyQualifiedName('Build__c'),
         SObjectServices.getFullyQualifiedName('Changed__c'),
         SObjectServices.getFullyQualifiedName('Class__c'),
         SObjectServices.getFullyQualifiedName('Component_Name__c'),
         SObjectServices.getFullyQualifiedName('Component_Type__c'),
         SObjectServices.getFullyQualifiedName('Deleted__c'),
         SObjectServices.getFullyQualifiedName('Deployment_Attempt__c'),
         SObjectServices.getFullyQualifiedName('Description__c'),
         SObjectServices.getFullyQualifiedName('Duration__c'),
         SObjectServices.getFullyQualifiedName('Error_Cause__c'),
         SObjectServices.getFullyQualifiedName('Error_Location__c'),
         SObjectServices.getFullyQualifiedName('Error_Message__c'),
         SObjectServices.getFullyQualifiedName('Method__c'),
         SObjectServices.getFullyQualifiedName('Parent_Component__c'),
         'RecordTypeId',
         SObjectServices.getFullyQualifiedName('Stack_Trace__c'),
         SObjectServices.getFullyQualifiedName('Tool__c'),
         SObjectServices.getFullyQualifiedName('Type__c')
    };

    public static final List<String> ATTACHMENT_FIELDS = new List<String>{
        'Body',
        'Name',
        'ParentId'
    };

    public static final List<String> BACKLOG_COMPONENT_FIELDS = new List<String>{
        SObjectServices.getFullyQualifiedName('Deploy_Manually__c'),
        SObjectServices.getFullyQualifiedName('Notes__c'),
        SObjectServices.getFullyQualifiedName('Profile__c'),
        SObjectServices.getFullyQualifiedName('Profile_Data_1__c'),
        SObjectServices.getFullyQualifiedName('Profile_Data_2__c'),
        SObjectServices.getFullyQualifiedName('Profile_Permission__c'),
        SObjectServices.getFullyQualifiedName('Source_Instance__c'),
        SObjectServices.getFullyQualifiedName('Source_Sandbox__c')
    };

    public static final List<String> BUILD_FIELDS = new List<String>{
        SObjectServices.getFullyQualifiedName('Package_URL__c'),
        SObjectServices.getFullyQualifiedName('Status__c')
    };

    public static final List<String> DEPLOYMENT_ATTEMPT_FIELDS = new List<String>{
         SObjectServices.getFullyQualifiedName('End_Date__c'),
         SObjectServices.getFullyQualifiedName('Number_Components_Deployed__c'),
         SObjectServices.getFullyQualifiedName('Number_Components_Errors__c'),
         SObjectServices.getFullyQualifiedName('Number_Components_Total__c'),
         SObjectServices.getFullyQualifiedName('Number_Test_Errors__c'),
         SObjectServices.getFullyQualifiedName('Number_Tests_Completed__c'),
         SObjectServices.getFullyQualifiedName('Number_Tests_Total__c'),
         SObjectServices.getFullyQualifiedName('Start_Date__c'),
         SObjectServices.getFullyQualifiedName('State_Detail__c'),
         SObjectServices.getFullyQualifiedName('Status__c'),
         SObjectServices.getFullyQualifiedName('Total_Code_Coverage__c'),
         SObjectServices.getFullyQualifiedName('Total_Lines__c'),
         SObjectServices.getFullyQualifiedName('Total_Lines_Not_Covered__c'),
         SObjectServices.getFullyQualifiedName('UUID__c')
    };

    /**
    * Checks to see if permissions exist for an application. A page message will be added, if the
    * user doesn't have permission
    * @param appPermissions     The permissions instance for the current application
    * @return PermissionServices.PermissionLevel   The level of permissions that the user has for the application
    */
    public static PermissionServices.PermissionLevel checkPagePermissions(ApplicationPermissions appPermissions) {
        PermissionServices.PermissionLevel permissionsLevel = appPermissions.hasPermission();
        if (permissionsLevel == PermissionServices.PermissionLevel.NONE) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR,
                System.Label.Permissions_Error
            ));
        }
        return permissionsLevel;
    }


    /**
    * Determines if the current user has full permission to the given objects
    * @param objectToDescribeMap    The map of object describe info to validate permissions against. Map of the form {"Object Name" => Schema.DescribeSObjectResult}
    */
    public static Boolean hasObjectFullPermissions(Map<String, Schema.DescribeSObjectResult> objectToDescribeMap) {
      for (String objectName : objectToDescribeMap.keySet()) {
            Schema.DescribeSObjectResult describe = objectToDescribeMap.get(objectName);

            if (!(describe.isAccessible() && describe.isCreateable() && describe.isUpdateable() && describe.isDeletable())) {
                return false;
            }
      }

      return true;
    }

    /**
    * Determines if the current user has read-only permission to the given objects
    * @param objectToDescribeMap    The map of object describe info to validate permissions against. Map of the form {"Object Name" => Schema.DescribeSObjectResult}
    */
    public static Boolean hasObjectReadPermissions(Map<String, Schema.DescribeSObjectResult> objectToDescribeMap) {
      for (String objectName : objectToDescribeMap.keySet()) {
            Schema.DescribeSObjectResult describe = objectToDescribeMap.get(objectName);

            if (!describe.isAccessible()) {
                return false;
            }
      }

      return true;
    }

    public static Boolean hasRecordTypePermissions() {
        Schema.DescribeSObjectResult describe = ALM_Error__c.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> infos = describe.getRecordTypeInfos();

        for (Schema.RecordTypeInfo info : infos) {
            if (!info.isAvailable()) {
                return false;
            }
        }

        return true;
    }

    /**
    * Determines if the current user has full FLS access to the given objects and fields
    * @param objectToDescribeMap    The map of object describe info to validate permissions against. Map of the form {"Object Name" => Schema.DescribeSObjectResult}
    * @param objectToFieldsMap      The map of fields to validate. Map of the form {"Object Name" => [fields]}
    */
    public static Boolean hasFLSFullPermissions(Map<String, Schema.DescribeSObjectResult> objectToDescribeMap, Map<String, List<String>> objectToFieldsMap) {
        return hasFLSPermissions(objectToDescribeMap, objectToFieldsMap, PermissionLevel.FULL);
    }

    /**
    * Determines if the current user has read-only FLS access to the given objects and fields
    * @param objectToDescribeMap    The map of object describe info to validate permissions against. Map of the form {"Object Name" => Schema.DescribeSObjectResult}
    * @param objectToFieldsMap      The map of fields to validate. Map of the form {"Object Name" => [fields]}
    */
    public static Boolean hasFLSReadPermissions(Map<String, Schema.DescribeSObjectResult> objectToDescribeMap, Map<String, List<String>> objectToFieldsMap) {
        return hasFLSPermissions(objectToDescribeMap, objectToFieldsMap, PermissionLevel.READ_ONLY);
    }

    /**
    * Determines if the current user has FLS access to the given objects and fields
    * @param objectToDescribeMap    The map of object describe info to validate permissions against. Map of the form {"Object Name" => Schema.DescribeSObjectResult}
    * @param objectToFieldsMap      The map of fields to validate. Map of the form {"Object Name" => [fields]}
    * @param permissionsLevel       The level of permissions required of the given objects and fields
    */
    public static Boolean hasFLSPermissions(Map<String, Schema.DescribeSObjectResult> objectToDescribeMap, Map<String, List<String>> objectToFieldsMap, PermissionLevel permissionsLevel) {
        for (String objectName : objectToFieldsMap.keySet()) {
            Schema.DescribeSObjectResult describe = objectToDescribeMap.get(objectName);
            Map<String,Schema.SObjectField> dfMap = describe.fields.getMap();

            List<String> fieldsToVerify = objectToFieldsMap.get(objectName);
            for (String fieldName : fieldsToVerify) {
                Schema.DescribeFieldResult dfr = dfMap.get(fieldName).getDescribe();

                if (permissionsLevel == PermissionLevel.FULL &&
                        !(dfr.isAccessible() &&
                            dfr.isCreateable() &&
                                (fieldName.equals('ParentId') ? true : dfr.isUpdateable()))) {
                    return false;
                } else if (permissionsLevel == PermissionLevel.READ_ONLY && !dfr.isAccessible()) {
                    return false;
                }
            }
        }

        return true;
    }
}