mywork/force-app/main/default/objects/ALM_Error__c/ALM_Error__c.object-meta.xml
<CustomObject>
    <label>ALM Error</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>ALM Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ALM Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Deployment_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Attempt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Attempt</label>
    <referenceTo>Deployment_Attempt__c</referenceTo>
    <relationshipLabel>ALM Errors</relationshipLabel>
    <relationshipName>ALM_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/ALM_Error__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <description>Errors generated from Assembler</description>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Build__c/Build__c.object-meta.xml
<CustomObject>
    <label>Build</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build__c/fields/Jenkins_Build__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jenkins Build</label>
    <referenceTo>Jenkins_Build__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <inlineHelpText>Link to download the build package</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Builds</relationshipLabel>
    <relationshipName>Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <description>Represents an overall deployment of metadata components.</description>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest build for this deployment</description>
    <inlineHelpText>The latest build for this deployment</inlineHelpText>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Completed_Build__c.field-meta.xml
<CustomField>
    <fullName>Completed_Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Completed Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipLabel>Deployments (Completed Build)</relationshipLabel>
    <relationshipName>Deployments1</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Deployment_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Attempt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Attempt</label>
    <referenceTo>Deployment_Attempt__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Deployments</relationshipLabel>
    <relationshipName>Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/Deployment_Attempt__c.object-meta.xml
<CustomObject>
    <label>Deployment Attempt</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deployment Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Build__c.field-meta.xml
<CustomField>
    <fullName>Build__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build</label>
    <referenceTo>Build__c</referenceTo>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Deployment Attempts</relationshipLabel>
    <relationshipName>Deployment_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Deployment_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/Jenkins_Build__c.object-meta.xml
<CustomObject>
    <label>Jenkins Build</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jenkins Build Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jenkins Builds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Jenkins_Job__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Job__c</fullName>
    <label>Jenkins Job</label>
    <referenceTo>Jenkins_Job__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Package_URL__c.field-meta.xml
<CustomField>
    <fullName>Package_URL__c</fullName>
    <description>The url of the build package sent to jenkins</description>
    <inlineHelpText>The url of the build package sent to jenkins</inlineHelpText>
    <label>Package URL</label>
    <type>Url</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
                <default>true</default>
                <label>NEW</label>
            </value>
            <value>
                <fullName>IN PROGRESS</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>FAILURE</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>Creating SF Build Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Status_Details__c.field-meta.xml
<CustomField>
    <fullName>Status_Details__c</fullName>
    <label>Status Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/Jenkins_Job__c.object-meta.xml
<CustomObject>
    <description>Represents a job on a Jenkins CI build server.</description>
    <label>Jenkins Job</label>
    <nameField>
        <label>Jenkins Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jenkins Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Ignore_Build_Errors__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Build_Errors__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Build Errors</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents a Sightline release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/classes/TestBuildServices.cls
@isTest
private class TestBuildServices {

    private static Release__c release;

    private static void setup() {
        release = new Release__c(Name='Test release');
        insert release;
    }

    static testMethod void getNewlyFinishedBuilds() {
    	setup();

    	Build__c newBuild1 = TestingUtils.createBuild(release.Id, BuildServices.STATUS_IN_PROGRESS);
    	Build__c newBuild2 = TestingUtils.createBuild(release.Id, BuildServices.STATUS_IN_PROGRESS);

    	Map<Id, Build__c> oldMap = new Map<Id, Build__c>{ newBuild1.Id => newBuild1, newBuild2.Id => newBuild2 };

    	Build__c updatedBuild1 = newBuild1.clone(true, true);
    	updatedBuild1.Status__c = BuildServices.STATUS_SUCCESS;

    	Build__c updatedBuild2 = newBuild2.clone(true, true);
    	updatedBuild2.Status__c = BuildServices.STATUS_FAILURE;

        List<Build__c> newBuilds = new List<Build__c> {updatedBuild1, updatedBuild2};

        Test.startTest();

        	List<Build__c> finishedBuilds = BuildServices.getNewlyFinishedBuilds(oldMap, newBuilds);

        Test.stopTest();

        System.assertEquals(2, finishedBuilds.size(), 'All newly finished builds should be returned');
        System.assertEquals(updatedBuild1.Id, finishedBuilds[0].Id, 'Builds with an updated status of success should be returned');
        System.assertEquals(updatedBuild2.Id, finishedBuilds[1].Id, 'Builds with an updated status of failure should be returned');
    }

    static testMethod void getNewlyFinishedBuilds_noneFinished() {
    	setup();

    	Build__c newBuild1 = TestingUtils.createBuild(release.Id, BuildServices.STATUS_IN_PROGRESS);
    	Build__c newBuild2 = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);
        List<Build__c> newBuilds = new List<Build__c> {newBuild1, newBuild2};

    	Map<Id, Build__c> oldMap = new Map<Id, Build__c>(newBuilds);

        Test.startTest();

        	List<Build__c> finishedBuilds = BuildServices.getNewlyFinishedBuilds(oldMap, newBuilds);

        Test.stopTest();

        System.assertEquals(0, finishedBuilds.size(), 'Only newly finished builds should be returned');
    }

    static testMethod void getDeploymentAttemptsToStart_NoDeployment() {
    	setup();

    	Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

    	Test.startTest();

    	   Set<Id> attemptsToStart = BuildServices.getDeploymentAttemptsToStart(new List<Build__c>{build});

    	Test.stopTest();

    	System.assertEquals(0, attemptsToStart.size(), 'Only builds that are currently on a deployment are deployable');
    }

    static testMethod void getDeploymentAttemptsToStart_deploymentInProgress() {
    	setup();

    	Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

    	Deployment_Attempt__c attempt = new Deployment_Attempt__c(Build__c = build.Id, Status__c = DeploymentServices.STATUS_IN_PROGRESS);
    	insert attempt;

    	Deployment__c deployment = new Deployment__c(Name='Background Build');
    	deployment.Build__c = build.Id;
    	deployment.Deployment_Attempt__c = attempt.Id;
    	insert deployment;

    	Test.startTest();

    	   Set<Id> attemptsToStart = BuildServices.getDeploymentAttemptsToStart(new List<Build__c>{build});

    	Test.stopTest();

    	System.assertEquals(0, attemptsToStart.size(), 'Only deployment attempts that are not started are deployable');
    }

    static testMethod void getDeploymentAttemptsToStart() {
    	setup();

    	Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

    	Deployment_Attempt__c attempt = new Deployment_Attempt__c(Build__c = build.Id, Status__c = DeploymentServices.STATUS_NOT_STARTED);
    	insert attempt;

    	Deployment__c deployment = new Deployment__c(Name='Background Build');
    	deployment.Build__c = build.Id;
    	deployment.Deployment_Attempt__c = attempt.Id;
    	insert deployment;

    	Test.startTest();

    	   Set<Id> attemptsToStart = BuildServices.getDeploymentAttemptsToStart(new List<Build__c>{build});

    	Test.stopTest();

    	System.assertEquals(1, attemptsToStart.size(), 'Deployment attempts that have a deployment and are not started are deployable');
    	System.assert(attemptsToStart.contains(attempt.Id), 'The deployment attempt for the completed build should be returned');
    }

    static testMethod void updateDeploymentWithCompletedBuild() {
        setup();

        Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

        Deployment__c deployment = new Deployment__c(Name='Background Build');
        deployment.Build__c = build.Id;
        insert deployment;

        Test.startTest();

            BuildServices.updateDeploymentWithCompletedBuild( new List<Build__c>{ build } );

        Test.stopTest();

        Deployment__c updatedDeployment = [SELECT Id, Completed_Build__c FROM Deployment__c];

        System.assertEquals(build.Id, updatedDeployment.Completed_Build__c, 'The deployment should be updated with the completed build');
    }

    static testMethod void updateDeploymentWithCompletedBuild_noDeployment() {
        setup();

        Build__c build = TestingUtils.createBuild(release.Id, BuildServices.STATUS_SUCCESS);

        Deployment__c deployment = new Deployment__c(Name='Background Build');
        insert deployment;

        Test.startTest();

            BuildServices.updateDeploymentWithCompletedBuild( new List<Build__c>{ build } );

        Test.stopTest();

        Deployment__c updatedDeployment = [SELECT Id, Completed_Build__c FROM Deployment__c];

        System.assertEquals(null, updatedDeployment.Completed_Build__c, 'The deployment should be unchanged');
    }

    static testMethod void updateDeploymentWithCompletedBuild_JenkinsDeployment() {
        // TODO: throws null pointer when false. Investigate
        Boolean createRepo = true;
        TestingUtils.JenkinsJobSetup setup = new TestingUtils.JenkinsJobSetup(createRepo, 'testingBuildTrigger');
        Id jBuildId = JenkinsServices.setupBuildRecords(setup.jenkinsJob.Id, '');
        Jenkins_Build__c jBuild = JenkinsServices.getJenkinsBuild(jBuildId);
        Build__c build = jBuild.Builds__r[0];

        TestingUtils.MockJenkinsBuildPackage buildPackage =
            new TestingUtils.MockJenkinsBuildPackage('testPackageContent', build.Id);

        Test.setMock(HttpCalloutMock.class, new MockWebAssemblerAPI(MockWebAssemblerAPI.JENKINS_DEPLOY_ACTION));

        Test.startTest();
            update new Build__c(Id=build.Id, Status__c = BuildServices.STATUS_SUCCESS);
        Test.stopTest();

        jBuild = JenkinsServices.getJenkinsBuild(jBuildId);
        System.assertEquals(JenkinsServices.JENKINS_BUILD_PENDING_STATUS, jBuild.Status__c,
            'The Jenkins Build should have the correct status');
        System.assert(String.isBlank(jBuild.Status_Details__c), 'The Jenkins Build should have empty status details');
        System.assertEquals(jBuild.Builds__r[0].Package_URL__c, jBuild.Package_URL__c, 'The Jenkins Build should have the build package url populated from the build');

        System.assert(ExecuteJenkinsBuildbatchServices.isMonitorBatchScheduledOrRunning(),
            'A Jenkins Monitor Batch should be running or scheduled');
    }

    static testMethod void updateDeploymentWithCompletedBuild_JenkinsDeployment_FailureWithBuildWarnings() {
        // set up build and related objects that will NOT ignore build warnings
        Jenkins_Job__c jJob = TestingUtils.createJenkinsJob();
        jJob.Ignore_Build_Errors__c = false;
        update jJob;

        Jenkins_Build__c jBuild = new Jenkins_Build__c(Jenkins_Job__c=jJob.Id);
        insert jBuild;

        Build__c build = new Build__c(Jenkins_Build__c=jBuild.Id, Status__c=BuildServices.STATUS_PENDING);
        insert build;

        ALM_Error__c buildError = TestingUtils.buildAssemblerBuildError(build.Id);
        insert buildError;

        Test.startTest();
            try {
                build.Status__c = BuildServices.STATUS_SUCCESS;
                update build;
            } catch (Exception e) {
                System.assert(false, 'No exception should have been thrown');
            }
        Test.stopTest();

        jBuild = [SELECT Id, Status__c, Status_Details__c from Jenkins_Build__c WHERE Id =: jBuild.Id];
        System.assertEquals(jenkinsServices.JENKINS_BUILD_FAILURE_STATUS, jBuild.Status__c,
                            'The Status on the Jenkins Build should be correct');
        System.assertEquals(System.Label.Jenkins_Build_Assembler_Failure_Errors_Not_Ignored, jBuild.Status_Details__c,
                            'The Status Details on the Jenkins Build should be correct');
    }

    static testMethod void updateDeploymentWithCompletedBuild_JenkinsDeployment_SuccessWithBuildWarnings() {
        // set up build and related objects that WILL ignore build warnings
        Boolean createRepo = true;
        TestingUtils.JenkinsJobSetup setup = new TestingUtils.JenkinsJobSetup(createRepo, 'testingBuildTrigger');

        setup.jenkinsJob.Ignore_Build_Errors__c = true;
        update setup.jenkinsJob;

        Jenkins_Build__c jBuild = new Jenkins_Build__c(Jenkins_Job__c=setup.jenkinsJob.Id);
        insert jBuild;

        Build__c build = new Build__c(Jenkins_Build__c=jBuild.Id, Status__c=BuildServices.STATUS_PENDING);
        insert build;

        ALM_Error__c buildError = TestingUtils.buildAssemblerBuildError(build.Id);
        insert buildError;

        TestingUtils.MockJenkinsBuildPackage buildPackage =
            new TestingUtils.MockJenkinsBuildPackage('testPackageContent', build.Id);

        Test.setMock(HttpCalloutMock.class, new MockWebAssemblerAPI(MockWebAssemblerAPI.JENKINS_DEPLOY_ACTION));

        Test.startTest();
            try {
                build.Status__c = BuildServices.STATUS_SUCCESS;
                update build;
            } catch (Exception e) {
                System.assert(false, 'No exception should have been thrown');
            }
        Test.stopTest();

        jBuild = [SELECT Id, Status__c, Status_Details__c from Jenkins_Build__c WHERE Id =: jBuild.Id];
        System.assertEquals(jenkinsServices.JENKINS_BUILD_PENDING_STATUS, jBuild.Status__c,
                            'The Status on the Jenkins Build should be correct');
        System.assertEquals(System.Label.Jenkins_Build_Assembler_Warning_Errors_Ignored, jBuild.Status_Details__c,
                            'The Status Details on the Jenkins Build should be correct');
    }


    static testMethod void getMostRecentBuildPackage() {
        Build__c build = new Build__c();
        insert build;

        Attachment oldestBuildPackage = new TestingUtils.MockJenkinsBuildPackage('p2', build.Id, Datetime.now().addDays(-1)).buildPackage;
        Attachment newestBuildPackage = new TestingUtils.MockJenkinsBuildPackage('p1', build.Id, Datetime.now()).buildPackage;
        Attachment targetBackup = new TestingUtils.MockJenkinsBuildPackage('backup', build.Id).buildPackage;
        targetBackup.Name = targetBackup.Name.replace('.zip', '-target.zip');
        update targetBackup;

        Attachment queriedBuildPackage;
        Test.startTest();
            queriedBuildPackage = BuildServices.getLatestBuildPackage(build.Id);
        Test.stopTest();

        System.assertEquals(newestBuildPackage.Id, queriedBuildPackage.Id, 'The newest build package should be returned');
    }
}