mywork/force-app/main/default/objects/Scratch_Org__c/Scratch_Org__c.object-meta.xml
<CustomObject>
    <label>Scratch Org</label>
    <pluralLabel>Scratch Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <label>Scratch Org Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Parent_Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Branch_Name__c</fullName>
    <description>Name of the branch used to create the branch for this scratch org</description>
    <inlineHelpText>Name of the branch used to create the branch for this scratch org</inlineHelpText>
    <label>Parent Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Repository_Location__c.field-meta.xml
<CustomField>
    <fullName>Repository_Location__c</fullName>
    <label>Repository Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Scratch_Org_Definition__c.field-meta.xml
<CustomField>
    <fullName>Scratch_Org_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The scratch org definition used to create this scratch org</description>
    <label>Scratch Org Definition</label>
    <referenceTo>Scratch_Org_Definition__c</referenceTo>
    <relationshipLabel>Scratch Orgs</relationshipLabel>
    <relationshipName>Scratch_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/Scratch_Org_Definition__c.object-meta.xml
<CustomObject>
    <description>Options used when creating a scratch org</description>
    <label>Scratch Org Definition</label>
    <nameField>
        <label>Scratch Org Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>2000-character free-form text field. The description is a good way to document the scratch org’s purpose. You can view or edit the description in the Dev Hub.</inlineHelpText>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Disabled_Org_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Org_Preferences__c</fullName>
    <label>Disabled Org Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supported_Org_Preferences</valueSetName>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Edition__c.field-meta.xml
<CustomField>
    <fullName>Edition__c</fullName>
    <description>edition</description>
    <inlineHelpText>The salesforce edition</inlineHelpText>
    <label>Edition</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Enabled_Org_Preferences__c.field-meta.xml
<CustomField>
    <fullName>Enabled_Org_Preferences__c</fullName>
    <label>Enabled Org Preferences</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supported_Org_Preferences</valueSetName>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <description>features</description>
    <inlineHelpText>The features to enable</inlineHelpText>
    <label>Features</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>AuthorApex</fullName>
            </value>
            <value>
                <fullName>Communities</fullName>
            </value>
            <value>
                <fullName>ContactsToMultipleAccounts</fullName>
            </value>
            <value>
                <fullName>ContractApprovals</fullName>
            </value>
            <value>
                <fullName>CascadeDelete</fullName>
            </value>
            <value>
                <fullName>CustomerSelfService</fullName>
            </value>
            <value>
                <fullName>CustomApps</fullName>
            </value>
            <value>
                <fullName>CustomTabs</fullName>
            </value>
            <value>
                <fullName>DebugApex</fullName>
            </value>
            <value>
                <fullName>DefaultWorkflowUser</fullName>
            </value>
            <value>
                <fullName>ExpandedSourceTracking</fullName>
            </value>
            <value>
                <fullName>ExternalSharing (not available in Group Edition)</fullName>
            </value>
            <value>
                <fullName>ForceComPlatform</fullName>
            </value>
            <value>
                <fullName>MultiCurrency</fullName>
            </value>
            <value>
                <fullName>PersonAccounts</fullName>
            </value>
            <value>
                <fullName>SalesWave</fullName>
            </value>
            <value>
                <fullName>LightningSalesConsole</fullName>
            </value>
            <value>
                <fullName>LightningServiceConsole</fullName>
            </value>
            <value>
                <fullName>ServiceCloud</fullName>
            </value>
            <value>
                <fullName>ServiceWave</fullName>
            </value>
            <value>
                <fullName>SiteDotCom</fullName>
            </value>
            <value>
                <fullName>Sites</fullName>
            </value>
            <value>
                <fullName>StateAndCountryPicklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/fields/Has_Sample_Data__c.field-meta.xml
<CustomField>
    <fullName>Has_Sample_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hasSampleData</description>
    <inlineHelpText>False is the default, which creates an org without sample data.</inlineHelpText>
    <label>Has Sample Data</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/globalValueSets/Supported_Org_Preferences.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AnalyticsSharingEnable</fullName>
    </customValue>
    <customValue>
        <fullName>AsyncSaveEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>ChatterEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>DisableParallelApexTesting</fullName>
    </customValue>
    <customValue>
        <fullName>EnhancedEmailEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>EventLogWaveIntegEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>LoginForensicsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>NetworksEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>NotesReservedPref01</fullName>
    </customValue>
    <customValue>
        <fullName>OfflineDraftsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>PathAssistantsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>S1DesktopEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>S1EncryptedStoragePref2</fullName>
    </customValue>
    <customValue>
        <fullName>S1OfflinePref</fullName>
    </customValue>
    <customValue>
        <fullName>SelfSetPasswordInApi</fullName>
    </customValue>
    <customValue>
        <fullName>SendThroughGmailPref</fullName>
    </customValue>
    <customValue>
        <fullName>SocialProfilesEnable</fullName>
    </customValue>
    <customValue>
        <fullName>Translation</fullName>
    </customValue>
    <customValue>
        <fullName>VoiceEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsAccountTeamsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>ShowViewHierarchyLink</fullName>
    </customValue>
    <customValue>
        <fullName>IsActivityRemindersEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsDragAndDropSchedulingEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsEmailTrackingEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsGroupTasksEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsMultidayEventsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsRecurringEventsEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsRecurringTasksEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsSidebarCalendarShortcutEnabled</fullName>
    </customValue>
    <customValue>
        <fullName>IsSimpleTaskCreateUIEnabled</fullName>
    </customValue>
    <description>Scratch org supported org preferences</description>
    <masterLabel>Supported Org Preferences</masterLabel>
</GlobalValueSet>

mywork/force-app/main/default/classes/TestDXCreateScratchOrgRequest.cls
@isTest
private with sharing class TestDXCreateScratchOrgRequest {

    @isTest static void createScratchOrgDefinitionMap_noTemplateDefined() {
        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(null);
        Test.stopTest();

        System.assertEquals(true, scratchOrgDef.isEmpty(), 
            'an empty map should be returned when no configuration is specified');
    }

    @isTest static void createScratchOrgDefinitionMap_onlyIncludeDefinedFields() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Description__c = 'some description';

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(1, scratchOrgDef.size(), 'Only config options with values should be returned');
        String descriptionKey = DXCreateScratchOrgRequest.SCRATCH_DEF_FIELDS_TO_KEYS.get(
            Schema.Scratch_Org_Definition__c.Description__c);
        System.assertEquals(definitionSObject.Description__c, scratchOrgDef.get(descriptionKey),
             'Only config options with values should be returned');
    }

    @isTest static void createScratchOrgDefinitionMap_hasSampleDataValue() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Has_Sample_Data__c = true;

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(1, scratchOrgDef.size(), 'Only config options with values should be returned');
        String hasSampleDataKey = DXCreateScratchOrgRequest.SCRATCH_DEF_OTHER_FIELDS_MAPPING.get(
            Schema.Scratch_Org_Definition__c.Has_Sample_Data__c);
        System.assertEquals(definitionSObject.Has_Sample_Data__c, scratchOrgDef.get(hasSampleDataKey),
             'The boolean option should only be returned when it is true');
    }
    
    @isTest static void createScratchOrgDefinitionMap_hasSampleDataFalseValue() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Has_Sample_Data__c = false;

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(0, scratchOrgDef.size(), 'The boolean option should only be returned when it is true');
    }


    @isTest static void createScratchOrgDefinitionMap_hasFeatures() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Features__c = 'one;two';

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(1, scratchOrgDef.size(), 'Only config options with values should be returned');
        String featureKey = DXCreateScratchOrgRequest.SCRATCH_DEF_OTHER_FIELDS_MAPPING.get(
            Schema.Scratch_Org_Definition__c.Features__c);
        List<String> features = (List<String>)scratchOrgDef.get(featureKey); 
        System.assertEquals(2, features.size(),
             'The features list should be populated with all selected features');
        System.assertEquals(true, features.contains('one'),
             'The features list should be populated with all selected features');
        System.assertEquals(true, features.contains('two'),
             'The features list should be populated with all selected features');
    }
    
    @isTest static void createScratchOrgDefinitionMap_hasOrgPreferencesEnabled() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Enabled_Org_Preferences__c = 'one;two';

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(1, scratchOrgDef.size(), 'Only config options with values should be returned');
        String enabledKey = DXCreateScratchOrgRequest.SCRATCH_DEF_OTHER_FIELDS_MAPPING.get(
            Schema.Scratch_Org_Definition__c.Enabled_Org_Preferences__c);
        Map<String, List<String>> preferences =
             (Map<String, List<String>>)scratchOrgDef.get(DXCreateScratchOrgRequest.ORG_PREFERENCES); 
        System.assertEquals(2, preferences.size(),
             'The preferences object should be populated with enabled and disabled lists');
        System.assertEquals(true, preferences.containsKey(enabledKey),
             'The preferences object should be populated with enabled list');
        System.assertEquals(2, preferences.get(enabledKey).size(),
             'The enabled preferences list should be populated from the enabled field');
        System.assertEquals(true, preferences.get(enabledKey).contains('one'),
             'The enabled preferences list should be populated from the enabled field');
        System.assertEquals(true, preferences.get(enabledKey).contains('two'),
             'The enabled preferences list should be populated from the enabled field');
    }

    @isTest static void createScratchOrgDefinitionMap_hasOrgPreferencesDisabled() {
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c();
        definitionSObject.Disabled_Org_Preferences__c = 'one;two';

        Test.startTest();
            Map<String, Object> scratchOrgDef = DXCreateScratchOrgRequest.createScratchOrgDefinitionMap(definitionSObject);
        Test.stopTest();

        System.assertEquals(1, scratchOrgDef.size(), 'Only config options with values should be returned');
        String disabledKey = DXCreateScratchOrgRequest.SCRATCH_DEF_OTHER_FIELDS_MAPPING.get(
            Schema.Scratch_Org_Definition__c.Disabled_Org_Preferences__c);
        Map<String, List<String>> preferences = 
            (Map<String, List<String>>)scratchOrgDef.get(DXCreateScratchOrgRequest.ORG_PREFERENCES); 
        System.assertEquals(2, preferences.size(),
             'The preferences object should be populated with enabled and disabled lists');
        System.assertEquals(true, preferences.containsKey(disabledKey),
             'The preferences object should be populated with disabled list');
        System.assertEquals(2, preferences.get(disabledKey).size(),
             'The disabled preferences list should be populated from the disabled field');
        System.assertEquals(true, preferences.get(disabledKey).contains('one'),
             'The disabled preferences list should be populated from the disabled field');
        System.assertEquals(true, preferences.get(disabledKey).contains('two'),
             'The disabled preferences list should be populated from the disabled field');
    }

    @isTest static void isCreatingNewbranch() {
       
        Scratch_Org_Definition__c definitionSObject = new Scratch_Org_Definition__c(
            Edition__c = 'Enterprise'
        );
        insert definitionSObject;

        Scratch_Org__c sOrg = new Scratch_Org__c(
            Parent_Branch_Name__c = 'Parent',
            Repository_Location__c = 'BranchToBeCreated',
            Scratch_Org_Definition__c = definitionSObject.Id
        );

        Scratch_Org__c sOrg2 = new Scratch_Org__c(
            Repository_Location__c = 'BranchToBeCreated',
            Scratch_Org_Definition__c = definitionSObject.Id
        );

        System.assertEquals(true, DXCreateScratchOrgRequest.isCreatingNewBranch(sOrg),
             'When parent branch name is defined, it should be determined that a new branch should be created');
        System.assertEquals(false, DXCreateScratchOrgRequest.isCreatingNewBranch(sOrg2),
             'When parent branch name is not defined, it should be determined that a new branch should not be created');
    }
    
}