mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Repository_URL__c</fullName>
    <description>The SSH URL of the version control system repository.</description>
    <inlineHelpText>The SSH URL of the version control system repository. This URL may explicitly specify the "ssh://" protocol or, as in the case of some VC services (e.g. GitHub), the URL may have its own unique syntax.</inlineHelpText>
    <label>Repository URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/TestTriggerUtils.cls
@isTest
public class TestTriggerUtils {

	private static testmethod void filterUpdatesByUpdatedField() {
		VC_Repository__c repo1 = TestingUtils.createVcRepository(
				'testRepo1','something@github.com');
		VC_Repository__c repo2 = TestingUtils.createVcRepository(
				'testRepo2','something@github.com');

		List<VC_Repository__c> newRepos = new List<VC_Repository__c>();
		newRepos.add(repo1);
		newRepos.add(repo2);

		Map<Id, VC_Repository__c> oldMap =
			new Map<Id, VC_Repository__c>([SELECT Id, Name, Repository_URL__c FROM VC_Repository__c]);

		repo1.Name = 'Changed Name';
		repo2.Repository_URL__C = 'Changed repo url';

		Test.startTest();
			List<VC_Repository__c> filteredRepos =
					TriggerUtils.filterUpdatesByUpdatedField(newRepos, oldMap, VC_Repository__c.Name);
		Test.stopTest();

		System.assertEquals(1, filteredRepos.size(), 'only one repo should have name changed');
		System.assertEquals(repo1.Name, filteredRepos[0].Name, 'the correct repo should be filtered');


	}
}