mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/VC_Repository_Validation__c.object-meta.xml
<CustomObject>
    <label>VC Repository Validation</label>
    <nameField>
        <displayFormat>VCRV-{0000}</displayFormat>
        <label>VC Repository Validation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VC Repository Validations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>External Id used to match this record uniquely</description>
    <externalId>true</externalId>
    <inlineHelpText>External Id used to match this record uniquely</inlineHelpText>
    <label>ExternalID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/fields/SuccessfulValidation__c.field-meta.xml
<CustomField>
    <fullName>SuccessfulValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represents the success status of this validation attempt</description>
    <inlineHelpText>Represents the success status of this validation attempt</inlineHelpText>
    <label>Successful Validation</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/fields/ValidationDate__c.field-meta.xml
<CustomField>
    <fullName>ValidationDate__c</fullName>
    <description>Date / Time when the validation occurred</description>
    <inlineHelpText>Date / Time when the validation occurred</inlineHelpText>
    <label>Validation Date</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/fields/ValidationError__c.field-meta.xml
<CustomField>
    <fullName>ValidationError__c</fullName>
    <description>Errors that occurred when attempting the validation</description>
    <inlineHelpText>Errors that occurred when attempting the validation</inlineHelpText>
    <label>Validation Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository_Validation__c/fields/VC_Repository__c.field-meta.xml
<CustomField>
    <fullName>VC_Repository__c</fullName>
    <description>The repository for which this validation was attempted</description>
    <inlineHelpText>The repository for which this validation was attempted</inlineHelpText>
    <label>VC Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>VC Repository Validations</relationshipLabel>
    <relationshipName>VC_Repository_Validations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/classes/TestVCControllerExt.cls
@isTest
private class TestVCControllerExt {
    private static final String TEST_REPOSITORY_URL = 'https://www.example.com/test-repository';
    private static final String TEST_REPOSITORY_HOST = 'GitHub';
    private static final String TEST_REPOSITORY_ORG_NAME = 'test-repository';
    private static VC_Repository__c testRepo;
    static {
        testRepo = TestingUtils.createVcRepository('git-repo', TEST_REPOSITORY_URL, TEST_REPOSITORY_HOST, TEST_REPOSITORY_ORG_NAME);
    }
    static testMethod void loadVCValidationsForUser_recordsFound() {
        DateTime currentTime = DateTime.Now();
        VC_Repository_Validation__c testValidationAttempt;
        //Create a validation attempt for the current user
        System.runAs(TestingUtils.ADMIN_USER){
            Boolean doInsert = false;
            testValidationAttempt = TestingUtils.createVcRepositoryValidation(testRepo, doInsert);
            testValidationAttempt.ValidationDate__c = currentTime;
            testValidationAttempt.SuccessfulValidation__c = true;
            insert testValidationAttempt;
        }

        List<VCRepository> actualReposWithValidations = new List<VCRepository>();
        Test.startTest();
            System.runAs(TestingUtils.ADMIN_USER){
                actualReposWithValidations = VCControllerExt.loadVCReposWithValidationsForUser();
            }
        Test.stopTest();

        System.assertEquals(1, actualReposWithValidations.size(),'One validation attempt, grouped by repo, should exist');
        VCRepository actualRepoRecord = actualReposWithValidations[0];
        System.assertEquals(testRepo.Id, actualRepoRecord.id, 'One validation attempt should exist for this repo');
        System.assertNotEquals(null, actualRepoRecord.validation, 'A validation record should exist for this repo');

        System.assertEquals(testValidationAttempt.ValidationDate__c, actualRepoRecord.validation.validationDate,
            'The validation date should be populated on the validation');
        System.assertEquals(testValidationAttempt.SuccessfulValidation__c, actualRepoRecord.validation.isSuccessful,
            'The successful validation field should be populated on the validation');
        System.assertEquals(testValidationAttempt.ValidationError__c, actualRepoRecord.validation.error,
            'The error field should be populated on the validation');
        System.assertEquals(testValidationAttempt.VC_Repository__c, actualRepoRecord.Id,
             'The repo validation repo id should match the repo id');
        System.assertEquals(testValidationAttempt.ExternalID__c, actualRepoRecord.validation.externalId,
             'The repo validation external id field should be populated');
    }

    static testMethod void loadVCValidationsForUser_noRecordsFound() {
        List<VCRepository> actualReposWithValidations = new List<VCRepository>();
        Test.startTest();
            System.runAs(TestingUtils.ADMIN_USER){
                actualReposWithValidations = VCControllerExt.loadVCReposWithValidationsForUser();
            }
        Test.stopTest();
        System.assertEquals(1, actualReposWithValidations.size(),'One repo should be found for the current user');
        System.assertEquals(null, actualReposWithValidations[0].validation, 'No validations should be found for the current user');
    }
}