mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Backlog__c.field-meta.xml
<CustomField>
    <fullName>Custom_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a different backlog, all items are already assigned to the main backlog</errorMessage>
        <filterItems>
            <field>Custom_Backlog__c.Universal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Custom_Backlog__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Priority__c.field-meta.xml
<CustomField>
    <fullName>Custom_Priority__c</fullName>
    <label>Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Main Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Custom_Backlog__c/Custom_Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Custom_Backlog__c/fields/Universal__c.field-meta.xml
<CustomField>
    <fullName>Universal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Universal</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/User_Preferences__c/fields/Default_Custom_Backlog_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Custom_Backlog_Id__c</fullName>
    <label>Default Custom Backlog Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/BacklogManagementHomeController.cls
public with sharing class BacklogManagementHomeController {

    public Integer permissionLevel {get; private set;}
    public transient ALMPageMessages pageMsgs { get; set; }
    public String namespace {get; set;}
    public String defaultCustomBacklogId {
        get {
            if (defaultCustomBacklogId == null) {
                User_Preferences__c preference = User_Preferences__c.getValues(UserInfo.getUserId());
                if (preference == null) {
                    defaultCustomBacklogId = '';
                } else {
                    defaultCustomBacklogId = preference.Default_Custom_Backlog_Id__c;
                }
            }

            return defaultCustomBacklogId;
        }

        set;
    }

    public static String MASTER_BACKLOG_IDENTIFIER {
        get {
            if (MASTER_BACKLOG_IDENTIFIER == null) {
                MASTER_BACKLOG_IDENTIFIER = 'Master';
            }

            return MASTER_BACKLOG_IDENTIFIER;
        }

        set;
    }

    public static String MASTER_BACKLOG_RECORD_ID {
        get {
            return CustomBacklogServices.MASTER_BACKLOG_RECORD.Id;
        }

        set;
    }

    private final static String DUPLICATE_CUSTOM_BACKLOG_NAME_ERROR_MSG = 'Custom backlog already exist.';

    public BacklogManagementHomeController(){
        permissionLevel = PermissionServices.checkPagePermissions(new CustomBacklogPermissions()).ordinal();
        namespace = SObjectServices.getNameSpace();
    }

    private static List<CustomBacklogModel> getCustomBacklogModels(List<Custom_Backlog__c> customBacklogs){
        List<CustomBacklogModel> cbklgModels = new List<CustomBacklogModel>();
        for (Custom_Backlog__c cbklg : customBacklogs){
            CustomBacklogModel cbklgModel = new CustomBacklogModel(cbklg);
            if (cbklg.Universal__c) {
                setGlobalBacklogCounts(cbklgModel);
            }
            cbklgModels.add(cbklgModel);
        }
        return cbklgModels;
    }

    public static void setGlobalBacklogCounts(CustomBacklogModel cbklgModel) {
        Integer unprioritizedInt = 0;
        Set<String> inactiveStatuses = BacklogItemServices.getInactiveStatuses();
        List<Backlog__c> items = [SELECT Id, Priority__c, Name
                 FROM Backlog__c
                 WHERE Status__c NOT IN :inactiveStatuses
                 ORDER BY Priority__c NULLS FIRST LIMIT 1000];

        for (Backlog__c item: items) {
            if (item.Priority__c == null) {
                unprioritizedInt += 1;
            }
        }
        cbklgModel.unprioritizedItems = CustomBacklogModel.getCountAsString(unprioritizedInt);
        cbklgModel.totalItems = CustomBacklogModel.getCountAsString(items.size());
    }

    @ReadOnly
    @RemoteAction
    public static List<CustomBacklogModel> getAllCustomBacklogs() {
        Set<String> inactiveStatuses = BacklogItemServices.getInactiveStatuses();
        List<Custom_Backlog__c> currentCustomBacklogs = [
            SELECT Id, Name, Universal__c,
                (SELECT Id, Custom_Priority__c, Name
                 FROM Backlog_Items__r
                 WHERE Status__c NOT IN :inactiveStatuses
                 ORDER BY Custom_Priority__c NULLS FIRST LIMIT 1000)
            FROM Custom_Backlog__c ORDER BY Universal__c DESC, Name ASC LIMIT 500
        ];
        return getCustomBacklogModels(CustomBacklogServices.loadSortedCustomBacklogs(currentCustomBacklogs));
    }

    @RemoteAction
    public static void updateUserPreferences(String backlogId) {
        User_Preferences__c preference = User_Preferences__c.getInstance(UserInfo.getUserId());
        preference.Default_Custom_Backlog_Id__c = backlogId;

        try {
            upsert preference;
        } catch (DMLException e) {
            throw new ALMException('An error occured updating the User_Preferences__c custom setting: '+ e.getMessage() );
        }
    }

    @RemoteAction
    public static void updateUserSpecificSortState(String customBacklogIds) {
        if (PermissionServices.checkPagePermissions(new CustomBacklogPermissions()).ordinal() < PermissionServices.PermissionLevel.FULL.ordinal()) {
            return;
        }

        CustomBacklogServices.updateCustomBacklogSortState(customBacklogIds);
    }

    private static UpsertCustomBacklogResponse validateCustomBacklogName(String name){
        UpsertCustomBacklogResponse response = new UpsertCustomBacklogResponse();
        List<Custom_Backlog__c> customBacklogs = [Select Id From Custom_Backlog__c Where Name = :name];
        if (!customBacklogs.isEmpty()){
            response.isSuccess = false;
            response.isValid = false;
            response.errorMsg = DUPLICATE_CUSTOM_BACKLOG_NAME_ERROR_MSG;
            return response;
        }
        response.isValid = true;
        return response;
    }

    @RemoteAction
    public static UpsertCustomBacklogResponse createCustomBacklog(String name) {
        if (PermissionServices.checkPagePermissions(new CustomBacklogPermissions()).ordinal() < PermissionServices.PermissionLevel.FULL.ordinal()) {
            UpsertCustomBacklogResponse response = new UpsertCustomBacklogResponse();
            response.isSuccess = false;
            response.errorMsg = System.Label.Permissions_Error;

            return response;
        }

        UpsertCustomBacklogResponse response = validateCustomBacklogName(name);
        if (!response.isValid){
            return response;
        }
        try {
            Custom_Backlog__c customBacklog = new Custom_Backlog__c(Name = name);
            insert customBacklog;
            response.customBacklogId = customBacklog.Id;
            response.isSuccess = true;
        } catch (Exception e){
            response.isSuccess = false;
            response.errorMsg = e.getMessage();
        }
        return response;
    }

    @RemoteAction
    public static UpsertCustomBacklogResponse updateCustomBacklog(String customBacklogId, String name) {
        if (PermissionServices.checkPagePermissions(new CustomBacklogPermissions()).ordinal() < PermissionServices.PermissionLevel.FULL.ordinal()) {
            UpsertCustomBacklogResponse response = new UpsertCustomBacklogResponse();
            response.isSuccess = false;
            response.errorMsg = System.Label.Permissions_Error;

            return response;
        }

        UpsertCustomBacklogResponse response = validateCustomBacklogName(name);
        if (!response.isValid){
            return response;
        }
        try {
            if(BacklogManagementHomeController.MASTER_BACKLOG_IDENTIFIER.equalsIgnoreCase(customBacklogId)) {
                customBacklogId = BacklogManagementHomeController.MASTER_BACKLOG_RECORD_ID;
            }
            Custom_Backlog__c customBacklog = new Custom_Backlog__c(Id=customBacklogId, Name = name);
            update customBacklog;
            response.customBacklogId = customBacklog.Id;
            response.isSuccess = true;
        } catch (Exception e){
            response.isSuccess = false;
            response.errorMsg = e.getMessage();
        }
        return response;
    }

    public class UpsertCustomBacklogResponse {
        public String customBacklogId;
        public Boolean isSuccess;
        public Boolean isValid;
        public String errorMsg;
        public UpsertCustomBacklogResponse(){

        }
    }
}