mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Commit__c/VC_Commit__c.object-meta.xml
<CustomObject>
    <label>VC Commit</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>VC Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VC Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Backlog_Components__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Components__c</fullName>
    <label>Backlog Components</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Backlog_Item__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Commit History</relationshipLabel>
    <relationshipName>VC_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Commit_Message__c.field-meta.xml
<CustomField>
    <fullName>Commit_Message__c</fullName>
    <label>Commit Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <type>TextArea</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>VC Commits</relationshipLabel>
    <relationshipName>VC_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed with Errors</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/VC_Commit__c/fields/VC_Repository__c.field-meta.xml
<CustomField>
    <fullName>VC_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>VC Commits</relationshipLabel>
    <relationshipName>VC_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Repository_URL__c</fullName>
    <description>The SSH URL of the version control system repository.</description>
    <inlineHelpText>The SSH URL of the version control system repository. This URL may explicitly specify the "ssh://" protocol or, as in the case of some VC services (e.g. GitHub), the URL may have its own unique syntax.</inlineHelpText>
    <label>Repository URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Source_Format__c.field-meta.xml
<CustomField>
    <fullName>Source_Format__c</fullName>
    <inlineHelpText>This setting controls how the metadata is stored in your repository. If you&#39;re building with Salesforce DX scratch orgs, then select &quot;Salesforce DX.&quot; If you&#39;re building in any other standard Salesforce org, select &quot;Metadata API&quot; format.&quot;</inlineHelpText>
    <label>Source Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metadata API</fullName>
            </value>
            <value>
                <fullName>Salesforce DX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/GitController.cls
public with sharing class GitController extends OAuthController {
    public String backlogItemId {get; set;}
    public String backlogItemName {get; set;}
    public String instanceId {get; set;}
    public static String SUCCESS_COMMIT_MESSAGE = 'Your commit request was submitted succesfully.';

    @TestVisible
    private static final String PAGE_STATE_TOKEN = 'PageState GitController';

    public GitController(ApexPages.StandardSetController controller) {
        setPageContext();
    }

    @AuraEnabled
    public static List<RepositoryResult> retrieveRepos() {
        List<RepositoryResult> results = new List<RepositoryResult>();
        for (VC_Repository__c vcRepository : [ SELECT Id, Repository_URL__c, Source_Format__c, Name FROM VC_Repository__c]) {
            results.add(new RepositoryResult(vcRepository));
        }
        return results;
    }

    @AuraEnabled
    public static List<String> retrieveBranches(String repositoryId) {
        try {
            VCServices.GitListResponse response = VCServices.gitListBranches(UserInfo.getUserId(), repositoryId, false);

            if (response.isSuccess) {
                return response.references;
            } else {
                throw new AuraHandledException(response.failureReason);
            }
        } catch (AuraHandledException e) {
            //In order to preserve the message, handle any aura exceptions separately
            throw e;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private Boolean setPageContext() {
        String backlogId = ApexPages.currentPage().getParameters().get('id');
        //@TODO need to get the instanceId from the state
        //String instanceId = ApexPages.currentPage().getParameters().get('id');
        Backlog__c backLogFromPageParams = BacklogItemServices.getBacklogRecord( backlogId );
        if( backLogFromPageParams == null )
            return false;
        backlogItemId = backLogFromPageParams.Id;
        backlogItemName = backLogFromPageParams.Name;
        return PermissionServices.checkPagePermissions(new GitCommitPermissions()) == PermissionServices.PermissionLevel.FULL;
    }

    @AuraEnabled
    public static List<Instances__c> getInstances() {
        return InstanceServices.getAllInstances();
    }

    public class RepositoryResult {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String repoURL;

        public RepositoryResult(VC_Repository__c repo) {
            this.id = repo.Id;
            this.name = repo.Name;
            this.repoURL = repo.Repository_URL__c;
        }
    }

    @AuraEnabled
    public static PageMessage makeCommitRequest(String vcCommitId) {
        VC_Commit__c vcCommit = [SELECT Backlog_Item__c, Backlog_Components__c, Branch_Name__c, Commit_Message__c, VC_Repository__c,
                                       Response_Message__c, Source_Instance__c, Status__c, CreatedBy.Username
                                   FROM VC_Commit__c
                                   WHERE Id=:vcCommitId];
        try {
            // TODO: makeCommitRequest should just take an Id
            VCServices.makeCommitRequest(vcCommit);
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return new PageMessage(ApexPages.Severity.CONFIRM, SUCCESS_COMMIT_MESSAGE);
    }

    @AuraEnabled
    public static String saveCommitRequest(String commitRequestJSON) {
        CommitRequest request;
        try {
            request = (CommitRequest) JSON.deserialize(commitRequestJSON, CommitRequest.class);
            VC_Commit__c vcCommit = request.buildVCCommitObject();
            insert vcCommit;
            return vcCommit.Id;
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class CommitRequest {
        @AuraEnabled
        public String backlogItemId;
        @AuraEnabled
        public List<String> backlogComponentIds;
        @AuraEnabled
        public String repositoryId;
        @AuraEnabled
        public String branchName;
        @AuraEnabled
        public String commitMessage;
        @AuraEnabled
        public String instanceId;

        public CommitRequest(String backlogItemId, List<String> backlogComponentIds, String repositoryId,
                             String branchName, String commitMessage, String instanceId) {
            this.backlogItemId = backlogItemId;
            this.backlogComponentIds = backlogComponentIds;
            this.repositoryId = repositoryId;
            this.branchName = branchName;
            this.commitMessage = commitMessage;
            this.instanceId = instanceId;
        }

        public VC_Commit__c buildVCCommitObject() {
            String backlogComponentIdsString = String.join(backlogComponentIds, ',');

            return new VC_Commit__c(Backlog_Components__c=backlogComponentIdsString, Backlog_Item__c=this.backlogItemId,
                                     Branch_Name__c=this.branchName, Commit_Message__c=this.commitMessage,
                                     VC_Repository__c=this.repositoryId, Source_Instance__c=instanceId);
        }
    }

    /**
    * Saves the current state of the user inputs on the page.
    * @param backlogItemId - The ID of the relevant backlog item.
    * @param pageStateMap - A map representing the current state of the user inputs on the page.
    */
    @AuraEnabled
    public static void savePageState(String backlogItemId, Map<String, Object> pageStateMap) {
        if (pageStateMap != null) {
            State.store(new PageState(constructPageStateToken(backlogItemId), pageStateMap));
        }
    }

    /**
    * Loads any existing saved state of the user inputs on the page.
    * @param backlogItemId - The ID of the relevant backlog item.
    * @return pageStateMap - A map representing any existing saved state of the user inputs on the page.
    */
    @AuraEnabled
    public static Map<String, Object> loadPageState(String backlogItemId) {
        PageState stateInstance = new PageState(constructPageStateToken(backlogItemId));

        try {
            State.retrieve(stateInstance);
        } catch (State.StateException se) {
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return stateInstance.stateMap;
    }

    /**
    * Expires any existing saved state of the user inputs on the page.
    * @param backlogItemId - The ID of the relevant backlog item.
    */
    @AuraEnabled
    public static void expirePageState(String backlogItemId) {
        new PageState(constructPageStateToken(backlogItemId)).expire();
    }

    /**
    * Constructs the state application token for the page state. This is used when saving/loading existing page state.
    * @param backlogItemId - The ID of the relevant backlog item.
    */
    public static String constructPageStateToken(String backlogItemId) {
        return PAGE_STATE_TOKEN + State.STATE_TOKEN_DELIM + backlogItemId;
    }
}