mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the progress of item is blocked.  Not a status or state since we don't want to lose the original value to set it to blocked.</inlineHelpText>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Business_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Value__c</fullName>
    <inlineHelpText>This is used to measure the business value.</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Closed_Date__c</fullName>
    <description>Defect Closed on Date/Time</description>
    <inlineHelpText>Date/Time defect's status was set to Closed</inlineHelpText>
    <label>Closed Date</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Replication steps for defects, requirements for features and stories.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Design consideration and solution notes.</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>Short summary of the backlog item</description>
    <inlineHelpText>Enter a short summary of the backlog item</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/recordTypes/Defect.recordType-meta.xml
<RecordType>
    <fullName>Defect</fullName>
    <active>true</active>
    <description>A bug or an issue related to an implemented story.</description>
    <label>Defect</label>
</RecordType>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/Feedback_API_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores field mapping from for
Feedback API.  Mapping is from source field name to target field name.</description>
    <label>Feedback API Mapping</label>
</CustomObject>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Comparison_Value__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Value__c</fullName>
    <description>Comparison value to match operator against</description>
    <inlineHelpText>Comparison value to match operator against (Only populate if this is a complex mapping)</inlineHelpText>
    <label>Comparison Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Is_Complex__c.field-meta.xml
<CustomField>
    <fullName>Is_Complex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate that the mapping is not a 1:1 mapping from a field in the source object to a field in the target object</description>
    <inlineHelpText>Used to indicate that the mapping is not a 1:1 mapping from a field in the source object to a field in the target object</inlineHelpText>
    <label>Is Complex?</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Only 'equals' is currently supported. If blank, the target value will always be applied</description>
    <inlineHelpText>Only 'equals' is currently supported. If blank, the target value will always be applied (Only populate if this is a complex mapping)</inlineHelpText>
    <label>Operator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Mapping__c/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <description>Value to populate target field with if comparison evaluates to true - This can be in the form of a merge field on the source object e.g. {!SourceFieldName}. Otherwise, the value will be copied as is.</description>
    <inlineHelpText>Value to populate target field with if comparison evaluates to true - This can be in the form of a merge field on the source object e.g. {!SourceFieldName}. Otherwise, the value will be copied as is. (only necessary if this is a complex mapping)</inlineHelpText>
    <label>Target Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/Feedback_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Feedback REST API</description>
    <label>Feedback API Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <inlineHelpText>ID of the Org we expect to be receiving requests from.</inlineHelpText>
    <label>Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Feedback_API_Settings__c/fields/Target_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Name__c</fullName>
    <inlineHelpText>The API name of the target object to create. In most cases this will be Backlog__c</inlineHelpText>
    <label>Target Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/TestFeedbackRestService.cls
@isTest
private class TestFeedbackRestService
{
    static Feedback_API_Settings__c apiSettings;

    static void setup()
    {
        apiSettings = TestingUtils.createFeedackAPISettings();
        createFeedbackMapping();
    }

    static testMethod void create_failure_settingsNotDefined()
    {
        Backlog__c backlogData = new Backlog__c();

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

            FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, '');

        Test.stopTest();

        System.assertEquals(false, response.success, 'The request should fail when there are no settings.');
        System.assertEquals(FeedbackRestService.NO_SETTINGS_ERROR_MSG, response.message, 'The request should fail when there are no settings.');
    }

    static testMethod void create_failure_invalidSettings()
    {
        apiSettings = TestingUtils.createFeedackAPISettings();
        apiSettings.Target_Object_Name__c = 'InvalidObjectName';
        System.runAs( TestingUtils.ADMIN_USER ) {
            update apiSettings;
        }
        createFeedbackMapping();

        Backlog__c backlogData = new Backlog__c();

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

            FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assertEquals(false, response.success, 'The request should fail when there are invalid settings.');
        System.assertEquals(FeedbackRestService.INVALID_SETTINGS_ERROR_MSG, response.message, 'The request should fail when there are invalid settings.');
    }

    static testMethod void create_failure_invalidMapping()
    {
        setup();

        TestingUtils.createFeedackAPIMapping( SObjectServices.getFullyQualifiedName('Blocked__c'), 'bad_field');

        Backlog__c backlogData = new Backlog__c(Blocked__c=false);

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

            FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assertEquals(false, response.success, 'The request should fail when there is an invalid mapping.');
        System.assert( response.message.contains( FeedbackRestService.INVALID_MAPPING_ERROR_MSG) , 'The request should fail when there is an invalid mapping');
    }

    static testMethod void create_failure_invalidJSON()
    {
        setup();
        String feedbackData = '{"key" : val[1]';

        Test.startTest();

            FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assertEquals(false, response.success, 'The request should fail when there are no settings.');
        System.assertEquals(FeedbackRestService.INVALID_JSON_ERROR, response.message, 'The request should fail when there is invalid JSON.');
    }

    static testMethod void create_failure_unauthorized()
    {
        setup();

        Backlog__c backlogData = new Backlog__c(Blocked__c=false);
        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

            FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, '');

        Test.stopTest();

        System.assertEquals(false, response.success, 'The request should fail when there is no org id set.');
        System.assertEquals(FeedbackRestService.UNAUTHORIZED_MSG, response.message, 'The request should fail when the user is not authorized.');
    }

    static testMethod void create_backlogWithData_success()
    {
        setup();

        Backlog__c backlogData = new Backlog__c();
        backlogData.Business_Value__c = 8;
        backlogData.Description__c = 'A description with text';

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

           FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assert(response.success, 'The request should be successful:' + response.message);

        List<Backlog__c> backlogs = [ SELECT Id, Name, Business_Value__c, Solution__c FROM Backlog__c ];

        System.assertEquals( 1, backlogs.size(), 'One backlog record should have been created');

        Backlog__c createdBacklog = backlogs[0];
        System.assertEquals( createdBacklog.Id, response.createdId, 'The response Id should be set');
        System.assertEquals( createdBacklog.Name, response.createdName, 'The created record Name should be set in the reponse');

        System.assertEquals( backlogData.Business_Value__c, createdBacklog.Business_Value__c, 'Fields on the backlog should be mapped using the feedback mapping');
        System.assertEquals( backlogData.Description__c, createdBacklog.Solution__c, 'Fields on the backlog should be mapped using the feedback mapping');
    }

/*
    Removing test for now since we have no Date fields in the PM package
    static testMethod void create_backlogWithData_mapDate()
    {
        Feedback_API_Settings__c settings = new Feedback_API_Settings__c();
        settings.Org_Id__c = '123456789';
        settings.Target_Object_Name__c = SObjectServices.getFullyQualifiedName( 'Test_Case__c' );

        System.runAs( TestingUtils.ADMIN_USER ) {
            insert settings;
        }

        Feedback_API_Mapping__c dateMapping = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('End_Date__c'), SObjectServices.getFullyQualifiedName('End_Date__c'));

        Test_Case__c backlogData = new Test_Case__c();
        backlogData.End_Date__c = Date.today();

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

           FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, settings.Org_Id__c);

        Test.stopTest();

        System.assert(response.success, 'The request should be successful:' + response.message);
    }
*/
    static testMethod void create_backlogWithData_mapDateTime()
    {
        setup();

        Feedback_API_Mapping__c datetimeMapping = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('Closed_Date__c'), SObjectServices.getFullyQualifiedName('Closed_Date__c'));

        Backlog__c backlogData = new Backlog__c();
        backlogData.Closed_Date__c = Datetime.now();

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

           FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assert(response.success, 'The request should be successful:' + response.message);

        List<Backlog__c> backlogs = [ SELECT Id, Name, Business_Value__c, Solution__c, Closed_Date__c FROM Backlog__c ];

        System.assertEquals( 1, backlogs.size(), 'One backlog record should have been created');

        Backlog__c createdBacklog = backlogs[0];
        System.assertEquals( createdBacklog.Id, response.createdId, 'The response Id should be set');

        System.assertEquals( backlogData.Closed_Date__c, createdBacklog.Closed_Date__c, 'Datetime Fields on the backlog should be mapped using the feedback mapping');
    }

    static testMethod void create_backlogWithComplexMapping_conditional()
    {
        final String DEFECT_STATUS = 'Bug';
        setup();

        Feedback_API_Mapping__c complexMapping1 = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('Status__c'), 'RecordTypeId');
        complexMapping1.Is_Complex__c = true;
        complexMapping1.Operator__c = FeedbackRestService.EQUALS_OPERATOR;
        complexMapping1.Comparison_Value__c = DEFECT_STATUS;
        complexMapping1.Target_Value__c = [SELECT Id FROM RecordType WHERE SObjectType = :SObjectServices.getFullyQualifiedName('Backlog__c') AND Name = 'Defect'].Id;

        Feedback_API_Mapping__c complexMapping2 = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('Summary__c'), SObjectServices.getFullyQualifiedName('Description__c'));
        complexMapping2.Is_Complex__c = true;
        complexMapping2.Operator__c = FeedbackRestService.EQUALS_OPERATOR;
        complexMapping2.Comparison_Value__c = 'Not a bug';
        complexMapping2.Target_Value__c = 'Some value';
        System.runAs( TestingUtils.ADMIN_USER ) {
           update new List<Feedback_API_Mapping__c>{ complexMapping1, complexMapping2 };
        }

        Backlog__c backlogData = new Backlog__c();
        backlogData.Business_Value__c = 8;
        backlogData.Status__c = DEFECT_STATUS;
        backlogData.Summary__c = 'This might be a bug';

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

           FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assert(response.success, 'The request should be successful');

        List<Backlog__c> backlogs = [ SELECT Id, Name, Business_Value__c, Description__c, RecordTypeId FROM Backlog__c ];

        System.assertEquals( 1, backlogs.size(), 'One backlog record should have been created');

        Backlog__c createdBacklog = backlogs[0];
        System.assertEquals( createdBacklog.Id, response.createdId, 'The response Id should be set');
        System.assertEquals( createdBacklog.Name, response.createdName, 'The created record Name should be set in the reponse');


        System.assertEquals( complexMapping1.Target_Value__c, createdBacklog.RecordTypeId, 'The target value from the complex mapping should be populated in the target field when the mapping evaluates to true');
        System.assertEquals( backlogData.Business_Value__c, createdBacklog.Business_Value__c, 'Fields on the backlog should be mapped using the feedback mapping');
        System.assertEquals( null, backlogData.Description__c, 'complex mapping criteria that are not met should not be evaluated');
    }

    static testMethod void create_backlogWithComplexMapping_mergeField()
    {
        final String DEFECT_STATUS = 'Bug';
        setup();

        Feedback_API_Mapping__c complexMapping1 = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('Status__c'), SObjectServices.getFullyQualifiedName('Summary__c'));
        complexMapping1.Is_Complex__c = true;
        complexMapping1.Target_Value__c = '{!' + SObjectServices.getFullyQualifiedName('Status__c') + '} - ' + '{!' + SObjectServices.getFullyQualifiedName('Summary__c') + '}';

        System.runAs( TestingUtils.ADMIN_USER ) {
           update complexMapping1;
        }

        Backlog__c backlogData = new Backlog__c();
        backlogData.Business_Value__c = 8;
        backlogData.Status__c = DEFECT_STATUS;
        backlogData.Summary__c = 'This might be a bug';

        String expectedResult = backlogData.Status__c + ' - ' + backlogData.Summary__c;

        String feedbackData = JSON.serialize( backlogData );

        Test.startTest();

           FeedbackRestService.Response response = FeedbackRestService.create(feedbackData, apiSettings.Org_Id__c);

        Test.stopTest();

        System.assert(response.success, 'The request should be successful');

        List<Backlog__c> backlogs = [ SELECT Id, Name, Business_Value__c, Description__c, Summary__c FROM Backlog__c ];

        System.assertEquals( 1, backlogs.size(), 'One backlog record should have been created');

        Backlog__c createdBacklog = backlogs[0];
        System.assertEquals( createdBacklog.Id, response.createdId, 'The response Id should be set');
        System.assertEquals( createdBacklog.Name, response.createdName, 'The created record Name should be set in the reponse');


        System.assertEquals( expectedResult, createdBacklog.Summary__c, 'The target value from the complex mapping should be populated in the target field with merge fields evaluated');
        System.assertEquals( backlogData.Business_Value__c, createdBacklog.Business_Value__c, 'Fields on the backlog should be mapped using the feedback mapping');
    }

    static List<Feedback_API_Mapping__c> createFeedbackMapping()
    {
        Feedback_API_Mapping__c fieldMapping1 = TestingUtils.createFeedackAPIMapping(SObjectServices.getFullyQualifiedName('Business_Value__c'), SObjectServices.getFullyQualifiedName('Business_Value__c'));
        Feedback_API_Mapping__c fieldMapping2 = TestingUtils.createFeedackAPIMapping( SObjectServices.getFullyQualifiedName('Description__c'), SObjectServices.getFullyQualifiedName('Solution__c'));

        return new List<Feedback_API_Mapping__c> { fieldMapping1, fieldMapping2 };
    }
}