mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org__c/Scratch_Org__c.object-meta.xml
<CustomObject>
    <label>Scratch Org</label>
    <pluralLabel>Scratch Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <label>Scratch Org Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Backlog_Item__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Scratch Orgs</relationshipLabel>
    <relationshipName>Scratch_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_Days__c</fullName>
    <description>The amount of days the scratch org should last</description>
    <inlineHelpText>The amount of days the scratch org should last</inlineHelpText>
    <label>Duration in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Parent_Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Branch_Name__c</fullName>
    <description>Name of the branch used to create the branch for this scratch org</description>
    <inlineHelpText>Name of the branch used to create the branch for this scratch org</inlineHelpText>
    <label>Parent Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Repository_Location__c.field-meta.xml
<CustomField>
    <fullName>Repository_Location__c</fullName>
    <label>Repository Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/Scratch_Org_Definition__c.field-meta.xml
<CustomField>
    <fullName>Scratch_Org_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The scratch org definition used to create this scratch org</description>
    <label>Scratch Org Definition</label>
    <referenceTo>Scratch_Org_Definition__c</referenceTo>
    <relationshipLabel>Scratch Orgs</relationshipLabel>
    <relationshipName>Scratch_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org__c/fields/VC_Repository__c.field-meta.xml
<CustomField>
    <fullName>VC_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>Scratch Orgs</relationshipLabel>
    <relationshipName>Scratch_Orgs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Scratch_Org_Definition__c/Scratch_Org_Definition__c.object-meta.xml
<CustomObject>
    <description>Options used when creating a scratch org</description>
    <label>Scratch Org Definition</label>
    <nameField>
        <label>Scratch Org Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scratch Org Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/TestDXController.cls
@isTest
private with sharing class TestDXController {

    @isTest
    static void createScratchOrgRecord() {
        Backlog__c backlogItem = TestingUtils.createBacklogItem();
        String name = 'scratch-org-name';
        VC_Repository__c repo = TestingUtils.createVcRepository('createScratchOrg-repo', 'https://repo-url.com');
        String branchName = 'dev';
        Scratch_Org_Definition__c orgDef = TestingUtils.createScratchOrgDefinition('test-org-def-createScratchOrg');
        Integer durationDays = 8;
        String parentBranchName = 'Item-01234';

        Test.startTest();
            String scratchOrgId = DXController.createScratchOrgRecord(
                name, backlogItem.Id, repo.Id, branchName, orgDef.Id, durationDays, parentBranchName);
        Test.stopTest();

        List<Scratch_Org__c> scratchOrgs = [
            SELECT Id, Name, VC_Repository__c, Repository_Location__c, Backlog_Item__c, Parent_Branch_Name__c,
            Scratch_Org_Definition__c, Duration_Days__c
            FROM Scratch_Org__c
            WHERE Id = :scratchOrgId
        ];

        System.assertEquals(1, scratchOrgs.size(), 'The scratch org should have been created');
        System.assertEquals(repo.Id, scratchOrgs[0].VC_Repository__c, 'The scratch org repo should be populated');
        System.assertEquals(branchName, scratchOrgs[0].Repository_Location__c,
            'The scratch org repo location should be populated');
        System.assertEquals(backlogItem.Id, scratchOrgs[0].Backlog_Item__c,
            'The scratch org backlog item should be populated');
        System.assertEquals(orgDef.Id, scratchOrgs[0].Scratch_Org_Definition__c,
            'The scratch org scratch org definition should be populated');
        System.assertEquals(durationDays, scratchOrgs[0].Duration_Days__c,
            'The scratch org should have the correct amount of duration days');
        System.assertEquals(parentBranchName, scratchOrgs[0].Parent_Branch_Name__c,
            'The scratch org new branch name should be populated');
    }

    @isTest
    static void getScratchOrgs() {
        Backlog__c backlogItem = TestingUtils.createBacklogItem();
        Scratch_Org__c scratchOrg = new Scratch_Org__c(Backlog_Item__c = backlogItem.Id, Duration_Days__c = 8);
        Scratch_Org__c otherScratchOrg = new Scratch_Org__c(Duration_Days__c = 8);
        insert new List<Scratch_Org__c> { scratchOrg, otherScratchOrg };

        Test.startTest();
            List<DXController.ScratchOrgModel> scratchOrgs = DXController.getScratchOrgs(backlogItem.Id);
        Test.stopTest();

        System.assertEquals(1, scratchOrgs.size(), 'Only scratch orgs related to the backlog item should be returned');
        System.assertEquals(scratchOrg.Id, scratchOrgs[0].id,
            'Only scratch orgs related to the backlog item should be returned');
        System.assertEquals(true, scratchOrgs[0].isLoginable,
            'Scratch orgs created by the running user should be loginable');
    }
}