mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/SprintColumnConfig.cls
public with sharing class SprintColumnConfig extends ColumnConfig {
    public SprintColumnConfig() {
        super();
        loadColumns();
    }

    private void loadColumns() {
        Map<String, String> statusValueToLabel = SObjectServices.getPicklistValueMap(Schema.SObjectType.Backlog__c.fields.Status__c);

        Map<String, Column> allColumns = new Map<String, Column>();
        for (String status : statusValueToLabel.keySet()) {
            allColumns.put(status, new Column(status, statusValueToLabel.get(status)));
        }
        activeColumns = SprintServices.getLanes();

        addStaticColumns(activeColumns, new List<Column>{ new Column(SprintModel.NOT_STARTED_STATUS) });

        for (Column col : activeColumns) {
            allColumns.remove(col.apiName);
        }

        Set<String> unusedStatuses = allColumns.keySet();
        for (String status : statusValueToLabel.keySet()) {
            if (unusedStatuses.contains(status)) {
                unusedColumns.add(new Column(status, statusValueToLabel.get(status)));
            }
        }
    }
}