mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Current_Sprint__c.field-meta.xml
<CustomField>
    <fullName>Current_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/Sprint_Item__c.object-meta.xml
<CustomObject>
    <label>Sprint Item</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Sprint Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Sprint Items</relationshipLabel>
    <relationshipName>Sprint_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Sprint Items</relationshipLabel>
    <relationshipName>Sprint_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestBacklogItemTrigger.cls
@isTest
private class TestBacklogItemTrigger {
    static testMethod void backlogItem_insert_single_notCompleted() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint.Id);

        Test.startTest();

            try {
                insert backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> sprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];

        System.assertEquals(1, sprintItems.size(), 'There should be one new sprint item.');
        System.assertEquals(backlogItem.Id, sprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, sprintItems[0].Sprint__c, 'The sprint ID should match.');
    }

    static testMethod void backlogItem_insert_single_completed() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.COMPLETED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint.Id);

        Test.startTest();

            try {
                insert backlogItem;
                System.assert(false, 'An exception should be thrown.');
            } catch (Exception e) {
                System.assert(true, 'An exception should be thrown.');
                System.assert(e.getMessage().contains(Label.Sprint_Item_Cannot_Add_To_Completed_Sprint), 'The exception message should match.');
            }

        Test.stopTest();

        List<Sprint_Item__c> sprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];

        System.assertEquals(0, sprintItems.size(), 'There should be no new sprint items.');
    }

    static testMethod void backlogItem_insert_multiple_mixture() {
        Sprint__c sprint0 = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.COMPLETED_STATUS);
        Sprint__c sprint1 = new Sprint__c(Name = 'Test Sprint 1', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert new List<Sprint__c>{ sprint0, sprint1 };

        Backlog__c backlogItem0 = new Backlog__c(Current_Sprint__c = sprint0.Id);
        Backlog__c backlogItem1 = new Backlog__c(Current_Sprint__c = sprint1.Id);

        Test.startTest();

            try {
                Database.insert(new List<Backlog__c>{ backlogItem0, backlogItem1 }, false);
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> sprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];

        System.assertEquals(1, sprintItems.size(), 'There should be one new sprint item.');
        System.assertEquals(backlogItem1.Id, sprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint1.Id, sprintItems[0].Sprint__c, 'The sprint ID should match.');
    }

    static testMethod void backlogItem_update_single_addSprintItem_notCompleted() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c();
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(0, beforeSprintItems.size(), 'There should be no sprint items before the update.');

        Test.startTest();

            backlogItem.Current_Sprint__c = sprint.Id;

            try {
                update backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, afterSprintItems.size(), 'There should be one new sprint item.');
        System.assertEquals(backlogItem.Id, afterSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, afterSprintItems[0].Sprint__c, 'The sprint ID should match.');
    }

    static testMethod void backlogItem_update_single_addSprintItem_completed() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.COMPLETED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c();
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(0, beforeSprintItems.size(), 'There should be no sprint items before the update.');

        Test.startTest();

            backlogItem.Current_Sprint__c = sprint.Id;

            try {
                update backlogItem;
                System.assert(false, 'An exception should be thrown.');
            } catch (Exception e) {
                System.assert(true, 'An exception should be thrown.');
                System.assert(e.getMessage().contains(Label.Sprint_Item_Cannot_Add_To_Completed_Sprint), 'The exception message should match.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(0, afterSprintItems.size(), 'There should be no new sprint items.');
    }

    static testMethod void backlogItem_update_single_addSprintItem_duplicate() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint.Id);
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, beforeSprintItems.size(), 'There should be one sprint item before the update.');
        System.assertEquals(backlogItem.Id, beforeSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, beforeSprintItems[0].Sprint__c, 'The sprint ID should match.');

        Test.startTest();

            backlogItem.Current_Sprint__c = sprint.Id;

            try {
                update backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, afterSprintItems.size(), 'There should be one sprint item.');
        System.assertEquals(backlogItem.Id, afterSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, afterSprintItems[0].Sprint__c, 'The sprint ID should match.');
        System.assertEquals(beforeSprintItems[0].Id, afterSprintItems[0].Id, 'The sprint item ID should match.');
    }

    static testMethod void backlogItem_update_single_moveSprintItem_notCompleted() {
        Sprint__c sprint0 = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        Sprint__c sprint1 = new Sprint__c(Name = 'Test Sprint 1', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert new List<Sprint__c>{ sprint0, sprint1 };

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint0.Id);
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, beforeSprintItems.size(), 'There should be one sprint item before the update.');
        System.assertEquals(backlogItem.Id, beforeSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint0.Id, beforeSprintItems[0].Sprint__c, 'The sprint ID should match.');

        Test.startTest();

            backlogItem.Current_Sprint__c = sprint1.Id;

            try {
                update backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, afterSprintItems.size(), 'There should be one sprint item.');
        System.assertEquals(backlogItem.Id, afterSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint1.Id, afterSprintItems[0].Sprint__c, 'The sprint ID should match.');
    }

    static testMethod void backlogItem_update_single_moveSprintItem_completed() {
        Sprint__c sprint0 = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        Sprint__c sprint1 = new Sprint__c(Name = 'Test Sprint 1', Status__c = SprintModel.COMPLETED_STATUS);
        insert new List<Sprint__c>{ sprint0, sprint1 };

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint0.Id);
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, beforeSprintItems.size(), 'There should be one sprint item before the update.');
        System.assertEquals(backlogItem.Id, beforeSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint0.Id, beforeSprintItems[0].Sprint__c, 'The sprint ID should match.');

        Test.startTest();

            backlogItem.Current_Sprint__c = sprint1.Id;

            try {
                update backlogItem;
                System.assert(false, 'An exception should be thrown.');
            } catch (Exception e) {
                System.assert(true, 'An exception should be thrown.');
                System.assert(e.getMessage().contains(Label.Sprint_Item_Cannot_Add_To_Completed_Sprint), 'The exception message should match.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, afterSprintItems.size(), 'There should be one sprint item.');
        System.assertEquals(backlogItem.Id, afterSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint0.Id, afterSprintItems[0].Sprint__c, 'The sprint ID should match.');
    }

    static testMethod void backlogItem_update_single_deleteSprintItem_notCompleted() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint.Id);
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, beforeSprintItems.size(), 'There should be one sprint item before the update.');
        System.assertEquals(backlogItem.Id, beforeSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, beforeSprintItems[0].Sprint__c, 'The sprint ID should match.');

        Test.startTest();

            backlogItem.Current_Sprint__c = null;

            try {
                update backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(0, afterSprintItems.size(), 'There should be no sprint items.');
    }

    static testMethod void backlogItem_update_single_deleteSprintItem_completed() {
        Sprint__c sprint = new Sprint__c(Name = 'Test Sprint 0', Status__c = SprintModel.NOT_STARTED_STATUS);
        insert sprint;

        Backlog__c backlogItem = new Backlog__c(Current_Sprint__c = sprint.Id);
        insert backlogItem;

        List<Sprint_Item__c> beforeSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, beforeSprintItems.size(), 'There should be one sprint item before the update.');
        System.assertEquals(backlogItem.Id, beforeSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, beforeSprintItems[0].Sprint__c, 'The sprint ID should match.');

        sprint.Status__c = SprintModel.COMPLETED_STATUS;
        update sprint;

        Test.startTest();

            backlogItem.Current_Sprint__c = null;

            try {
                update backlogItem;
            } catch (Exception e) {
                System.assert(false, 'No exceptions should be thrown.');
            }

        Test.stopTest();

        List<Sprint_Item__c> afterSprintItems = [
            SELECT Backlog__c, Sprint__c 
            FROM Sprint_Item__c
        ];
        System.assertEquals(1, afterSprintItems.size(), 'There should be one sprint item.');
        System.assertEquals(backlogItem.Id, afterSprintItems[0].Backlog__c, 'The backlog item ID should match.');
        System.assertEquals(sprint.Id, afterSprintItems[0].Sprint__c, 'The sprint ID should match.');
    }
}