mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/GA_Metrics__c/GA_Metrics__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds data to send to Google Analytics</description>
    <label>GA Metrics</label>
</CustomObject>

mywork/force-app/main/default/objects/GA_Metrics__c/fields/Data1__c.field-meta.xml
<CustomField>
    <fullName>Data1__c</fullName>
    <label>Data1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/TestTrackingFrameController.cls
@isTest
private class TestTrackingFrameController {

    static testMethod void setAction() {
        ApexPages.StandardController sc = new ApexPages.StandardController( new Backlog__c() );
        TrackingFrameController trackingController = new TrackingFrameController( sc );
        System.assertEquals(Backlog__c.sObjectType.getDescribe().getLocalName(), trackingController.actionTarget, 'The action should be set to the local name of the sObject');
    }

    static testMethod void testGetTrackingData() {
        GA_Metrics__c metric = GA_Metrics__c.getInstance();
        metric.Data1__c = MetricsServices.NEW_ACTION_TYPE + MetricsServices.ACTION_SEPARATOR + 'Fake_Object__c';
        insert metric;

        Test.startTest();
            List<Map<String,String>> result =
                TrackingFrameController.getTrackingData( Schema.SobjectType.Backlog__c.getLocalName() );
        Test.stopTest();

        System.assertEquals(0, result.size(), 'There should not be any metrics fro Backlog__c' );
    }
}