mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user story that the defect is associated to.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Backlog</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether or not this component has been deleted in the source instance.</inlineHelpText>
    <label>Documented As Deleted</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Deploy_Manually__c.field-meta.xml
<CustomField>
    <fullName>Deploy_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Set to true if this component should be deployed manually</inlineHelpText>
    <label>Deploy Manually</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/Build_Component__c.object-meta.xml
<CustomObject>
    <label>Build Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Build Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build_Component__c/fields/Backlog_Component__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Component</label>
    <referenceTo>Backlog_Component__c</referenceTo>
    <relationshipLabel>Build Componnets</relationshipLabel>
    <relationshipName>Build_Componnets</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Build Components</relationshipLabel>
    <relationshipName>Build_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <label>Instance Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Is_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Is_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this component will be deleted</description>
    <inlineHelpText>Indicates that this component will be deleted</inlineHelpText>
    <label>Is Deletion?</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Is_Manual_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Is_Manual_Deployment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this component was marked to be deploymed manually</description>
    <label>Is Manual Deployment</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Documented</fullName>
            </value>
            <value>
                <fullName>Undocumented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Child Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <label>Instance Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/AssemblerManifestRecord.cls
public virtual with sharing class AssemblerManifestRecord {

    public static final String DOCUMENTED = 'Documented';
    public static final String UNDOCUMENTED = 'Undocumented';
    public static final String REMOVED = 'Removed';

    public Id backlogId {get; set;}
    public String backlogStatus {get; set;}
    public String backlogName {get; set;}
    public String instance {get; set;}
    public String notes {get; set;}
    public Boolean deployManually {get; set;}
    public Boolean isDeletion {get; set;}
    public Boolean isRemoved {get; set;}
    public Boolean savedIsRemovedValue {get; set;}
    public Boolean selected {get; set;}

    protected Id componentId;
    protected Build_Component__c buildComponent;

    public AssemblerManifestRecord(Backlog_Component__c backlogComponent) {
        this.backlogId          = backlogComponent.Backlog__r.Id;
        this.backlogStatus      = backlogComponent.Backlog__r.Status__c;
        this.backlogName        = backlogComponent.Backlog__r.Name;
        this.instance           = backlogComponent.Source_Instance__r.Name;
        this.notes              = backlogComponent.Notes__c;
        this.componentId        = backlogComponent.Component__c;
        this.deployManually     = backlogComponent.Deploy_Manually__c;

        this.buildComponent = new Build_Component__c(Backlog_Component__c = backlogComponent.Id,
         Type__c = DOCUMENTED, Instance_Name__c = instance, Component__c = backlogComponent.Component__c);
        this.buildComponent.Component_Name__c   = ComponentServices.getComponentName(backlogComponent.Component__r);
        this.buildComponent.Component_Type__c   = backlogComponent.Component__r.Type__c;
        this.buildComponent.Parent_Component__c = backlogComponent.Component__r.Parent_Component__r.Name;
        this.buildComponent.Is_Deletion__c = backlogComponent.Deleted__c;
        this.buildComponent.Is_Manual_Deployment__c = deployManually;
        
        this.isDeletion = backlogComponent.Deleted__c;

        this.selected = false;
        this.isRemoved = deployManually;
        this.savedIsRemovedValue = this.isRemoved;
        buildComponent.Backlog_Component__r = null;
        buildComponent.Component__r = null;
    }

    public AssemblerManifestRecord(ComponentSearchWrapper undocumentedComponent) {
        this.instance                       = undocumentedComponent.environment;
        this.componentId                    = undocumentedComponent.component.Id;
        this.deployManually                 = false;

        buildComponent                      = new Build_Component__c( Type__c = UNDOCUMENTED);
        buildComponent.Component_Name__c    = ComponentServices.getComponentName(undocumentedComponent.component);
        buildComponent.Component_Type__c    = undocumentedComponent.component.Type__c;
        buildComponent.Parent_Component__c  = undocumentedComponent.component.Parent_Component__r.Name;
        buildComponent.Instance_Name__c     = instance;
        buildComponent.Component__c         = undocumentedComponent.component.Id;
        buildComponent.Is_Deletion__c = undocumentedComponent.isDeleted;

        undocumentedComponent.existsOnCurrentBacklog = true;
        selected = false;
        isDeletion = buildComponent.Is_Deletion__c;
        isRemoved = false;
        // Since the component wasn't here before, it is as if it was removed at the last save.
        // By having isRemoved = false and having savedIsRemovedValue = true, we can show the user
        // that there has been a change since the last save.
        this.savedIsRemovedValue = true; 
        buildComponent.Backlog_Component__r = null;
        buildComponent.Component__r = null;
    }

    public AssemblerManifestRecord(Build_Component__c buildComponent) {
        this.buildComponent = buildComponent;
        if (buildComponent.Backlog_Component__c != null) {
            this.backlogId          = buildComponent.Backlog_Component__r.Backlog__r.Id;
            this.backlogStatus      = buildComponent.Backlog_Component__r.Backlog__r.Status__c;
            this.backlogName        = buildComponent.Backlog_Component__r.Backlog__r.Name;
            this.instance           = buildComponent.Backlog_Component__r.Source_Instance__r.Name;
            this.notes              = buildComponent.Backlog_Component__r.Notes__c;
            this.buildComponent.Component_Name__c   = ComponentServices.getComponentName(buildComponent.Backlog_Component__r.Component__r);
            this.buildComponent.Component_Type__c   = buildComponent.Backlog_Component__r.Component__r.Type__c;
            this.buildComponent.Parent_Component__c = buildComponent.Backlog_Component__r.Component__r.Parent_Component__r.Name;
            this.componentId        = buildComponent.Backlog_Component__r.Component__c;
            this.deployManually     = buildComponent.Is_Manual_Deployment__c;
        } else {
            this.componentId        = buildComponent.Component__c;
            this.instance           = buildComponent.Instance_Name__c;
            this.deployManually     = false;
        }
        this.isRemoved = (buildComponent.Type__c == REMOVED
            || (!getIsUndocumented() && buildComponent.Backlog_Component__c == null));
        this.savedIsRemovedValue = this.isRemoved;
        this.isDeletion = buildComponent.Is_Deletion__c;
        this.selected = !isRemoved;
        buildComponent.Backlog_Component__r = null;
        buildComponent.Component__r = null;
    }

    public virtual Boolean getIsDocumented() {
        return buildComponent.Type__c == DOCUMENTED || buildComponent.Type__c == REMOVED;
    }

    public Boolean getIsUndocumented() {
        return buildComponent.Type__c == UNDOCUMENTED;
    }

    public virtual String getKey() {
        String instance = (instance == null) ? '' : instance;
        return instance + '|' + String.valueOf( componentId );
    }

    public virtual String getDocumentedKey() {
        return backlogName == null ? getKey() : getKey() + '|' + backlogName;
    }

    public virtual Build_Component__c getBuildComponent() {
        if (isRemoved) {
            buildComponent.Type__c = AssemblerManifestRecord.REMOVED;
        } else if (getIsDocumented()) {
            buildComponent.Type__c = AssemblerManifestRecord.DOCUMENTED;
        }
        return buildComponent;
    }

    public Id getComponentId() {
        return this.componentId;
    }

    public String getName() {
        return buildComponent.Component_Name__c;
    }

    public String getType() {
        return buildComponent.Component_Type__c;
    }

    public String getParent() {
        return buildComponent.Parent_Component__c;
    }

    public virtual AssemblerManifestRecord deepClone() {
        AssemblerManifestRecord clonedRecord = this.clone();
        clonedRecord.buildComponent = getBuildComponent().clone( false, true );
        return clonedRecord;
    }
}