mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Include_Entire_Profile__c.field-meta.xml
<CustomField>
    <fullName>Include_Entire_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the entire profile should be deployed</description>
    <inlineHelpText>Indicates that the entire profile should be deployed</inlineHelpText>
    <label>Include Entire Profile</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Backlog Components (Profile)</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Permission__c.field-meta.xml
<CustomField>
    <fullName>Profile_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profile Permission</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Source_Sandbox__c</fullName>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Sandbox</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/ComponentDocProfile.cls
/**
* Represents a documented profile in component documetation
*/
public class ComponentDocProfile implements Comparable {
    @AuraEnabled
    public Boolean includeOnlyDocumentedComponents { get; set; }
    @AuraEnabled
    public Boolean includeEntireProfile { get; set; }
    @AuraEnabled
    public Boolean selected { get; set; }
    @AuraEnabled
    public Id profileComponentId { get; set; }
    @AuraEnabled
    public String instanceName { get; set; }
    @AuraEnabled
    public String profileName { get; set; }
    @AuraEnabled
    public String selectedPermissions { get; set;}

    private Backlog_Component__c backlogComponent;

    public ComponentDocProfile(Backlog_Component__c backlogComponent) {
        if (backlogComponent.Profile_Permission__c) {
            this.profileName = ComponentServices.getComponentName(backlogComponent.Profile__r);
            this.profileComponentId = backlogComponent.Profile__c;
            this.includeOnlyDocumentedComponents = true;
        } else {
            this.profileName = ComponentServices.getComponentName(backlogComponent.Component__r);
            this.profileComponentId = backlogComponent.Component__c;
            this.includeOnlyDocumentedComponents = false;
        }

        this.includeEntireProfile = backlogComponent.Include_Entire_Profile__c;

        this.selected = true;
        this.instanceName = String.isEmpty(backlogComponent.Source_Instance__r.Name) ?
                backlogComponent.Source_Sandbox__c : backlogComponent.Source_Instance__r.Name;
        this.backlogComponent = new Backlog_Component__c(Id=backlogComponent.Id, Backlog__c=backlogComponent.Backlog__c);
        this.backlogComponent.Source_Sandbox__c = this.instanceName;

        if (backlogComponent.Id == null) {
            this.backlogComponent.Component__c=profileComponentId;
        } else if (String.isBlank(instanceName) && backlogComponent.Component__c != profileComponentId) {
            //For legacy profile cleanup, create a new component that looks up to the profile component so all others can be deleted
            this.backlogComponent = backlogComponent.clone(false, true);
            this.backlogComponent.Component__c=profileComponentId;
        }

        this.backlogComponent.Source_Instance__c = backlogComponent.Source_Instance__c;

        this.selectedPermissions = ProfilePermissions.getProfilePermissionsString(backlogComponent);
    }

    public ComponentDocProfile(Backlog_Component__c backlogComponent, Boolean includeOnlyDocumentedComponents) {
        this(backlogComponent);
        if (includeOnlyDocumentedComponents) {
            this.includeOnlyDocumentedComponents = includeOnlyDocumentedComponents;
            backlogComponent.Profile_Permission__c = true;
            backlogComponent.Profile__c = profileComponentId;
        }
    }

    @AuraEnabled
    public String getBacklogComponentId() {
        return backlogComponent.Id;
    }

    /**
    * @throws ALMException
    */
    public Backlog_Component__c getBacklogComponent() {
        backlogComponent.Profile_Permission__c = includeOnlyDocumentedComponents;
        backlogComponent.Profile__c = profileComponentId;
        backlogComponent.Include_Entire_Profile__c = includeEntireProfile;

        ProfilePermissions.setProfilePermissionsData(backlogComponent, selectedPermissions);

        //TODO: discuss need of setting the Source_Sandbox__c field with Jon

        return backlogComponent;
    }

    @AuraEnabled
    public String getKey() {
        String instance = (instanceName == null) ? '' : instanceName;
        return instance + '|' + String.valueOf( profileComponentId );
    }

    public Integer compareTo(Object o) {
        ComponentDocProfile p = (ComponentDocProfile) o;

        if( profileName == p.ProfileName) {
            return 0;
        }
        else if( profileName < p.ProfileName) {
            return -1;
        }
        else {
            return 1;
        }
    }

}