mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_1__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_1__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_2__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_2__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestBacklogComponentTrigger.cls
@isTest
private class TestBacklogComponentTrigger {
    static testMethod void removeDeletedBacklogComponentsFromProfileData_noDelete_unrelated() {
        String testProfileComponentName = 'Test Profile Component Name';
        String testOtherComponentName = 'Test Other Component Name';
        String testComponentType = ComponentServices.APEX_ALM_NAME;
        String profileJSON = generateProfileJSON(
            testProfileComponentName, 
            new Set<String>{ 'Test Instance' }, 
            new Map<String, Set<String>>{ 
                ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType) => new Set<String>{ testOtherComponentName }
            }
        );

        Backlog__c backlogItem = new Backlog__c();
        insert backlogItem;
        Component__c profileComponent = new Component__c(Name = testProfileComponentName, Type__c = 'Profile');
        Component__c otherComponent = new Component__c(Name = 'Test Unrelated Component Name', Type__c = testComponentType);
        insert new List<Component__c>{ profileComponent, otherComponent };
        Backlog_Component__c profileBacklogComponent = new Backlog_Component__c(
            Backlog__c = backlogItem.Id, Component__c = profileComponent.Id, Component__r = profileComponent, 
            Profile_Data_1__c = profileJSON
        );
        Backlog_Component__c deletedBacklogComponent = new Backlog_Component__c(
            Backlog__c = backlogItem.Id, Component__c = otherComponent.Id, Component__r = otherComponent
        );
        insert new List<Backlog_Component__c>{ profileBacklogComponent, deletedBacklogComponent };

        Test.startTest();

            delete deletedBacklogComponent;

        Test.stopTest();

        List<Backlog_Component__c> backlogComponents = [
            SELECT Component__r.Name, Profile_Data_1__c, Profile_Data_2__c, Source_Instance__r.Name 
            FROM Backlog_Component__c
        ];

        System.assertEquals(1, backlogComponents.size(), 'There should be one backlog component remaining');
        System.assertEquals(profileComponent.Name, backlogComponents[0].Component__r.Name, 'The backlog component related component name should match.');

        ProfilePermissions resultPermissions = ProfilePermissions.valueOf(backlogComponents[0]);
        ProfilePermissions.Section resultSection = resultPermissions.sections[0];
        System.assertEquals(ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType), resultSection.apiName, 'The section API name should match.');
        System.assertEquals(1, resultSection.permissions.size(), 'There should be one permission.');
        System.assertEquals(testOtherComponentName, resultSection.permissions[0], 'The permission name should be correct.');
    }

    static testMethod void removeDeletedBacklogComponentsFromProfileData_singleBacklogSinglePermission() {
        String testProfileComponentName = 'Test Profile Component Name';
        String testOtherComponentName = 'Test Other Component Name';
        String testComponentType = ComponentServices.APEX_ALM_NAME;
        String profileJSON = generateProfileJSON(
            testProfileComponentName, 
            new Set<String>{ 'Test Instance' }, 
            new Map<String, Set<String>>{
                ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType) => new Set<String>{ testOtherComponentName }
            }
        );

        Backlog__c backlogItem = new Backlog__c();
        insert backlogItem;
        Component__c profileComponent = new Component__c(Name = testProfileComponentName, Type__c = 'Profile');
        Component__c otherComponent = new Component__c(Name = testOtherComponentName, Type__c = testComponentType);
        insert new List<Component__c>{ profileComponent, otherComponent };
        Backlog_Component__c profileBacklogComponent = new Backlog_Component__c(
            Backlog__c = backlogItem.Id, Component__c = profileComponent.Id, Component__r = profileComponent, 
            Profile_Data_1__c = profileJSON
        );
        Backlog_Component__c deletedBacklogComponent = new Backlog_Component__c(
            Backlog__c = backlogItem.Id, Component__c = otherComponent.Id, Component__r = otherComponent
        );
        insert new List<Backlog_Component__c>{ profileBacklogComponent, deletedBacklogComponent };

        Test.startTest();

            delete deletedBacklogComponent;

        Test.stopTest();

        List<Backlog_Component__c> backlogComponents = [
            SELECT Component__r.Name, Profile_Data_1__c, Profile_Data_2__c, Source_Instance__r.Name 
            FROM Backlog_Component__c
        ];

        System.assertEquals(1, backlogComponents.size(), 'There should be one backlog component remaining');
        System.assertEquals(profileComponent.Name, backlogComponents[0].Component__r.Name, 'The backlog component related component name should match.');

        ProfilePermissions resultPermissions = ProfilePermissions.valueOf(backlogComponents[0]);
        ProfilePermissions.Section resultSection = resultPermissions.sections[0];
        System.assertEquals(ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType), resultSection.apiName, 'The section API name should match.');
        System.assert(resultSection.permissions.isEmpty(), 'The section permissions should be empty.');
    }

    static testMethod void removeDeletedBacklogComponentsFromProfileData_multipleBacklogMultiplePermission() {
        String testComponentType = ComponentServices.APEX_ALM_NAME;

        String testProfileComponentName0 = 'Test Profile Component Name 0';
        String testOtherComponentName0 = 'Test Other Component Name 0';
        String testProfileComponentName1 = 'Test Profile Component Name 1';
        String testOtherComponentName1 = 'Test Other Component Name 1';

        String profileJSON0 = generateProfileJSON(
            testProfileComponentName0, 
            new Set<String>{ 'Test Instance' }, 
            new Map<String, Set<String>>{ 
                ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType) => new Set<String>{ 
                    testOtherComponentName0, 
                    testOtherComponentName1
                }
            }
        );

        String profileJSON1 = generateProfileJSON(
            testProfileComponentName1, 
            new Set<String>{ 'Test Instance' }, 
            new Map<String, Set<String>>{ 
                ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType) => new Set<String>{ 
                    testOtherComponentName0, 
                    testOtherComponentName1
                }
            }
        );

        Backlog__c backlogItem0 = new Backlog__c();
        Backlog__c backlogItem1 = new Backlog__c();
        insert new List<Backlog__c>{ backlogItem0, backlogItem1 };

        Component__c profileComponent0 = new Component__c(Name = testProfileComponentName0, Type__c = 'Profile');
        Component__c profileComponent1 = new Component__c(Name = testProfileComponentName1, Type__c = 'Profile');
        Component__c otherComponent0 = new Component__c(Name = testOtherComponentName0, Type__c = testComponentType);
        Component__c otherComponent1 = new Component__c(Name = testOtherComponentName1, Type__c = testComponentType);

        insert new List<Component__c>{ profileComponent0, profileComponent1, otherComponent0, otherComponent1 };
        Backlog_Component__c profileBacklogComponent0 = new Backlog_Component__c(
            Backlog__c = backlogItem0.Id, Component__c = profileComponent0.Id, Component__r = profileComponent0, 
            Profile_Data_1__c = profileJSON0
        );
        Backlog_Component__c profileBacklogComponent1 = new Backlog_Component__c(
            Backlog__c = backlogItem1.Id, Component__c = profileComponent1.Id, Component__r = profileComponent1, 
            Profile_Data_1__c = profileJSON1
        );
        Backlog_Component__c deletedBacklogComponent0 = new Backlog_Component__c(
            Backlog__c = backlogItem0.Id, Component__c = otherComponent0.Id, Component__r = otherComponent0
        );
        Backlog_Component__c deletedBacklogComponent1 = new Backlog_Component__c(
            Backlog__c = backlogItem1.Id, Component__c = otherComponent1.Id, Component__r = otherComponent1
        );
        insert new List<Backlog_Component__c>{ 
            profileBacklogComponent0, profileBacklogComponent1, 
            deletedBacklogComponent0, deletedBacklogComponent1 
        };

        Test.startTest();

            delete new List<Backlog_Component__c>{ deletedBacklogComponent0, deletedBacklogComponent1 };

        Test.stopTest();

        List<Backlog_Component__c> backlogComponents = [
            SELECT Component__r.Name, Profile_Data_1__c, Profile_Data_2__c, Source_Instance__r.Name 
            FROM Backlog_Component__c
            ORDER BY Component__r.Name ASC
        ];

        System.assertEquals(2, backlogComponents.size(), 'There should be one backlog components remaining');
        System.assertEquals(profileComponent0.Name, backlogComponents[0].Component__r.Name, 'The backlog component related component name should match.');
        System.assertEquals(profileComponent1.Name, backlogComponents[1].Component__r.Name, 'The backlog component related component name should match.');

        ProfilePermissions resultPermissions0 = ProfilePermissions.valueOf(backlogComponents[0]);
        ProfilePermissions.Section resultSection0 = resultPermissions0.sections[0];
        System.assertEquals(ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType), resultSection0.apiName, 'The section API name should match.');
        System.assertEquals(1, resultSection0.permissions.size(), 'The section permissions should contain one permission.');
        System.assertEquals(testOtherComponentName1, resultSection0.permissions[0], 'The section permissions should contain the correct permission.');

        ProfilePermissions resultPermissions1 = ProfilePermissions.valueOf(backlogComponents[1]);
        ProfilePermissions.Section resultSection1 = resultPermissions1.sections[0];
        System.assertEquals(ProfileServices.COMPONENT_TYPE_TO_CATEGORY.get(testComponentType), resultSection1.apiName, 'The section API name should match.');
        System.assertEquals(1, resultSection1.permissions.size(), 'The section permissions should contain one permission.');
        System.assertEquals(testOtherComponentName0, resultSection1.permissions[0], 'The section permissions should contain the correct permission.');
    }

    private static String generateProfileJSON(String profileName, Set<String> instanceNames, Map<String, Set<String>> sectionToPermissions) {
        String profileJSON = '{"name" : "' + profileName + '", "instances" : [';

        for (String instanceName : instanceNames) {
            if (!profileJSON.endsWith('[')) {
                profileJSON += ', ';
            }
            profileJSON += '"' + instanceName + '"';
        }

        profileJSON += '], "sections" : [';

        for (String section : sectionToPermissions.keySet()) {
            if (!profileJSON.endsWith('[')) {
                profileJSON += ', ';
            }

            profileJSON += '{"apiName" : "' + section + '", "permissions" : [';

            for (String permission : sectionToPermissions.get(section)) {
                if (!profileJSON.endsWith('[')) {
                    profileJSON += ', ';
                }
                profileJSON += '"' + permission + '"';
            }

            profileJSON += ']}';
        }

        profileJSON += ']}';

        return profileJSON;
    }
}