mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Source_Sandbox__c</fullName>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Sandbox</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestUpdateExistingBkgComponentRecords.cls
@isTest
private class TestUpdateExistingBkgComponentRecords {

    static testMethod void testBatch() {
        Backlog__c bklg = new Backlog__c();
        insert bklg;

        Component__c comp = new Component__c(Name='Foo', Type__c='Apex Class');
        insert comp;

        List<Backlog_Component__c> backlogComps = new List<Backlog_Component__c>();

        // Insert 200 backlog component records to simulate one batch execution
        for (Integer i=0; i<199; i++) {
            Backlog_Component__c bc = new Backlog_Component__c();
            bc.Backlog__c = bklg.Id;
            bc.Component__c = comp.Id;

            if (Math.mod(i, 2) == 0) {
                bc.Source_Sandbox__c = 'sandbox';
            } else {
                bc.Source_Sandbox__c = 'prod';
            }

            backlogComps.add(bc);
        }

        // Create record with source sandbox value empty
        Backlog_Component__c bc2 = new Backlog_Component__c();
        bc2.Backlog__c = bklg.Id;
        bc2.Component__c = comp.Id;
        bc2.Source_Sandbox__c = '';
        backlogComps.add(bc2);

        insert backlogComps;

        Integer errors = [Select count() from Backlog_Component__c Where Source_Instance__c = ''];
        System.assertEquals(200, errors, 'No backlog component record should have its source instance set');

        // execute the batch
        Test.startTest();
            UpdateExistingBacklogComponentRecords batch = new UpdateExistingBacklogComponentRecords();
            ID batchProcessid = Database.executeBatch(batch);
        Test.stopTest();

        Integer emptyCount = [Select count() from Backlog_Component__c Where Source_Instance__c = ''];
        System.assertEquals(1, emptyCount, 'There should be 1 backlog component record with no source instance value');

        List<Instances__c> instanceList = [Select Name from Instances__c Order By Name Asc];
        System.assertEquals(2, instanceList.size(), 'There should be 2 Instance records.');
        System.assertEquals('prod', instanceList.get(0).Name.toLowerCase(), 'There should be 1 Instance record called Prod.');
        System.assertEquals('sandbox', instanceList.get(1).Name.toLowerCase(), 'There should be 1 Instance record called Sandbox.');
    }
}