mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Backlog Components (Profile)</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_1__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_1__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_2__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_2__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Permission__c.field-meta.xml
<CustomField>
    <fullName>Profile_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profile Permission</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/Build_Component__c.object-meta.xml
<CustomObject>
    <label>Build Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Build Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build_Component__c/fields/Backlog_Component__c.field-meta.xml
<CustomField>
    <fullName>Backlog_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog Component</label>
    <referenceTo>Backlog_Component__c</referenceTo>
    <relationshipLabel>Build Componnets</relationshipLabel>
    <relationshipName>Build_Componnets</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Build Components</relationshipLabel>
    <relationshipName>Build_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Profile_Data_1__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_1__c</fullName>
    <description>Stores the aggregated profile selection data</description>
    <label>Profile Data 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Profile_Data_2__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_2__c</fullName>
    <description>Stores the aggregated profile selection data</description>
    <label>Profile Data 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Build_Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Documented</fullName>
            </value>
            <value>
                <fullName>Undocumented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Child Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Source_Instances__c.field-meta.xml
<CustomField>
    <fullName>Source_Instances__c</fullName>
    <label>Source Instances</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
            <value>
                <fullName>Visualforce Page</fullName>
            </value>
            <value>
                <fullName>Visualforce Tab</fullName>
            </value>
            <value>
                <fullName>Web Tab</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/Profile_Permission_Data__mdt.object-meta.xml
<CustomObject>
    <label>Profile Permission Data</label>
    <pluralLabel>Profile Permission Data</pluralLabel>
</CustomObject>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Has_Sub_Sections__c.field-meta.xml
<CustomField>
    <fullName>Has_Sub_Sections__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls if this Category is has sub sections. Sub sections are broken down by Standard / Custom (only applies for categories)</description>
    <inlineHelpText>Controls if this Category is has sub sections. Sub sections are broken down by Standard / Custom (only applies for categories)</inlineHelpText>
    <label>Has Sub Sections</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <label>Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Is_Category__c.field-meta.xml
<CustomField>
    <fullName>Is_Category__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Category</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Option_Label__c.field-meta.xml
<CustomField>
    <fullName>Option_Label__c</fullName>
    <description>stores the name of the option, for example 'Modify All Data'</description>
    <inlineHelpText>stores the name of the option, for example 'Modify All Data'</inlineHelpText>
    <label>Option Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Option_Value__c.field-meta.xml
<CustomField>
    <fullName>Option_Value__c</fullName>
    <description>stores the API name of the option, for example 'modifyAllData'</description>
    <inlineHelpText>stores the API name of the option, for example 'modifyAllData'</inlineHelpText>
    <label>Option Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Profile_Permission_Data__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Controls the order that the section or field is shown</description>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/classes/ProfileServices.cls
public with sharing class ProfileServices {

    public static final String PROFILE_NAME_INSTANCE_DELIMETER = '~|~';
    public static final String APEX_API_NAME = 'classAccesses';
    public static final String LAYOUT_API_NAME = 'layoutAssignments';
    public static final String FIELD_API_NAME = 'fieldPermissions';
    public static final String OBJECT_API_NAME = 'objectPermissions';
    public static final String RECORD_TYPE_API_NAME = 'recordTypeVisibilities';
    public static final String TABS_API_NAME = 'tabVisibilities';

    public static final Map<String, String> CATEGORY_TO_COMPONENT_TYPE = new Map<String, String> {
          'applicationVisibilities' => 'Application',
          APEX_API_NAME => ComponentServices.APEX_ALM_NAME,
          'pageAccesses' => 'Visualforce Page',
          TABS_API_NAME => 'Custom Object Tab|Web Tab|Visualforce Tab',
          FIELD_API_NAME => ComponentServices.OBJECT_ALM_NAME,
          LAYOUT_API_NAME => ComponentServices.LAYOUT_ALM_NAME,
          OBJECT_API_NAME => ComponentServices.OBJECT_ALM_NAME,
          RECORD_TYPE_API_NAME => ComponentServices.RECORD_TYPE_ALM_NAME
    };

    public static final Map<String, String> COMPONENT_TYPE_TO_CATEGORY = new Map<String, String> {
          'Application' => 'applicationVisibilities',
          ComponentServices.APEX_ALM_NAME => APEX_API_NAME,
          ComponentServices.LAYOUT_ALM_NAME => LAYOUT_API_NAME,
          ComponentServices.FIELD_ALM_NAME => FIELD_API_NAME,
          'Visualforce Page' => 'pageAccesses',
          'Custom Object Tab' => TABS_API_NAME,
          'Web Tab' => TABS_API_NAME,
          'Visualforce Tab' => TABS_API_NAME,
          ComponentServices.OBJECT_ALM_NAME => OBJECT_API_NAME,
          ComponentServices.RECORD_TYPE_ALM_NAME => RECORD_TYPE_API_NAME
    };

    public static List<Backlog_Component__c> getProfileBacklogComponents(String backlogItemId) {
        return [
            SELECT Id, Component__c, Profile__c, Source_Instance__c, Profile_Data_1__c, Profile_Data_2__c
            FROM Backlog_Component__c
            WHERE Backlog__c = :backlogItemId
            AND  (Profile_Permission__c = true
            OR Component__r.Type__c = 'Profile')
        ];
    }

    public static ProfileTemplate generateProfileTemplate(String instanceName) {
        List<Profile_Permission_Data__mdt> categories = getProfilePermissionData(true);

        List<Profile_Permission_Data__mdt> options = getProfilePermissionData(false);

        Map<String, List<ProfileTemplate.Permission>> categoryToPermissions = new Map<String, List<ProfileTemplate.Permission>>();

        for(Profile_Permission_Data__mdt option : options) {
            if (!categoryToPermissions.containsKey(option.Category__c)) {
                categoryToPermissions.put(option.Category__c, new List<ProfileTemplate.Permission>());
            }
            categoryToPermissions.get(option.Category__c).add( new ProfileTemplate.Permission(option) );
        }

        Map<String, List<ProfileTemplate.Permission>> typeToComponent = mapPermissionsByComponentType(instanceName);

        List<ProfileTemplate.Section> sections = new List<ProfileTemplate.Section>();

        for (Profile_Permission_Data__mdt category : categories) {
            ProfileTemplate.Section section = new ProfileTemplate.Section(category);
            sections.add(section);

            if (categoryToPermissions.containsKey(section.label)) {
                section.addPermissions( categoryToPermissions.get(section.label) );
            }

            if (CATEGORY_TO_COMPONENT_TYPE.containsKey( section.apiName )) {
                for (String componentType : CATEGORY_TO_COMPONENT_TYPE.get( section.apiName ).split('\\|')) {
                    if (typeToComponent.containsKey( componentType )) {
                        section.addPermissions( typeToComponent.get(componentType) );
                    }
                }
            }
            section.sort();
        }

        return new ProfileTemplate(instanceName, sections);
    }

    public static List<Profile_Permission_Data__mdt> getProfilePermissionData(Boolean getCategories) {
        return [
            SELECT Id, DeveloperName, Is_Category__c, Help_Text__c, Category__c, Order__c, Option_Label__c, Option_Value__c, Has_Sub_Sections__c
            FROM Profile_Permission_Data__mdt
            WHERE Is_Category__c = :getCategories
            ORDER BY Order__c
        ];
    }

    public static ProfileTemplate retrieveProfileTemplate(String instanceName) {
        try {
            ProfileTemplate.ProfileTemplateState cachedState = new ProfileTemplate.ProfileTemplateState(instanceName);
            ProfileServices.getCache().getData( cachedState );

            return cachedState.getTemplate();
        } catch(State.StateException se) {
            System.debug(se.getMessage());
            return refreshProfileTemplateCache(instanceName);
        }
    }

    public static ProfileTemplate retrieveProfileTemplate(List<String> instanceNames) {
        List<ProfileTemplate> templatesToMerge = new List<ProfileTemplate>();
        for (String instanceName : instanceNames) {
            templatesToMerge.add(retrieveProfileTemplate(instanceName));
        }

        return ProfileTemplate.mergeTemplates(templatesToMerge);
    }

    @future
    public static void refreshProfileTemplateCacheInFuture(String instanceId) {
        Instances__c instance = InstanceServices.getInstance(instanceId);

        if (instance == null) {
            ALMLogServices.error(new ALMException('No instance id specified'), ALMLogServices.Application.SCAN);
            return;
        }

        refreshProfileTemplateCache(instance.Name);
    }

    public static ProfileTemplate refreshProfileTemplateCache(String instanceName) {

        ProfileTemplate template = generateProfileTemplate(instanceName);

        ProfileTemplate.ProfileTemplateState cachedState = new ProfileTemplate.ProfileTemplateState(template);
        try {
            ProfileServices.getCache().putData(cachedState);
        } catch (State.StateException stateException) {
            ALMLogServices.error(stateException, ALMLogServices.Application.SCAN);
        }

        return template;
    }

    /**
    * Retrieve the profile name from a provided build component.
    * @param buildComponent
    * @return String    Profile Name
    */
    public static String getProfileName(Build_Component__c buildComponent) {
        String profileName;

        if (!String.isBlank(buildComponent.Component_Name__c)) {
            profileName = buildComponent.Component_Name__c;
        }
        else if (!String.isBlank(buildComponent.Backlog_Component__r.Profile__r.Name)) {
            //check Backlog_Component__r.Profile__r for backwards compatibility. From now on the
            //component lookup should always be valid for profiles
            profileName = buildComponent.Backlog_Component__r.Profile__r.Name;
        } else {
            profileName = ComponentServices.getComponentName(buildComponent.Component__r);
        }

        return profileName;
    }

    /**
    * Maps component by permission category and API name, removing the instance name.
    * @param components - The components to map.
    * @return Map<String, Set<String>> - A map of the components to the set of API permissions.
    */
    public static Map<String, Set<String>> filterComponents(List<ComponentSearchWrapper> components) {
        List<AssemblerManifestRecord> componentManifestRecords = new List<AssemblerManifestRecord>();
        for (ComponentSearchWrapper component : components) {
            componentManifestRecords.add(new AssemblerManifestRecord(component));
        }

        return filterComponents(componentManifestRecords);
    }

    /**
    * Maps component by permission category and API name, removing the instance name.
    * @param components - The components to map.
    * @return Map<String, Set<String>> - A map of the components to the set of API permissions.
    */
    public static Map<String, Set<String>> filterComponents(List<AssemblerManifestRecord> components) {
        Map<String, Set<String>> filteredMap = new Map<String, Set<String>>();
        Map<String, Set<String>> permissionMap = ProfileServices.getPermissionsMap(components);

        for (String section : permissionMap.keySet()) {
            filteredMap.put(section, new Set<String>());
            for (String permission : permissionMap.get(section)) {
                String parsedPermission = permission.split(ProfileServices.PROFILE_NAME_INSTANCE_DELIMETER)[0];
                filteredMap.get(section).add(parsedPermission);
            }
        }

        return filteredMap;
    }

   /**
    * Map components by permission category and api name
    * @param components
    * @return Map<String, Set<String>> map of profile section apiName => Set of api permissions
    */
    public static Map<String, Set<String>> getPermissionsMap(List<ComponentSearchWrapper> components) {
        List<List<String>> componentStrings = new List<List<String>>();

        for (ComponentSearchWrapper component : components) {
            componentStrings.add(new List<String> {component.componentName, component.component.Type__c, component.component.Parent_Component__r.Name, component.environment});
        }

        return getPermissionsMap(componentStrings);
    }

   /**
    * Map components by permission category and api name
    * @param components
    * @return Map<String, Set<String>> map of profile section apiName => Set of api permissions
    */
    public static Map<String, Set<String>> getPermissionsMap(List<AssemblerManifestRecord> components) {
        List<List<String>> componentStrings = new List<List<String>>();

        for (AssemblerManifestRecord component : components) {
            componentStrings.add(new List<String> {component.getName(), component.getType(), component.getParent(), component.instance});
        }

        return getPermissionsMap(componentStrings);
    }

    /**
    * Map components by permission category and api name
    * @param components   a list of the form [[component name, component type, component parent name, instance],...]
    * @return Map<String, Set<String>> map of profile section apiName => Set of api permissions
    */
    private static Map<String, Set<String>> getPermissionsMap(List<List<String>> components) {
        Map<String, Set<String>> sectionToPermissions = new Map<String, Set<String>>();

        for (List<String> component : components) {
            String name = component[0];
            String type = component[1];
            String parent = component[2];
            String instance = component[3];

            String apiNames = COMPONENT_TYPE_TO_CATEGORY.get(type);

            if (apiNames != null) {
                for (String sectionApiName : apiNames.split('\\|')) {
                    if (!sectionToPermissions.containsKey(sectionApiName)) {
                        sectionToPermissions.put(sectionApiName, new Set<String>());
                    }
                    String apiName = ProfileTemplate.getApiName(name, type, parent);

                    //For now we are only selecting the object if a field is documented.
                    if (type == ComponentServices.FIELD_ALM_NAME) {
                        apiName = parent;
                    }

                    sectionToPermissions.get(sectionApiName).add(apiName + PROFILE_NAME_INSTANCE_DELIMETER + instance);
                }
            }
        }

        return sectionToPermissions;
    }

    /**
    * Creates a map of Component__c.Type => List<ProfileTemplate.Permission> with the ProfileTemplate.Permission
    * representing a Component__c record
    */
    private static Map<String, List<ProfileTemplate.Permission>> mapPermissionsByComponentType(String instanceName) {
        Map<String, List<ProfileTemplate.Permission>> typeToComponent = new Map<String, List<ProfileTemplate.Permission>>();

        Set<String> componentTypes = new Set<String>();

        for(String componentType : CATEGORY_TO_COMPONENT_TYPE.values()) {
            componentTypes.addAll(componentType.split('\\|'));
        }

        for (Component__c component : [
            SELECT Name, Type__c, Parent_Component__c, Parent_Component__r.Name
            FROM Component__c
            WHERE Type__c IN :componentTypes
            AND Source_Instances__c INCLUDES (:instanceName)
         ]) {
            if (!typeToComponent.containsKey(component.Type__c)) {
                typeToComponent.put(component.Type__c, new List<ProfileTemplate.Permission>());
            }
            typeToComponent.get(component.Type__c).add( new ProfileTemplate.Permission(component) );
         }

         return typeToComponent;
    }

    public interface Cacheable {
        void putData(State.IStateful state);
        String getData(State.IStateful state);
    }

    public class StateCache implements Cacheable {

        /**
        * @throws a State.StateException
        */
        public void putData(State.IStateful templateState) {
            State.store(templateState);
        }

        public String getData(State.IStateful templateState) {
            State.retrieve(templateState);
            return templateState.serialize();
        }
    }

    public static Cacheable getCache() {
        //TODO: use platform cache if it is available
        return new StateCache();
    }
}