mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Business_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Value__c</fullName>
    <inlineHelpText>This is used to measure the business value.</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Dev_Effort__c.field-meta.xml
<CustomField>
    <fullName>Dev_Effort__c</fullName>
    <inlineHelpText>This is used to measure the development effort required to implement a story.  Represents a mix of technical complexity, work time, and even uncertainty bound to a story.  1 point represents a basic configuration change like creating a new field.</inlineHelpText>
    <label>Dev Effort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Main Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>Short summary of the backlog item</description>
    <inlineHelpText>Enter a short summary of the backlog item</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/User_Goal__c.field-meta.xml
<CustomField>
    <fullName>User_Goal__c</fullName>
    <description>This tells what the user wants to do.  What is their goal?  This is not for capturing WHY - that is in another field</description>
    <inlineHelpText>This tells what the user wants to do.  What is their goal?  This is not for capturing WHY - that is in another field</inlineHelpText>
    <label>I need</label>
    <type>TextArea</type>
</CustomField>

mywork/force-app/main/default/classes/BacklogItemModel.cls
public with sharing class BacklogItemModel {
    public String id {get; set;}
    public String title {get; set;}
    public String name {get; set;}
    public String status {get; set;}
    public String statusLabel {get; set;}
    public String type {get; set;}
    public Decimal value {get; set;}
    public Decimal effort {get; set;}
    public Decimal priority {get; set;}

    public Map<String, String> statusMap {
        get {
            if (statusMap == null) {
                statusMap = SObjectServices.getPicklistValueMap( Schema.sObjectType.Backlog__c.fields.Status__c );
            }
            return statusMap;
        }
        private set;
    }

    public BacklogItemModel(Backlog__c backlog) {
        id           = backlog.Id;
        name         = backlog.Name;
        type         = backlog.RecordType.Name;
        status       = backlog.Status__c;
        statusLabel  = statusMap.containsKey(status) ? statusMap.get(status) : status;
        title        = String.isNotBlank( backlog.Summary__c ) ? backlog.Summary__c : backlog.User_Goal__c;
        effort       = backlog.Dev_Effort__c;
        value        = backlog.Business_Value__c;
        priority     = backlog.Priority__c;
    }
}