mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicate the persona, which gives the user's perspective.  Who is it that wants/needs this story to be implemented</description>
    <inlineHelpText>Indicate the persona, which gives the user's perspective.  Who is it that wants/needs this story to be implemented</inlineHelpText>
    <label>As a(n)</label>
    <referenceTo>Persona__c</referenceTo>
    <relationshipName>Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/User_Goal__c.field-meta.xml
<CustomField>
    <fullName>User_Goal__c</fullName>
    <description>This tells what the user wants to do.  What is their goal?  This is not for capturing WHY - that is in another field</description>
    <inlineHelpText>This tells what the user wants to do.  What is their goal?  This is not for capturing WHY - that is in another field</inlineHelpText>
    <label>I need</label>
    <type>TextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Source_Sandbox__c</fullName>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Sandbox</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Persona__c/Persona__c.object-meta.xml
<CustomObject>
    <description>A persona identifies a type of user.  A persona may correspond to a specific organizational role or may cover multiple organizational roles that share goals.  Personas are analogous to the users you would find on a Use Case diagram in software development.</description>
    <label>Persona</label>
    <nameField>
        <label>Persona Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/TestAssetDuplicatePreventer.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAssetDuplicatePreventer {

    static testMethod void testInserts() {
        Persona__c p = new Persona__c(Name='Build Manager');
        insert p;
        
        Backlog__c s = new Backlog__c(Persona__c=p.Id, User_Goal__c='to do something');
        insert s;
        
        Component__c c = new Component__c(Name='Test 1', Type__c='Apex Class');
        insert c;
        
        Backlog_Component__c sm1 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c.Id, Source_Sandbox__c='sandbox');
        insert sm1;
        
        Backlog_Component__c dupe = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c.Id, Source_Sandbox__c='sandbox');
        
        try {
            insert dupe;
        } catch (Dmlexception e) {
            assertSingleComponent(e);
        }
    }
    
    static testMethod void testBulkInserts() {
        Persona__c p = new Persona__c(Name='Build Manager');
        insert p;
        
        Backlog__c s = new Backlog__c(Persona__c=p.Id, User_Goal__c='to do something');
        insert s;
        
        Component__c c1 = new Component__c(Name='Test 1', Type__c='Apex Class');
        Component__c c2 = new Component__c(Name='Test 2', Type__c='Apex Trigger');
        Component__c[] components = new Component__c[] {c1, c2};
        insert components;
        
        Backlog_Component__c sm1 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c1.Id, Source_Sandbox__c='sandbox');
        
        Backlog_Component__c sm2 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c2.Id, Source_Sandbox__c='sandbox');
        
        Backlog_Component__c[] members = new Backlog_Component__c[] {sm1, sm2};        
        insert members;
                
        Backlog_Component__c dupe1 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c1.Id, Source_Sandbox__c='sandbox');
        
        Backlog_Component__c dupe2 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c2.Id, Source_Sandbox__c='sandbox');
        
        Backlog_Component__c[] dupes = new Backlog_Component__c[] {dupe1, dupe2};        
        
        try {
            insert dupes;
        } catch (Dmlexception e) {
            assertMultipleComponents(e, 2);
        }
    }
    
    static testMethod void testUpdates() {
        Persona__c p = new Persona__c(Name='Build Manager');
        insert p;
        
        Backlog__c s = new Backlog__c(Persona__c=p.Id, User_Goal__c='to do something');
        insert s;
        
        Component__c c = new Component__c(Name='Test 1', Type__c='Apex Class');
        insert c;
        
        Backlog_Component__c sm1 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c.Id, Source_Sandbox__c='sandbox');
        insert sm1;
        
        sm1 = new Backlog_Component__c(Id=sm1.Id, Backlog__c=s.Id, Component__c=c.Id, Source_Sandbox__c='sandbox');
        
        try {
            update sm1;
        } catch (Dmlexception e) {
            assertSingleComponent(e);
        }
    }
    
    static testMethod void testBulkUpdates() {
        Persona__c p = new Persona__c(Name='Build Manager');
        insert p;
        
        Backlog__c s = new Backlog__c(Persona__c=p.Id, User_Goal__c='to do something');
        insert s;
        
        Component__c c1 = new Component__c(Name='Test 1', Type__c='Apex Class');
        Component__c c2 = new Component__c(Name='Test 2', Type__c='Apex Trigger');
        Component__c[] components = new Component__c[] {c1, c2};
        insert components;
        
        Backlog_Component__c sm1 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c1.Id, Source_Sandbox__c='sandbox');
        Backlog_Component__c sm2 = new Backlog_Component__c(Backlog__c=s.Id, Component__c=c2.Id, Source_Sandbox__c='sandbox');
        Backlog_Component__c[] members = new Backlog_Component__c[] {sm1, sm2};        
        insert members;
                
        sm1 = new Backlog_Component__c(Id=sm1.Id, Backlog__c=s.Id, Component__c=c1.Id, Source_Sandbox__c='sandbox');
        sm2 = new Backlog_Component__c(Id=sm2.Id, Backlog__c=s.Id, Component__c=c2.Id, Source_Sandbox__c='sandbox');
        Backlog_Component__c[] membersToUpdate = new Backlog_Component__c[] {sm1, sm2};        
        
        try {
            update membersToUpdate;
        } catch (Dmlexception e) {
            assertMultipleComponents(e, 2);
        }
    }
    
    static void assertSingleComponent(System.DMLException e) {
        System.assert(e.getNumDml() == 1);
    }
    
    static void assertMultipleComponents(DMLException e, Integer numberOfFailedRecords) {
        for (Integer i=0; i<numberOfFailedRecords; i++) {
            System.assert(e.getNumDml() == numberOfFailedRecords);
        }
    }
 
}