mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Backlog__c.field-meta.xml
<CustomField>
    <fullName>Custom_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a different backlog, all items are already assigned to the main backlog</errorMessage>
        <filterItems>
            <field>Custom_Backlog__c.Universal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Custom_Backlog__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Priority__c.field-meta.xml
<CustomField>
    <fullName>Custom_Priority__c</fullName>
    <label>Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Custom_Backlog__c/Custom_Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Custom_Backlog__c/fields/Universal__c.field-meta.xml
<CustomField>
    <fullName>Universal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Universal</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/classes/CustomBacklogModel.cls
public class CustomBacklogModel {

    public String name;
    public String customBacklogId;
    public String totalItems {get; set;}
    public String unprioritizedItems {get; set;}
    public Boolean isUniversal {get; set;}


    public CustomBacklogModel(Custom_Backlog__c cbklg){
        this.name = cbklg.Name;
        this.isUniversal = cbklg.Universal__c;
        this.customBacklogId = this.isUniversal ? BacklogManagementHomeController.MASTER_BACKLOG_IDENTIFIER : cbklg.Id;
        Integer intUnprioritizedItems = 0;
        for (Backlog__c bItem: cbklg.Backlog_Items__r) {
            if (bItem.Custom_Priority__c == null){
                intUnprioritizedItems += 1;
            }
        }
        if (!this.isUniversal) {
            this.totalItems = getCountAsString(cbklg.Backlog_Items__r.size());
            this.unprioritizedItems = getCountAsString(intUnprioritizedItems);
        }
    }

    public Static String getCountAsString(Integer itemCount) {
        return itemCount > 999? '999+': String.valueOf(itemCount);
    }

}