mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Current_Sprint__c.field-meta.xml
<CustomField>
    <fullName>Current_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/Sprint_Item__c.object-meta.xml
<CustomObject>
    <label>Sprint Item</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Sprint Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Sprint Items</relationshipLabel>
    <relationshipName>Sprint_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Sprint Items</relationshipLabel>
    <relationshipName>Sprint_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/TestSprintItemTrigger.cls
@isTest
private class TestSprintItemTrigger {
    
    static void setupTestSprintItemData(Boolean doInsert){
        UnitTest.addData(TestingUtils.buildSprints('test_sprint', 2)).tag('Sprints');
        if (doInsert){
            UnitTest.get('Sprints').insertAll();
        }
        else {
            UnitTest.get('Sprints').dummyInsert();
        }
        UnitTest.get('Sprints')
            .divide(2)
            .part('Sprint 1')
            .part('Sprint 2');
        UnitTest.addData(TestingUtils.buildBacklogItems(2)).tag('Backlogs');
        if (doInsert){
            UnitTest.get('Backlogs').insertAll();
        }
        else {
            UnitTest.get('Backlogs').dummyInsert();
        }
        
        UnitTest.addData(TestingUtils.buildSprintItems(null, (List<Backlog__c>) UnitTest.get('Backlogs').getList() )).tag('Sprint Items');
        UnitTest.get('Sprint Items')
            .divide(2)
            .part('Sprint Items in Sprint 1')
            .part('Sprint Items in Sprint 2');
        UnitTest.get('Sprint Items in Sprint 1').property(SObjectServices.getFullyQualifiedName('Sprint__c')).assign(UnitTest.get('Sprint 1').getList()[0].Id);
        UnitTest.get('Sprint Items in Sprint 2').property(SObjectServices.getFullyQualifiedName('Sprint__c')).assign(UnitTest.get('Sprint 2').getList()[0].Id);
        
    }

    static testMethod void testSprintItemInsert_UpdateCurrentSprintOnBacklog() {
        
        setupTestSprintItemData(true);
        
        Test.startTest();
            UnitTest.get('Sprint Items').insertAll();
        Test.stopTest();
        
        Map<Id, Backlog__c> bklgMap = new Map<Id, Backlog__c>([Select Current_Sprint__c, Status__c from Backlog__c Where Id in :UnitTest.getIds('Backlogs')]);
        
        System.assertEquals(UnitTest.getIds('Backlogs'), bklgMap.keySet(), 'We expect to get back the correct backlogs.');
        for (Sprint_Item__c sItem : (List<Sprint_Item__c>)UnitTest.get('Sprint Items').getList()){
            System.assertEquals(sItem.Sprint__c, bklgMap.get(sItem.Backlog__c).Current_Sprint__c, 'We expect the Backlog to be updated with the current sprint.');
        }
        
    }
    
    static testMethod void testSprintItemNonSprintUpdate_MaintainCurrentSprintOnBacklog() {
        
        setupTestSprintItemData(true);

        UnitTest.get('Sprint Items').insertAll();
        
        UnitTest.get('Sprint Items').property(SObjectServices.getFullyQualifiedName('Status__c')).assign(SprintModel.COMPLETED_STATUS);
        
        Test.startTest();
            UnitTest.get('Sprint Items').updateAll();
        Test.stopTest();
        
        Map<Id, Backlog__c> bklgMap = new Map<Id, Backlog__c>([Select Current_Sprint__c, Status__c from Backlog__c Where Id in :UnitTest.getIds('Backlogs')]);
        
        System.assertEquals(UnitTest.getIds('Backlogs'), bklgMap.keySet(), 'We expect to get back the correct backlogs.');
        for (Sprint_Item__c sItem : (List<Sprint_Item__c>)UnitTest.get('Sprint Items').getList()){
            System.assertEquals(sItem.Sprint__c, bklgMap.get(sItem.Backlog__c).Current_Sprint__c, 'We expect the Backlog to be the same current sprint.');
        }
        
    }
    
    static testMethod void testSprintItemDelete_ClearCurrentSprintOnBacklog() {
        
        setupTestSprintItemData(true);
        UnitTest.get('Sprint Items').insertAll();
        
        Test.startTest();
            UnitTest.get('Sprint Items').deleteAll();
        Test.stopTest();
        
        Map<Id, Backlog__c> bklgMap = new Map<Id, Backlog__c>([Select Current_Sprint__c, Status__c from Backlog__c Where Id in :UnitTest.getIds('Backlogs')]);
        
        System.assertEquals(UnitTest.getIds('Backlogs'), bklgMap.keySet(), 'We expect to get back the correct backlogs.');
        for (Id bklgId : bklgMap.keySet()){
            System.assertEquals(null, bklgMap.get(bklgId).Current_Sprint__c, 'We expect the Backlog to be updated with NO current sprint.');
        }
        
    }
    static testMethod void testSprintItemUndelete_UpdateCurrentSprintOnBacklog() {
        
        setupTestSprintItemData(true);
        UnitTest.get('Sprint Items').insertAll();
        UnitTest.get('Sprint Items').deleteAll();
        
        Test.startTest();
            undelete UnitTest.get('Sprint Items').getList();
        Test.stopTest();
        
        Map<Id, Backlog__c> bklgMap = new Map<Id, Backlog__c>([Select Current_Sprint__c, Status__c from Backlog__c Where Id in :UnitTest.getIds('Backlogs')]);
        
        System.assertEquals(UnitTest.getIds('Backlogs'), bklgMap.keySet(), 'We expect to get back the correct backlogs.');
        for (Sprint_Item__c sItem : (List<Sprint_Item__c>)UnitTest.get('Sprint Items').getList()){
            System.assertEquals(sItem.Sprint__c, bklgMap.get(sItem.Backlog__c).Current_Sprint__c, 'We expect the Backlog to be updated with the current sprint.');
        }
        
    }
}