mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The status should indicate the stage in the life of a backlog item from inception to completion.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Needs Requirements</fullName>
            </value>
            <value>
                <fullName>Needs Solution</fullName>
            </value>
            <value>
                <fullName>Dev Ready</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Dev Complete</fullName>
            </value>
            <value>
                <fullName>Build Ready</fullName>
            </value>
            <value>
                <fullName>QA Ready</fullName>
            </value>
            <value>
                <fullName>QA Accepted</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defect Resolution</fullName>
            </value>
            <value>
                <fullName>UAT Accepted</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user story that the defect is associated to.</inlineHelpText>
    <label>User Story</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Defects</relationshipLabel>
    <relationshipName>Backlog</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/Backlog_Component__c.object-meta.xml
<CustomObject>
    <description>Links component records to backlog items like stories and defects.</description>
    <label>Backlog Component</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Backlog Component</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>User Stories and Defects</relationshipLabel>
    <relationshipName>SCBridge</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Include_Entire_Profile__c.field-meta.xml
<CustomField>
    <fullName>Include_Entire_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the entire profile should be deployed</description>
    <inlineHelpText>Indicates that the entire profile should be deployed</inlineHelpText>
    <label>Include Entire Profile</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Backlog Components (Profile)</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_1__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_1__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Data_2__c.field-meta.xml
<CustomField>
    <fullName>Profile_Data_2__c</fullName>
    <description>Stores the profile selection data</description>
    <label>Profile Data 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Profile_Permission__c.field-meta.xml
<CustomField>
    <fullName>Profile_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Profile Permission</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Instance__c.field-meta.xml
<CustomField>
    <fullName>Source_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>Backlog Components</relationshipLabel>
    <relationshipName>Backlog_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_Component__c/fields/Source_Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Source_Sandbox__c</fullName>
    <inlineHelpText>The name of the sandbox where this component was developed.</inlineHelpText>
    <label>Source Sandbox</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Component__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Component Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Parent_Component__c.field-meta.xml
<CustomField>
    <fullName>Parent_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Child Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Component__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Assignment Rule</fullName>
            </value>
            <value>
                <fullName>Business Rule</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Custom Button or Link</fullName>
            </value>
            <value>
                <fullName>Custom Object Tab</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Dashboard</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Field Set</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home Page Component</fullName>
            </value>
            <value>
                <fullName>Home Page Layout</fullName>
            </value>
            <value>
                <fullName>Label</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>List View</fullName>
            </value>
            <value>
                <fullName>Lookup Filter</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Object Translation</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Password Policy</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Instances__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Production / Developer</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/classes/BacklogComponentServices.cls
public with sharing class BacklogComponentServices {
    /**
    * Updates profile permission data on a set of backlog components related to a given set of other backlog
    * components to be deleted. Profile backlog components are updated at this time.
    * @param deletedBacklogComponents - A set of backlog components that have been deleted.
    * @return Database.SaveResult - The results of updating profile backlog components.
    */
    public static Map<Id, Backlog_Component__c> removeDeletedBacklogComponentsFromProfileData(Set<Backlog_Component__c> deletedBacklogComponents) {
        return removeDeletedBacklogComponentsFromProfileData(deletedBacklogComponents, true);
    }

    /**
    * Updates profile permission data on a set of backlog components related to a given set of other backlog
    * components to be deleted. Profile backlog components are not updated at this time, by default.
    * @param deletedBacklogComponents - A set of backlog components that have been deleted.
    * @param updateProfiles - A flag that determines whether or not profile backlog components are updated
    * or simply returned.
    * @return Database.SaveResult - The results of updating profile backlog components.
    */
    public static Map<Id, Backlog_Component__c> removeDeletedBacklogComponentsFromProfileData(Set<Backlog_Component__c> deletedBacklogComponents, Boolean updateProfiles) {
        // Grab all backlog components related to profiles.
        Set<Backlog_Component__c> profileBacklogComponents = filterProfileBacklogComponents(deletedBacklogComponents);

        // If there are no profile-related backlog components, return.
        if (profileBacklogComponents.isEmpty()) {
            return null;
        }

        // Map backlog IDs to their associated manifest records.
        Map<Id, List<AssemblerManifestRecord>> backlogIdsToManifestRecords = 
            mapBacklogIdsToManifestRecords(profileBacklogComponents);

        // Map backlog IDs to their associated permissions maps.
        Map<Id, Map<String, Set<String>>> backlogIdToPermissionsMap = new Map<Id, Map<String, Set<String>>>();
        for (Id backlogId : backlogIdsToManifestRecords.keySet()) {
            backlogIdToPermissionsMap.put(
                backlogId, 
                ProfileServices.filterComponents(backlogIdsToManifestRecords.get(backlogId))
            );
        }

        // Grab all profile backlog components affected by the deletion, sorted by backlog item.
        List<Backlog__c> relevantBacklogItems = [
            SELECT Id, (
                SELECT Id, Source_Sandbox__c, Source_Instance__r.Name, Backlog__r.Name, Backlog__r.Status__c, 
                       Component__r.Name, Component__r.Full_Name__c, Component__r.Type__c, Component__r.Parent_Component__r.Name, Notes__c, 
                       Profile_Permission__c, Profile_Data_1__c, Profile_Data_2__c, Include_Entire_Profile__c, Profile__c, Profile__r.Name, Profile__r.Full_Name__c
                FROM SCBridge__r
                WHERE (Profile_Permission__c = true OR Component__r.Type__c = 'Profile')) 
            FROM Backlog__c 
            WHERE Id IN :backlogIdsToManifestRecords.keySet()
        ];

        // Remove permissions from each backlog component, on each backlog item.
        List<Backlog_Component__c> updatedProfileComponents = new List<Backlog_Component__c>();
        for (Backlog__c backlogItem : relevantBacklogItems) {
            for (Backlog_Component__c backlogComponent : backlogItem.SCBridge__r) {
                // Remove the permissions.
                ProfilePermissions profilePermissionsData = ProfilePermissions.valueOf(backlogComponent);
                profilePermissionsData.removePermissions(backlogIdToPermissionsMap.get(backlogItem.Id));
                ProfilePermissions.setProfilePermissionsData(backlogComponent, JSON.serialize(profilePermissionsData));

                // Add the profile backlog component to the list to be updated.
                updatedProfileComponents.add(backlogComponent);
            }
        }

        // Update the altered permissions on the profile backlog components.
        if (updateProfiles) {
            try {
                update updatedProfileComponents;
            } catch (DMLException de) {
                for (Integer i = 0; i < de.getNumDml(); ++i) {
                    updatedProfileComponents[de.getDmlIndex(i)].addError(de.getDmlMessage(i));
                }
                ALMLogServices.error(de, ALMLogServices.Application.COMPONENT_DOCUMENTATION);
            }
        }

        // Map final updated profile backlog component IDs to their associated records.
        Map<Id, Backlog_Component__c> updatedProfileComponentIdToRecord = new Map<Id, Backlog_Component__c>(updatedProfileComponents);

        return updatedProfileComponentIdToRecord;
    }

    /**
    * Filters a given set of backlog components by relevance to profiles.
    * @param backlogComponentsToFilter - A set of backlog components to filter for relevance to profiles.
    * @return - A set of backlog components relevant to profiles.
    */
    private static Set<Backlog_Component__c> filterProfileBacklogComponents(Set<Backlog_Component__c> backlogComponentsToFilter) {
        // Collect all related component IDs.
        Set<Id> componentIds = new Set<Id>();
        for (Backlog_Component__c backlogComponent : backlogComponentsToFilter) {
            componentIds.add(backlogComponent.Component__c);
        }

        // Map IDs of components of types relevant to profiles to their component records.
        Map<Id, Component__c> profileComponentIdsToComponents = new Map<Id, Component__c>();
        for (Component__c component : [SELECT Name, Full_Name__c, Type__c, Parent_Component__r.Name, Parent_Component__r.Full_Name__c FROM Component__c WHERE Id IN :componentIds]) {
            if (ProfileServices.COMPONENT_TYPE_TO_CATEGORY.containsKey(component.Type__c)) {
                profileComponentIdsToComponents.put(component.Id, component);
            }
        }

        // Collect all of the backlog components that are relevant to profiles.
        Set<Backlog_Component__c> profileBacklogComponents = new Set<Backlog_Component__c>();
        for (Backlog_Component__c backlogComponent : backlogComponentsToFilter) {
            if (profileComponentIdsToComponents.containsKey(backlogComponent.Component__c)) {
                backlogComponent.Component__r = profileComponentIdsToComponents.get(backlogComponent.Component__c);
                profileBacklogComponents.add(backlogComponent);
            }
        }

        return profileBacklogComponents;
    }

    /**
    * Maps backlog item IDs to lists of relevant manifest records.
    * @param - profileBacklogComponents - A set of backlog components to create "backlog ID => list of manifest records" associations from.
    * @return - A map associating backlog IDs with lists of manifest records.
    */
    private static Map<Id, List<AssemblerManifestRecord>> mapBacklogIdsToManifestRecords(Set<Backlog_Component__c> profileBacklogComponents) {
        Map<Id, List<AssemblerManifestRecord>> backlogIdsToManifestRecords = new Map<Id, List<AssemblerManifestRecord>>();
        for (Backlog_Component__c backlogComponent : profileBacklogComponents) {
            if (backlogIdsToManifestRecords.get(backlogComponent.Backlog__c) == null) {
                backlogIdsToManifestRecords.put(backlogComponent.Backlog__c, new List<AssemblerManifestRecord>());
            }
            backlogIdsToManifestRecords.get(backlogComponent.Backlog__c).add(new AssemblerManifestRecord(backlogComponent));
        }

        return backlogIdsToManifestRecords;
    }
}