mywork/force-app/main/default/objects/Jenkins_Config__c/Jenkins_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Represents a configuration for a Jenkins CI build server.</description>
    <label>Jenkins Config</label>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Represents a Jenkins CI build server endpoint.</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/User_API_Token__c.field-meta.xml
<CustomField>
    <fullName>User_API_Token__c</fullName>
    <description>Represents a Jenkins CI user API token.</description>
    <label>User API Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Config__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <description>Represents a Jenkins CI user ID.</description>
    <label>User ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/JenkinsStartJobRequest.cls
public with sharing class JenkinsStartJobRequest extends BaseRequest {

	public String buildPackageUrl;
	public String jenkinsBuildName;
	public String jenkinsEndpoint;
	public String jenkinsUserApiToken;
	public String jenkinsUserId;
	public String jenkinsJobTokenParam;

	public JenkinsStartJobRequest(String jenkinsBuildName, String jenkinsJobTokenParam, String jenkinsPath,
	                              String buildPackageUrl) {
		super();

		Jenkins_Config__c jenkinsConfig = Jenkins_Config__c.getInstance();
		if (jenkinsConfig == null || String.isBlank(jenkinsConfig.Endpoint__c)) {
			throw new ALMException(JenkinsServices.CONFIG_ERROR);
		}

		this.jenkinsBuildName = jenkinsBuildName;
		this.buildPackageUrl = buildPackageUrl;
		this.jenkinsEndpoint = jenkinsConfig.Endpoint__c + jenkinsPath;
		this.jenkinsUserApiToken = jenkinsConfig.User_API_Token__c;
		this.jenkinsUserId = jenkinsConfig.User_ID__c;
		this.jenkinsJobTokenParam = jenkinsJobTokenParam;
	}
}