mywork/force-app/main/default/objects/Build_Rule__c/Build_Rule__c.object-meta.xml
<CustomObject>
    <description>Defines criteria that need to be met in order for a build to be started</description>
    <label>Build Rule</label>
    <nameField>
        <displayFormat>BR - {000}</displayFormat>
        <label>Build Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build_Rule__c/fields/Boolean_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Boolean_Criteria__c</fullName>
    <inlineHelpText>Semi-colon delimited list of field api names that need to evaluate to true</inlineHelpText>
    <label>Boolean Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/CI_Instance__c/CI_Instance__c.object-meta.xml
<CustomObject>
    <label>CI Instance</label>
    <nameField>
        <label>CI Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CI Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/Jenkins_Job__c.object-meta.xml
<CustomObject>
    <description>Represents a job on a Jenkins CI build server.</description>
    <label>Jenkins Job</label>
    <nameField>
        <label>Jenkins Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jenkins Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Build_Rule__c.field-meta.xml
<CustomField>
    <fullName>Build_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build Rule</label>
    <referenceTo>Build_Rule__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/CI_Instance__c.field-meta.xml
<CustomField>
    <fullName>CI_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The target instance for this Job</inlineHelpText>
    <label>CI Instance</label>
    <referenceTo>CI_Instance__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Dependent_Jenkins_Job__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Jenkins_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A job dependent on this job.</description>
    <label>Dependent Jenkins Job</label>
    <referenceTo>Jenkins_Job__c</referenceTo>
    <relationshipLabel>Dependent Jenkins Jobs</relationshipLabel>
    <relationshipName>Dependent_Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Last_Build_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Build_Status__c</fullName>
    <label>Last Build Status</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Trigger_Job_Automatically__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Job_Automatically__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger_Job_Automatically__c checkbox to be checked if the jenkins jobs should start automatically start the jenkins job.</description>
    <label>Trigger Job Automatically</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/classes/JenkinsJobHandler.cls
public with sharing class JenkinsJobHandler{
    
    public static final String JENKINS_JOB_DEFAULT_STATUS = 'Pending';
    public static final String JENKINS_JOB_SUCCESS_STATUS = 'Success';   
    
    /**
    * Check any dependent jenkins jobs which can be triggered automatically and then start jobs
    *  @param  jenkinsJobs Should be trigger.new
    */    
     public static void executeDependentJenkinsJob(List<Jenkins_Job__c> jenkinsJobs){
        Set<Id> depJobIds = new Set<Id>();
        List<Jenkins_Job__c> depJobs = new List<Jenkins_job__c>();
        for (Jenkins_Job__c jJob: jenkinsJobs) {
               Jenkins_Job__c oldJob = (Jenkins_Job__c) Trigger.oldMap.get(jJob.ID);
               if(JENKINS_JOB_DEFAULT_STATUS.equalsIgnorecase(oldJob.Last_Build_Status__c)
                       && JENKINS_JOB_SUCCESS_STATUS.equalsIgnorecase(jJob.Last_Build_Status__c)) {
                       if(jJob.Dependent_Jenkins_Job__c != null){
                           depJobIds.add(jJob.Dependent_Jenkins_Job__c);
                       }                      
                }
               
        }
        if(!depJobIds.isEmpty()){
            depJobs = [SELECT Build_Rule__r.Boolean_Criteria__c , Build_Rule__c, CI_Instance__c FROM Jenkins_Job__c WHERE Id IN : depJobIds AND Trigger_Job_Automatically__c = true]; 
            for(Jenkins_Job__c depJenkinsJob : depJobs ){
                if(depJenkinsJob  != null){
                    CIInstanceservices.executeValidJob((Jenkins_Job__c)depJenkinsJob);
                }
            }
        }        
       
    } 
    
 
}