mywork/force-app/main/default/objects/Build_Rule__c/Build_Rule__c.object-meta.xml
<CustomObject>
    <description>Defines criteria that need to be met in order for a build to be started</description>
    <label>Build Rule</label>
    <nameField>
        <displayFormat>BR - {000}</displayFormat>
        <label>Build Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Build_Rule__c/fields/Boolean_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Boolean_Criteria__c</fullName>
    <inlineHelpText>Semi-colon delimited list of field api names that need to evaluate to true</inlineHelpText>
    <label>Boolean Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/CI_Instance__c/CI_Instance__c.object-meta.xml
<CustomObject>
    <label>CI Instance</label>
    <nameField>
        <label>CI Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CI Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/CI_Instance__c/fields/Pre_Steps_Completed__c.field-meta.xml
<CustomField>
    <fullName>Pre_Steps_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if pre deployment steps have been executed for this Instance</inlineHelpText>
    <label>Pre-Steps Completed</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/CI_Instance__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>CI Instances</relationshipLabel>
    <relationshipName>CI_Instances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/CI_Instance__c/fields/Target_Instance__c.field-meta.xml
<CustomField>
    <fullName>Target_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Target Instance</label>
    <referenceTo>Instances__c</referenceTo>
    <relationshipLabel>CI Instances</relationshipLabel>
    <relationshipName>CI_Instances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Instances__c/Instances__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Build__c/Jenkins_Build__c.object-meta.xml
<CustomObject>
    <label>Jenkins Build</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jenkins Build Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jenkins Builds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/CI_Instance__c.field-meta.xml
<CustomField>
    <fullName>CI_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CI Instance</label>
    <referenceTo>CI_Instance__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Build__c/fields/Jenkins_Job__c.field-meta.xml
<CustomField>
    <fullName>Jenkins_Job__c</fullName>
    <label>Jenkins Job</label>
    <referenceTo>Jenkins_Job__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/Jenkins_Job__c.object-meta.xml
<CustomObject>
    <description>Represents a job on a Jenkins CI build server.</description>
    <label>Jenkins Job</label>
    <nameField>
        <label>Jenkins Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jenkins Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Build_Rule__c.field-meta.xml
<CustomField>
    <fullName>Build_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Build Rule</label>
    <referenceTo>Build_Rule__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/CI_Instance__c.field-meta.xml
<CustomField>
    <fullName>CI_Instance__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The target instance for this Job</inlineHelpText>
    <label>CI Instance</label>
    <referenceTo>CI_Instance__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Is_Validation__c.field-meta.xml
<CustomField>
    <fullName>Is_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if this job is performing a validation. When unchecked it indicates this is for a deployment</inlineHelpText>
    <label>Is Validation?</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Represents a relative URL path to a job on a Jenkins CI build server.</description>
    <label>Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents a Sightline release.</description>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Jenkins Jobs</relationshipLabel>
    <relationshipName>Jenkins_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Source_Repository__c.field-meta.xml
<CustomField>
    <fullName>Source_Repository__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Repository</label>
    <referenceTo>VC_Repository__c</referenceTo>
    <relationshipLabel>Jenkins Builds</relationshipLabel>
    <relationshipName>Jenkins_Builds2</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Source_Repository_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Repository_Location__c</fullName>
    <label>Source Repository Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Represents an authentication token for a job on a Jenkins CI build server.</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Jenkins_Job__c/fields/Trigger_Job_Automatically__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Job_Automatically__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger_Job_Automatically__c checkbox to be checked if the jenkins jobs should start automatically start the jenkins job.</description>
    <label>Trigger Job Automatically</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Release__c/recordTypes/Build.recordType-meta.xml
<RecordType>
    <fullName>Build</fullName>
    <active>true</active>
    <label>Build</label>
</RecordType>

mywork/force-app/main/default/objects/Release__c/recordTypes/Release.recordType-meta.xml
<RecordType>
    <fullName>Release</fullName>
    <active>true</active>
    <label>Release</label>
</RecordType>

mywork/force-app/main/default/objects/VC_Repository__c/VC_Repository__c.object-meta.xml
<CustomObject>
    <label>VC Repository</label>
    <nameField>
        <label>VC Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VC Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/VC_Repository__c/fields/Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Repository_URL__c</fullName>
    <description>The SSH URL of the version control system repository.</description>
    <inlineHelpText>The SSH URL of the version control system repository. This URL may explicitly specify the "ssh://" protocol or, as in the case of some VC services (e.g. GitHub), the URL may have its own unique syntax.</inlineHelpText>
    <label>Repository URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/classes/TestCIInstanceTrigger.cls
@isTest
private class TestCIInstanceTrigger {

	private static final String TEST_JOB_PATH = 'test/job/path';
    private static final String TEST_JOB_TOKEN = 'test_job_token';
    
    static testMethod void testAutoStartValidJobs() {
    	Release__c release = new Release__c(Name='Test release');
        insert release;      
        
        Test.setMock(HttpCalloutMock.class, new MockJenkinsAPI(TEST_JOB_PATH, TEST_JOB_TOKEN));
        
        Instances__c Instances = TestingUtils.createInstance('TestTarget');
        CI_Instance__c ciInstance = new CI_Instance__c(Name ='Test Dev',Target_Instance__c = Instances.id, Release__c = release.id);
        insert ciInstance;
        
        Build_Rule__c bRule = new Build_Rule__c(Boolean_Criteria__c='Pre_Steps_Completed__c');
        insert bRule;

        VC_Repository__c vcRepo = new VC_Repository__c(Repository_URL__c = 'some-repo-URL' );
        insert vcRepo;
        
        Jenkins_Job__c jJob = new Jenkins_Job__c (
            Name='TestJob',
            path__c='job/JenkinsTestJob',
            Token__c='f7b94543c70b741nwwjw36498476ea66fdaab',
            CI_Instance__c=ciInstance.id,
            Release__c=release.id,
            Is_Validation__c=true,
            Build_Rule__c=bRule.Id,
            Trigger_Job_Automatically__c = true,
            Source_Repository_Location__c = 'some-branch-name',
             Source_Repository__c = vcRepo.Id
        );
        insert jJob;
                      
        Test.startTest();

            ciInstance.Pre_Steps_Completed__c = true;

            update ciInstance;
        
        Test.stopTest();  
        List<Jenkins_Build__c> builds = [SELECT Id from Jenkins_Build__c WHERE Jenkins_Job__c = : jJob.Id];
        System.assertEquals(builds.size(),1, 'Some Issue in creation of Jenkins Build object as part of start job automatically');
     
    }

}