mywork/force-app/main/default/objects/ALMSettings__c/ALMSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ALM Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/ALMSettings__c/fields/Enable_Custom_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Custom_Backlogs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls accessibility to custom backlogs</description>
    <label>Enable Custom Backlogs</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Backlog__c.field-meta.xml
<CustomField>
    <fullName>Custom_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Backlog</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a different backlog, all items are already assigned to the main backlog</errorMessage>
        <filterItems>
            <field>Custom_Backlog__c.Universal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Custom_Backlog__c</referenceTo>
    <relationshipLabel>Backlog Items</relationshipLabel>
    <relationshipName>Backlog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Custom_Backlog__c/Custom_Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/CustomBacklogPermissions.cls
public with sharing class CustomBacklogPermissions implements ApplicationPermissions {
    public static final Map<String, Schema.DescribeSObjectResult> OBJECTS_TO_DESCRIBE = new Map<String, Schema.DescribeSObjectResult> {
        SObjectServices.getFullyQualifiedName('Custom_Backlog__c') => Custom_Backlog__c.sObjectType.getDescribe(),
        SObjectServices.getFullyQualifiedName('Backlog__c') => Backlog__c.sObjectType.getDescribe()
    };


    public PermissionServices.PermissionLevel hasPermission() {
        PermissionServices.PermissionLevel permissionsLevel = PermissionServices.PermissionLevel.NONE;

        if (hasObjectPermissions() && hasRecordTypePermissions() && hasFLSPermissions() && accessCustomBacklogs) {
            permissionsLevel = PermissionServices.PermissionLevel.FULL;
        } else if (hasObjectReadPermissions() && hasRecordTypePermissions() && hasFLSPermissions() && accessCustomBacklogs) {
            permissionsLevel = PermissionServices.PermissionLevel.READ_ONLY;
        }

        return permissionsLevel;
    }

    public Boolean hasFLSPermissions() {
        return true;
    }

    public Boolean hasObjectPermissions(){
        return PermissionServices.hasObjectFullPermissions(OBJECTS_TO_DESCRIBE);
    }

    public Boolean hasObjectReadPermissions(){
        return PermissionServices.hasObjectReadPermissions(OBJECTS_TO_DESCRIBE);
    }

    public Boolean hasRecordTypePermissions(){
        return true;
    }

    private Boolean accessCustomBacklogs {
        get {
            return ALMSettings__c.getInstance().Enable_Custom_Backlogs__c;
        }
        private set;
    }
}