mywork/force-app/main/default/objects/ALMSettings__c/ALMSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ALM Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/ALMSettings__c/fields/Enable_Custom_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Custom_Backlogs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls accessibility to custom backlogs</description>
    <label>Enable Custom Backlogs</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/classes/PopulateALMSettings.cls
public with sharing class PopulateALMSettings {
    public static void populateCustomSettingEnableMultipleBacklogs() {
        String errorString;
        ALMSettings__c existingSetting = ALMSettings__c.getOrgDefaults();
        if(!existingSetting.Enable_Custom_Backlogs__c) {
            existingSetting.Enable_Custom_Backlogs__c = true;
            try {
                upsert existingSetting;
            } catch (DMLException dex) {
                errorString = dex.getMessage();
            }

            if (String.isNotBlank(errorString)) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String[] mailTo = new String[] {'productdev@bluewolfgroup.com'};
                mail.setToAddresses(mailTo);
                mail.setSubject('Errors occurred during the universal backlog creation post install process');
                mail.setPlainTextBody(errorString);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            }
        }
    }
}