mywork/force-app/main/default/objects/ALMSettings__c/ALMSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ALM Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/ALMSettings__c/fields/Last_Log_Export_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Log_Export_Time__c</fullName>
    <description>Stores the last time that any error logs were exported</description>
    <label>Last Log Export Time</label>
    <type>DateTime</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/Logged_Exception__c.object-meta.xml
<CustomObject>
    <label>Logged Exception</label>
    <nameField>
        <displayFormat>Ex{0000}</displayFormat>
        <label>Logged Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logged Exeptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The application that the exception occurred in</description>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Console</fullName>
            </value>
            <value>
                <fullName>Backlog Management</fullName>
            </value>
            <value>
                <fullName>Component Documentation</fullName>
            </value>
            <value>
                <fullName>Sprint</fullName>
            </value>
            <value>
                <fullName>Slingshot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Class_Id__c.field-meta.xml
<CustomField>
    <fullName>Class_Id__c</fullName>
    <label>Class Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Class_Link__c.field-meta.xml
<CustomField>
    <fullName>Class_Link__c</fullName>
    <formula>HYPERLINK('/' +  Class_Id__c , 'View Class', '_BLANK')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Class Link</label>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Exception_Description__c.field-meta.xml
<CustomField>
    <fullName>Exception_Description__c</fullName>
    <description>Includes Stack Trace, DML operation info, etc</description>
    <label>Exception Description</label>
    <length>16384</length>
    <type>LongTextArea</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Notified__c.field-meta.xml
<CustomField>
    <fullName>Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notified</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the type of Exception that has been logged. These values are drawn from the Exception type list that can be found in Salesforce's Apex documentation.</description>
    <label>Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

mywork/force-app/main/default/objects/Logged_Exception__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logged_Exeptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/classes/ALMLogServices.cls
public with sharing class ALMLogServices {

    public enum Application {
        ADMIN_CONSOLE,
        BACKLOG_MANAGEMENT,
        COMPONENT_DOCUMENTATION,
        LOGGER,
        OAUTH,
        PM_POST_INSTALL_SCRIPT,
        SPRINT,
        SCAN,
        SLINGSHOT,
        AUTOMATED_TESTING,
        JENKINS,
        VC,
        APPLICATION_RESULT_CLEANER,
        DX_SCRATCH
    }

    public enum LogLevel {
        ERROR,
        WARNING
    }

    @future(callout=true)
    public static void export() {
        List<Logged_Exception__c> logsToExport = getLogsToExport();

        if (logsToExport.isEmpty()) {
            return;
        }

        //due to the 256k message limit size in SQS, lets only include 15 messages for any request
        final Integer MAX_LOGS_TO_PROCESS = 15;
        Datetime lastExportTime;

        String logEndpoint = ALMRestServices.WEB_SERVICE_URL + '/alm-log';
        for (List<Logged_Exception__c> exceptions : SObjectServices.chunkLists(logsToExport, MAX_LOGS_TO_PROCESS)) {
            LogCreateRequest request = new LogCreateRequest(exceptions);
            try {
                ALMRestServices.makePostRequest(logEndpoint, JSON.serialize(request));
                lastExportTime = exceptions[exceptions.size() - 1].CreatedDate;
            } catch (ALMException ae) {
                error(ae, Application.LOGGER);
                updateLastSyncTime(lastExportTime);
                //can not make additional callouts if logging error
                return;
            }
        }

        updateLastSyncTime(lastExportTime);
    }

    public static void error(Exception ex, Application app) {
        log(ex, app, LogLevel.ERROR);
    }

    public static void warn(Exception ex, Application app) {
        log(ex, app, LogLevel.WARNING);
    }

    private static void log(Exception ex, Application app, LogLevel logLevel) {
        ExLog.log(ex, app, logLevel);
        ALMLogExportScheduler.ensureScheduleExists();
    }

    public static void errorAsync(Exception ex, Application app) {
        logAsync(ex, app, LogLevel.ERROR);
    }

    public static void warnAsync(Exception ex, Application app) {
        logAsync(ex, app, LogLevel.WARNING);
    }

    private static void logAsync(Exception ex, Application app, LogLevel logLevel) {
        System.enqueueJob(new AsyncExLog(ex, app, logLevel));
        ALMLogExportScheduler.ensureScheduleExists();
    }

    private static void updateLastSyncTime(Datetime lastExportTime) {
        if (lastExportTime == null) {
            return;
        }

        ALMSettings__c settings = ALMSettings__c.getOrgDefaults();
        settings.Last_Log_Export_Time__c = lastExportTime;
        try {
            upsert settings;
        } catch(DmlException de) {
            error(de, Application.LOGGER);
        }
    }

    public static List<Logged_Exception__c> getLogsToExport() {
        return [
            SELECT Who__c, Type__c,  Organization_Name__c, Organization_Id__c, Notified__c, Log_Level__c,
             Line_Number__c,  Exception_Description__c, CreatedDate, CreatedById, Class_Name__c,
             Class_Link__c, Class_Id__c, Application__c
            FROM Logged_Exception__c
            WHERE CreatedDate > :ALMSettings__c.getOrgDefaults().Last_Log_Export_Time__c
            ORDER BY CreatedDate ASC
            LIMIT 500
        ];
    }

    public class LogCreateRequest {
        public List<Log> logs;
        public String orgId;

        public LogCreateRequest(List<Logged_Exception__c> exceptions) {
            this.logs = new List<Log>();
            this.orgId = UserInfo.getOrganizationId();
            for(Logged_Exception__c le : exceptions) {
                logs.add( new Log(le) );
            }
        }
    }

    public class Log {
        public String application;
        public String appVersion;
        public String className;
        public String lineNumber;
        public String logLevel;
        public String message;
        public String orgName;
        public String type;
        public String who;

        public Log(Logged_Exception__c le) {
            this.application  = le.Application__c;

            if (SObjectServices.CURRENT_NAMESPACE != '') {
                this.appVersion = System.requestVersion().major() +'.' + System.requestVersion().minor();
            }

            this.className = le.Class_Name__c;
            this.lineNumber = le.Line_Number__c == null ? null : String.valueOf(le.Line_Number__c);
            this.logLevel = le.Log_Level__c;
            this.message = le.Exception_Description__c;
            this.orgName = le.Organization_Name__c;
            this.type = le.Type__c;
            this.who = le.Who__c;
        }
    }
}