mywork/force-app/main/default/objects/ALMSettings__c/ALMSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ALM Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/ALMSettings__c/fields/Enable_Custom_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Custom_Backlogs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls accessibility to custom backlogs</description>
    <label>Enable Custom Backlogs</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/fields/Custom_Priority__c.field-meta.xml
<CustomField>
    <fullName>Custom_Priority__c</fullName>
    <label>Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Main Backlog Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mywork/force-app/main/default/classes/BacklogPrioritizationColumnConfig.cls
public with sharing class BacklogPrioritizationColumnConfig extends ColumnConfig {
    
    @TestVisible
    private static Set<String> columnsToExclude = new Set<String>{
    
    };
    public Boolean isCustomBacklogEnabled {
        get {
            return ALMSettings__c.getInstance().Enable_Custom_Backlogs__c;
        }
        private set;
    }
    
    public BacklogPrioritizationColumnConfig() {
        super();
        if (!isCustomBacklogEnabled){
            columnsToExclude.add(SObjectServices.getFullyQualifiedName('Custom_Priority__c'));
        }
        loadColumns();
    }
    
    private void loadColumns() {
        Map<String, Column> allColumns = new Map<String, Column>();
        for (Column field : BacklogItemServices.getFields()) {
            if (!columnsToExclude.contains(field.apiName)){
                allColumns.put( field.apiName, field);
            }
        }
        
        activeColumns = new List<Column>();
        for (Column activeColumn : BacklogItemServices.getPrioritizationFields()){ 
            if (isCustomBacklogEnabled || activeColumn.apiName != SObjectServices.getFullyQualifiedName('Custom_Priority__c')){ 
                activeColumns.add(activeColumn); 
            }
        } 
        
        addStaticColumns(activeColumns,
            new List<Column>{ new Column(Schema.sObjectType.Backlog__c.fields.Priority__c) });

        for (Column field : activeColumns) {
            allColumns.remove( field.apiName);
            if (BacklogItemServices.DEFAULT_COLUMNS.contains(field.apiName)) {
                field.isDefault = true;
            }
        }

        for (String defaultColumnName : BacklogItemServices.DEFAULT_COLUMNS) {
            if (allColumns.containsKey( defaultColumnName )) {
                Column defaultColumn = allColumns.remove( defaultColumnName );
                defaultColumn.isDefault = true;
                activeColumns.add(defaultColumn);
            }
        }

        unusedColumns = allColumns.values();
        unusedColumns.sort();
    }
}