mywork/force-app/main/default/objects/ALMSettings__c/ALMSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ALM Settings</label>
</CustomObject>

mywork/force-app/main/default/objects/ALMSettings__c/fields/Enable_Custom_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Custom_Backlogs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls accessibility to custom backlogs</description>
    <label>Enable Custom Backlogs</label>
    <type>Checkbox</type>
</CustomField>

mywork/force-app/main/default/objects/Custom_Backlog__c/Custom_Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/classes/TestCustomBacklogViewExt.cls
@isTest
private class TestCustomBacklogViewExt {

    static testMethod void customBacklogViewRedirectsToCorrectPage_withPermissions() {
        ALMSettings__c settings = new ALMSettings__c(Enable_Custom_Backlogs__c = true);
        insert settings;

        Custom_Backlog__c customBacklog = new Custom_Backlog__c();
        insert customBacklog;

        ApexPages.StandardController sc = new ApexPages.StandardController( customBacklog );
        CustomBacklogViewExt customBacklogMgmtController = new CustomBacklogViewExt(sc);

        Test.startTest();
            PageReference redirect = customBacklogMgmtController.doRedirect();
        Test.stopTest();

        Map<String, String> redirectParams = redirect.getParameters();

        System.assertEquals(customBacklog.Id, redirectParams.get(BacklogManagementExt.CUSTOM_BACKLOG_ID_PARAM),
                            'The user should be redirected to the Backlog Items Management page');
    }

    static testMethod void customBacklogViewRedirectsToCorrectPage_withoutPermissions() {
        Custom_Backlog__c customBacklog = new Custom_Backlog__c();
        insert customBacklog;

        ApexPages.StandardController sc = new ApexPages.StandardController( customBacklog );
        CustomBacklogViewExt customBacklogMgmtController = new CustomBacklogViewExt(sc);

        Test.startTest();
            PageReference redirect = customBacklogMgmtController.doRedirect();
        Test.stopTest();

        Map<String, String> redirectParams = redirect.getParameters();

        System.assertEquals(null, redirectParams.get(BacklogManagementExt.CUSTOM_BACKLOG_ID_PARAM),
                            'No custom backlog id should be provided to the redirect');
    }
}