mywork/force-app/main/default/objects/ALM_User__c/ALM_User__c.object-meta.xml
<CustomObject>
    <label>ALM User</label>
    <nameField>
        <label>ALM User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/ALM_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ALM_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/ALM_User_Role__c/ALM_User_Role__c.object-meta.xml
<CustomObject>
    <description>Stores roles available for use when assigning a user to a record.</description>
    <label>ALM User Role</label>
    <nameField>
        <label>ALM User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <description>Represents backlog items which can be features, stories or defects.</description>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_User__c/Backlog_User__c.object-meta.xml
<CustomObject>
    <label>Backlog Item User</label>
    <nameField>
        <displayFormat>BU-{0000}</displayFormat>
        <label>Backlog Item User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Item Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Backlog_User__c/fields/ALM_User__c.field-meta.xml
<CustomField>
    <fullName>ALM_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ALM User</label>
    <referenceTo>ALM_User__c</referenceTo>
    <relationshipLabel>Backlog Users</relationshipLabel>
    <relationshipName>Backlog_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_User__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog Item</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>Backlog Users</relationshipLabel>
    <relationshipName>Backlog_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Backlog_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role of the team member</description>
    <label>Role</label>
    <referenceTo>ALM_User_Role__c</referenceTo>
    <relationshipLabel>Backlog Item Users</relationshipLabel>
    <relationshipName>Backlog_Item_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint_User__c/Sprint_User__c.object-meta.xml
<CustomObject>
    <label>Sprint User</label>
    <nameField>
        <displayFormat>SU-{000000}</displayFormat>
        <label>Sprint User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mywork/force-app/main/default/objects/Sprint_User__c/fields/ALM_User__c.field-meta.xml
<CustomField>
    <fullName>ALM_User__c</fullName>
    <label>ALM User</label>
    <referenceTo>ALM_User__c</referenceTo>
    <relationshipLabel>Spint Users</relationshipLabel>
    <relationshipName>Spint_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>ALM_User_Role__c</referenceTo>
    <relationshipLabel>Spint Users</relationshipLabel>
    <relationshipName>Spint_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

mywork/force-app/main/default/objects/Sprint_User__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>Spint Users</relationshipLabel>
    <relationshipName>Spint_Users</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mywork/force-app/main/default/classes/UserAssignment.cls
public with sharing class UserAssignment {

    public SObject record    {get; set;}
    public String  name      {get; set;}
    public String  almUserId {get; set;}
    public String  photoURL  {get; set;}

    public String  role {
        get {
            return (String) record.get(SObjectServices.getFullyQualifiedName('Role__c'));
        }
        set {
            record.put(SObjectServices.getFullyQualifiedName('Role__c'), value);
        }
    }

    public String roleDisplay {
        get {

            if (String.isNotBlank(roleDisplay)) {
                return roleDisplay;
            } else if (String.isBlank(role)) {
                return 'Assign Role';
            } else {
                sObject  role =  record.getSObject(SObjectServices.getFullyQualifiedName('Role__r'));
                return (role == null) ? 'Assign Role' : (String)role.get('Name');
            }
        }
        set;
    }

    public String roleName {
        get {
            sObject  role =  record.getSObject(SObjectServices.getFullyQualifiedName('Role__r'));
            return (role == null) ? '' : (String)role.get('Name');
        }
        set;
    }

    /**
     * For existing user assignments
     * @param  record  A Backlog_User__c or a Sprint_User__c
     */
    public UserAssignment(SObject record) {
        this(record, (ALM_User__c) record.getSObject('ALM_User__r'));
    }

    /**
     * @param   record  A Sprint_User__c or a Backlog_User__c
     * @param   user    an ALM_User__c
     */
    private UserAssignment(SObject record, ALM_User__c user) {

        this.record = record;
        this.almUserId = user.Id;
        this.name = user.Name;

        if (user.User__r != null && ALMUserServices.isChatterEnabled()) {
            SObject relatedUser = user.getSObject('User__r');
            photoURL = String.valueOf( relatedUser.get('SmallPhotoUrl') );
        } else {
            photoURL = ALMUserServices.DEFAULT_USER_IMAGE_URL;
        }
    }

    /**
     * @param   targetId    A Sprint__c or a Backlog__c
     * @param   user        An ALM_User__c
     */
    public static UserAssignment create(Id targetId, ALM_User__c user) {
        if (targetId.getSObjectType() == Backlog__c.SObjectType) {
            return new UserAssignment(new Backlog_User__c(Backlog__c = targetId, ALM_User__c = user.Id), user);
        } else if (targetId.getSObjectType() == Sprint__c.SObjectType) {
            return new UserAssignment(new Sprint_User__c(Sprint__c = targetId, ALM_User__c = user.Id), user);
        } else {
            throw new ALMException('Invalid user assignment type.');
        }

        return null;
    }
}